apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: postgresql
resources:
  - service.yaml
  - statefulset.yaml
configMapGenerator:
  - name: postgresql-hooks
    files:
      - scripts/pre-stop.sh
secretGenerator:
  - name: postgresql-secrets
    literals:
      - admin-password=admin_password
      - postgres-password=event_planner_password
      - repmgr-password=repmgr_password
