apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: postgresql-
commonLabels:
  app: postgresql
resources:
  - headless-svc.yaml
  - statefulset.yaml
configMapGenerator:
  - name: init
    files:
      - scripts/init.sql
  - name: hooks
    files:
      - scripts/pre-stop.sh
secretGenerator:
  - name: secrets
    literals:
      - admin-password=admin_password
      - postgres-password=event_planner_password
      - repmgr-password=repmgr_password
