kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: es-logging
rules:
  - apiGroups:
      - ''
    resources:
      - 'services'
      - 'namespaces'
      - 'endpoints'
    verbs:
      - 'get'
