apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: elasticsearch
resources:
  - cluster-role.yaml
  - cluster-role-binding.yaml
  - service.yaml
  - service-account.yaml
  - statefulset.yaml
