apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: rest
      port: 9200
      targetPort: rest
      protocol: TCP
  selector:
    app: logging
