apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-node
spec:
  serviceName: elasticsearch
  replicas: 3
  selector:
    matchLabels:
      app: elasticsearch
  template:
    spec:
      serviceAccountName: es-logging
      containers:
        - name: elasticsearch
          image: elasticsearch:7.14.2
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 1
              memory: 2Gi
            requests:
              cpu: 1
              memory: 1Gi
          ports:
            - name: rest
              containerPort: 9200
              protocol: TCP
            - name: transport
              containerPort: 9300
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /usr/share/elasticsearch/data
          env:
            - name: cluster.name
              value: event-planner-logs
            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: discovery.seed_hosts
              value: 'es-node-0.elasticsearch,es-node-1.elasticsearch,es-node-2.elasticsearch'
            - name: cluster.initial_master_nodes
              value: 'es-node-0,es-node-1,es-node-2'
            - name: ES_JAVA_OPTS
              value: '-Xms1g -Xmx1g'
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ['sh', '-c', 'chown -R 1000:1000 /usr/share/elasticsearch/data']
          securityContext:
            privileged: true
          volumeMounts:
            - name: data
              mountPath: /usr/share/elasticsearch/data
        - name: increase-vm-max-map
          image: busybox
          command: ['sysctl', '-w', 'vm.max_map_count=262144']
          securityContext:
            privileged: true
        - name: increase-fd-ulimit
          image: busybox
          command: ['sh', '-c', 'ulimit -n 65536']
          securityContext:
            privileged: true
  #      affinity:
  #        podAntiAffinity:
  #          requiredDuringSchedulingIgnoredDuringExecution:
  #            - labelSelector:
  #                matchExpressions:
  #                  - key: app
  #                    operator: In
  #                    values:
  #                      - elasticsearch
  #              topologyKey: "kubernetes.io/hostname"
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
