apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    spec:
      containers:
        - name: kibana
          image: kibana:7.14.2
          imagePullPolicy: Always
          resources:
            requests:
              memory: 128Mi
            limits:
              memory: 1Gi
          env:
            - name: ELASTICSEARCH_HOSTS
              value: '["http://es-node-0.elasticsearch:9200","http://es-node-1.elasticsearch:9200","http://es-node-2.elasticsearch:9200"]'
            - name: K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - name: ui
              containerPort: 5601
              protocol: TCP
