// flow-typed signature: cd57659e6e36191a6f7a8cf961b8e31c
// flow-typed version: <<STUB>>/@auth0/auth0-react_v^1.11.0/flow_v0.186.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@auth0/auth0-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@auth0/auth0-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@auth0/auth0-react/dist/auth0-react.cjs' {
  declare module.exports: any;
}

declare module '@auth0/auth0-react/dist/auth0-react.esm' {
  declare module.exports: any;
}

declare module '@auth0/auth0-react/dist/auth0-react' {
  declare module.exports: any;
}

declare module '@auth0/auth0-react/dist/auth0-react.min' {
  declare module.exports: any;
}

// Filename aliases
declare module '@auth0/auth0-react/dist/auth0-react.cjs.js' {
  declare module.exports: $Exports<'@auth0/auth0-react/dist/auth0-react.cjs'>;
}
declare module '@auth0/auth0-react/dist/auth0-react.esm.js' {
  declare module.exports: $Exports<'@auth0/auth0-react/dist/auth0-react.esm'>;
}
declare module '@auth0/auth0-react/dist/auth0-react.js' {
  declare module.exports: $Exports<'@auth0/auth0-react/dist/auth0-react'>;
}
declare module '@auth0/auth0-react/dist/auth0-react.min.js' {
  declare module.exports: $Exports<'@auth0/auth0-react/dist/auth0-react.min'>;
}
