language: java
jdk: openjdk11

dist: bionic
os: linux

if: tag is blank

notifications:
  email: false

addons:
  sonarcloud:
    organization: 'bbortt-github'
    token:
      secure: 'r80d5AzN1vc/C00mbNV+KEwGzscYJLYvadxqBh8iG/WjdoGgZ3MuZ/PNi55gl3C/C4J/U5haDUhQ0R70Jajhh2ptgJgYq8PZAmOyrrAQxFg1+iWh9IUhx7UUyP6lvAPw3H6ubMtpq7bAaiR/WUrHHWpkQs0e1+XD0Q955Y4lohN+TSlpSKbLpkdNMcO7z5Z+4Y4WeUScsOONQOAr3vYJBjX0/iRrshTLH6K5QLMRf9vcZwUCw2Y6xX+TgD2AYqqIKBUGEFsTHTcl7bxnSX+36QH9ktxmW0hxkD6q5ZtcAlc8qMQZL0AgQXDbCSsSPQ8quFruQ/WqkvgGjU2C93ax5SP+1EsRXGUnXwIw0IhKUs+v+QJulNTWxleXsoDMRVsG4V0DeHgx8wF8jvxCV/3VvJ3/tvipZAisMnKfVSQuFjAQROU/m4lW62lKFP3SNAZ+se5+m1P6dRVPKfZd2OY2t6RreOjBIhxTgZgZvg4e2eHOg5BuugQ6FPI4VJmAdoNJtDoaUGRLCdRviwsqxreLNRCcrA4j5KoZHWuYk/9S8CqP4cbzpA3qiH9iKe4DnaWrKFleUNw2XVQZH8nY8KtWLMaQkpZ4YjKpRmnBFs8XL5UrVuUUM0P1A07uou+KYCXipd624bskda2TfV2/YsoOdveyAKxjRQ7l/DitkmIDTyA='

script:
  - ./gradlew dependencyUpdates
  - ./gradlew -Pversion=$TRAVIS_BUILD_NUMBER -Pprod --no-daemon -i build jacocoTestReport sonarqube

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/

cache:
  - npm
  - directories:
      - $HOME/.gradle/caches/
      - $HOME/.gradle/wrapper/
