language: java

dist: bionic
os: linux

install: skip

if: tag is blank

notifications:
  email: false

env:
  global:
    - secure: 'tB0ltTbDaJTTntOQLWRSHqSW1yRMoL8Fceb7pNpcVWZ0z7QfSreC4eeYqZNGjMfnlaSOASIUaX5XJ53p9y+ZS8cdVbBiNf5lXKA2yWMxxWhevE0jXGTcpMay+OCCpv90V2bjXjx3+DgmW6d2jKJUEqu8z3u2VG4rvNJiACranf7eUocBbbzKGlAp4gMymWde+Ytu/Dpso5d2v3A6uriZNagYZNv2tUD2262uEv4MZVx+bG9+wkFbLEAoI1OvyLtjG9J5fNHUiDDCm0gEqvOuJ5zYJj36Og5z5mdFDZ/JVAzDN+eVIuN82SQzYVVDqibQB6FFkXUTajJ300U/iSG2QqkgEgFx0YiuHNjSPSmKii/96vaPy++v4vBgy5LQj3IggWLn3Rb7597+4sNL16eCACfhY8+XkqpMF7tv90ybJYUslA0F1s3p8GnvCfGsRhfTmn8pS+yEOcGEw3TViUoNj9VjgWvPIHefWtiJRcacbFxqIcUUMaskd7t20HL3ivHNC1Lm3fqMhXIvmgXpXDajIdg6OuuiZDIfBBZUAHngH6fUwuVpxS7B9fq41iWgPxNFjG5SYkxNSkGQq46t6VJHXO+t+mzlR6XI8nA5m3pBE/WuMURic/T80CznKoztoNF1rkyKO5inemapEPVf+qAajRyNVt9B4IB1NSff4XFeIzA='
      # ^^ GAE_PROJECT_ID
    - secure: 'oi6/G1hn+RNFAD+lYhCjFT/KzrA8SVExwNGQhhI3zdHizGKB4WYL6ab1k2jyy6Whjh2wZyBU0DXugk5UUaV5APnlt1N1DhicDKclvUfYlY2rjN13XJ2yqzgiZgLVOhsUqSMKEgrpnLrgjNf66SJEG+YJui0RbhWNk1PDTltw2A03GxflbaQcH3OE/MaYj4QO93lCnK9YaSNLRSs6WCHAEpONdVJo3IcJMz78rda38q6GS+fM8+KbPA4D4AYYLHsEC8+/WRECmWbJcyiFQPmy0sa4hg2cERTHtKgaH8zjESEod0dy7u2ZEbipDGglL6LU9Igyhg9GToyd3fCraZPscOByxyFxciqaAO0DuXLKrpAIjtF/BsG5npVBsV2MRQbLoj6yVvcc5NbcLnkQmjAoFK0O8AXvuoeBB3yzj3UF6WE9s5t7B0uRO2NxWCQGMu87q4URgGvpa6QsYqOrjIVqjBryGxWRBdh+WF6/rGFPzCXMU2ajwy+3ja4ZO49vfYW6fVrmpcNg+Rd63nhQlAmgOjgZqpG8BcVAI0nWir7RTBeOEpLjiQMSQVWAccWmaDE9APye4czs9jXT/kps/jBHVuj7ZEG1x973B+Yp6qmydaOgb2SsTHIZ6q6oCwGMij4qS2Rfi4WFKtBkURYH5417w8BQcMB71k6dKI8L+Au9TxM='
      # ^^ GITHUB_TOKEN

services:
  - docker

addons:
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
  sonarcloud:
    organization: 'bbortt-github'
    token:
      secure: 'GiBbIV9/Rf/scaC/gAqw5+gp1n2Lv2BMWiTge5gkHMJGz93QEIlfjuqDe2vfWYrFRa4fXZmYDjTn1ZdppRdvfV25UsN9udH4ItUyMtzdSoY4+XOdCYQ29e4sVVl+oo+m0A5x3KvnLIwIbWapHkNjNDz8vwpafYOEzJf6dIPzXvpjgYv6P4VZkEJPcw0O5DMYPLFe0zE11KFkdPczwdKdbDMuDZB+8VM/JuJcDw9Oz+B2j5TFlZeCj7sOq+ZMEKR72kaOr8yrH23FO/PTD/qwKKl0/0sJy66aPRaUwU0c5cIm5U0+/OEzPeTifFL3Xrk3uLlkWMREWhz5C5ehYItsQi+igMFUnhRxSq/KnoUqjiUs3RJ00QH/Xq+gxF28Yq51KmzXSMWHfgHnzK5ZVvOt1RHceK3tD0WaVpRtfYIuzoTsKUd/uBiGKIUk9EmJNsZBSmqsdbKV05Xwjun9m2lCGS9x8fKlL/z6Zf8rJlu5EWohhrx+XJlxvbs30qKfIo/8rCPaolSp5SghM4cNPmZ+P89I746sKbqsBAyH1E1FlDP1qwUgQbfX0+xNuSjRjm98f4vqd0yh+LRku+Hhtcmr7L3wGveB8EC0bjJ5o7uVRc6Z73oGylHrjAi47SmJDn6u5lU+UXl0HHZ+Uv9gQ2ENuBVKklo9H942YtBZN6xdwRE='

jobs:
  include:
    # OpenJDK - Java 11 (lts, main build with Sonar)
    - env:
        - MAIN_BUILD="true"
        - BUILD_VERSION=$TRAVIS_BUILD_NUMBER
      jdk: openjdk11
    # OpenJDK - Java 13 (latest)
    - env:
        - MAIN_BUILD="false"
        - BUILD_VERSION="0.0.1-SNAPSHOT"
      jdk: openjdk13

before_install:
  - sudo sed -i "s/port = 5433/port = 5432/" /etc/postgresql/12/main/postgresql.conf
  - sudo cp /etc/postgresql/{9.3,12}/main/pg_hba.conf
  - sudo pg_ctlcluster 12 main restart

before_script:
  - psql -c "CREATE DATABASE event_planner_integration;" -U postgres
  - psql -c "CREATE USER event_planner WITH PASSWORD 'event_planner_password';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE event_planner_integration TO event_planner;" -U postgres

script:
  - if [[ "${MAIN_BUILD}" == "true" ]]; then export GRADLE_COMMAND="build jacocoTestReport sonarqube"; else export GRADLE_COMMAND="check"; fi
  - ./gradlew -Pversion=$BUILD_VERSION -Pprod --no-daemon -i dependencyUpdates ${GRADLE_COMMAND}

after_success:
  - test $MAIN_BUILD = "true" &&
    bash <(curl -s https://codecov.io/bash) &&
    docker build . --build-arg JAR_FILE=event-planner-$TRAVIS_BUILD_NUMBER.jar --tag gcr.io/$GAE_PROJECT_ID/event-planner:$TRAVIS_BUILD_NUMBER

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/

cache:
  - npm
  - directories:
      - $HOME/.gradle/caches/
      - $HOME/.gradle/wrapper/
      - $HOME/.sonar/cache
      - $HOME/google-cloud-sdk/

before_deploy:
  - openssl enc -aes-256-cbc -d -base64 -k $GAE_TAR_KEY -S $GAE_TAR_SALT -iv "D142327B0FF7E582D5658EB38EDB3234" -iter 10000 -in gae.tar.enc -out gae.tar
  - tar xvf gae.tar
  - .travis/install_gcloud_sdk.sh
  - gcloud auth activate-service-account --key-file travis-ci-service-account.key.json
  - gcloud config set project $GAE_PROJECT_ID

deploy:
  provider: script
  script: .travis/deploy_env.sh canary $GAE_PROJECT_ID $TRAVIS_BUILD_NUMBER
  on:
    repo: bbortt/event-planner
    branch: canary
    condition: $MAIN_BUILD = "true"
  skip_cleanup: true
