// flow-typed signature: 5669382a8034d879d10b36d8f5433538
// flow-typed version: <<STUB>>/eslint-config-next_v^12.1.5/flow_v0.176.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-next'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-next' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-next/core-web-vitals' {
  declare module.exports: any;
}

declare module 'eslint-config-next/parser' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-next/core-web-vitals.js' {
  declare module.exports: $Exports<'eslint-config-next/core-web-vitals'>;
}
declare module 'eslint-config-next/index' {
  declare module.exports: $Exports<'eslint-config-next'>;
}
declare module 'eslint-config-next/index.js' {
  declare module.exports: $Exports<'eslint-config-next'>;
}
declare module 'eslint-config-next/parser.js' {
  declare module.exports: $Exports<'eslint-config-next/parser'>;
}
