// flow-typed signature: 2ea226f1972ced968ef2ec1a94de6b8f
// flow-typed version: <<STUB>>/foundation-sites_v^6.7.4/flow_v0.176.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'foundation-sites'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'foundation-sites' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'foundation-sites/customizer/lib' {
  declare module.exports: any;
}

declare module 'foundation-sites/customizer/lib/js' {
  declare module.exports: any;
}

declare module 'foundation-sites/customizer/lib/sass' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/foundation.cjs' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/foundation.es6' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/foundation.esm' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/foundation' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/foundation.min' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/plugins/foundation.abide' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/plugins/foundation.abide.min' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/plugins/foundation.accordion' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/plugins/foundation.accordion.min' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/plugins/foundation.accordionMenu' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/plugins/foundation.accordionMenu.min' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/plugins/foundation.core' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/plugins/foundation.core.min' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/plugins/foundation.drilldown' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/plugins/foundation.drilldown.min' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/plugins/foundation.dropdown' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/plugins/foundation.dropdown.min' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/plugins/foundation.dropdownMenu' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/plugins/foundation.dropdownMenu.min' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/plugins/foundation.equalizer' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/plugins/foundation.equalizer.min' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/plugins/foundation.interchange' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/plugins/foundation.interchange.min' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/plugins/foundation.magellan' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/plugins/foundation.magellan.min' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/plugins/foundation.offcanvas' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/plugins/foundation.offcanvas.min' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/plugins/foundation.orbit' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/plugins/foundation.orbit.min' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/plugins/foundation.responsiveAccordionTabs' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/plugins/foundation.responsiveAccordionTabs.min' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/plugins/foundation.responsiveMenu' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/plugins/foundation.responsiveMenu.min' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/plugins/foundation.responsiveToggle' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/plugins/foundation.responsiveToggle.min' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/plugins/foundation.reveal' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/plugins/foundation.reveal.min' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/plugins/foundation.slider' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/plugins/foundation.slider.min' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/plugins/foundation.smoothScroll' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/plugins/foundation.smoothScroll.min' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/plugins/foundation.sticky' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/plugins/foundation.sticky.min' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/plugins/foundation.tabs' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/plugins/foundation.tabs.min' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/plugins/foundation.toggler' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/plugins/foundation.toggler.min' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/plugins/foundation.tooltip' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/plugins/foundation.tooltip.min' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/plugins/foundation.util.box' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/plugins/foundation.util.box.min' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/plugins/foundation.util.imageLoader' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/plugins/foundation.util.imageLoader.min' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/plugins/foundation.util.keyboard' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/plugins/foundation.util.keyboard.min' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/plugins/foundation.util.mediaQuery' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/plugins/foundation.util.mediaQuery.min' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/plugins/foundation.util.motion' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/plugins/foundation.util.motion.min' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/plugins/foundation.util.nest' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/plugins/foundation.util.nest.min' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/plugins/foundation.util.timer' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/plugins/foundation.util.timer.min' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/plugins/foundation.util.touch' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/plugins/foundation.util.touch.min' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/plugins/foundation.util.triggers' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/js/plugins/foundation.util.triggers.min' {
  declare module.exports: any;
}

declare module 'foundation-sites/docs/assets/img/gulpfile' {
  declare module.exports: any;
}

declare module 'foundation-sites/docs/assets/js/docs.ad' {
  declare module.exports: any;
}

declare module 'foundation-sites/docs/assets/js/docs.examples' {
  declare module.exports: any;
}

declare module 'foundation-sites/docs/assets/js/docs.interchangeMap' {
  declare module.exports: any;
}

declare module 'foundation-sites/docs/assets/js/docs' {
  declare module.exports: any;
}

declare module 'foundation-sites/gulp/config' {
  declare module.exports: any;
}

declare module 'foundation-sites/gulp/tasks/babel-error' {
  declare module.exports: any;
}

declare module 'foundation-sites/gulp/tasks/check' {
  declare module.exports: any;
}

declare module 'foundation-sites/gulp/tasks/clean' {
  declare module.exports: any;
}

declare module 'foundation-sites/gulp/tasks/copy' {
  declare module.exports: any;
}

declare module 'foundation-sites/gulp/tasks/customizer' {
  declare module.exports: any;
}

declare module 'foundation-sites/gulp/tasks/deploy' {
  declare module.exports: any;
}

declare module 'foundation-sites/gulp/tasks/docs' {
  declare module.exports: any;
}

declare module 'foundation-sites/gulp/tasks/javascript' {
  declare module.exports: any;
}

declare module 'foundation-sites/gulp/tasks/lint' {
  declare module.exports: any;
}

declare module 'foundation-sites/gulp/tasks/sass' {
  declare module.exports: any;
}

declare module 'foundation-sites/gulp/tasks/test' {
  declare module.exports: any;
}

declare module 'foundation-sites/gulp/utils' {
  declare module.exports: any;
}

declare module 'foundation-sites/gulpfile' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/entries/foundation-plugins' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/entries/foundation' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/entries/plugins/foundation.abide' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/entries/plugins/foundation.accordion' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/entries/plugins/foundation.accordionMenu' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/entries/plugins/foundation.core' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/entries/plugins/foundation.drilldown' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/entries/plugins/foundation.dropdown' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/entries/plugins/foundation.dropdownMenu' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/entries/plugins/foundation.equalizer' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/entries/plugins/foundation.interchange' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/entries/plugins/foundation.magellan' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/entries/plugins/foundation.offcanvas' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/entries/plugins/foundation.orbit' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/entries/plugins/foundation.responsiveAccordionTabs' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/entries/plugins/foundation.responsiveMenu' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/entries/plugins/foundation.responsiveToggle' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/entries/plugins/foundation.reveal' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/entries/plugins/foundation.slider' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/entries/plugins/foundation.smoothScroll' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/entries/plugins/foundation.sticky' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/entries/plugins/foundation.tabs' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/entries/plugins/foundation.toggler' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/entries/plugins/foundation.tooltip' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/entries/plugins/foundation.util.box' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/entries/plugins/foundation.util.imageLoader' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/entries/plugins/foundation.util.keyboard' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/entries/plugins/foundation.util.mediaQuery' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/entries/plugins/foundation.util.motion' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/entries/plugins/foundation.util.nest' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/entries/plugins/foundation.util.timer' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/entries/plugins/foundation.util.touch' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/entries/plugins/foundation.util.triggers' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation.abide' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation.accordion' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation.accordionMenu' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation.core' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation.core.plugin' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation.core.utils' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation.drilldown' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation.dropdown' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation.dropdownMenu' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation.equalizer' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation.interchange' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation.magellan' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation.offcanvas' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation.orbit' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation.positionable' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation.responsiveAccordionTabs' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation.responsiveMenu' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation.responsiveToggle' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation.reveal' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation.slider' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation.smoothScroll' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation.sticky' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation.tabs' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation.toggler' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation.tooltip' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation.util.box' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation.util.imageLoader' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation.util.keyboard' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation.util.mediaQuery' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation.util.motion' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation.util.nest' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation.util.timer' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation.util.touch' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation.util.triggers' {
  declare module.exports: any;
}

declare module 'foundation-sites/rollup.config' {
  declare module.exports: any;
}

declare module 'foundation-sites/script/husky-commit-lint' {
  declare module.exports: any;
}

declare module 'foundation-sites/script/husky-commit-test' {
  declare module.exports: any;
}

declare module 'foundation-sites/script/husky-push-test' {
  declare module.exports: any;
}

declare module 'foundation-sites/test/javascript/components/abide' {
  declare module.exports: any;
}

declare module 'foundation-sites/test/javascript/components/accordion' {
  declare module.exports: any;
}

declare module 'foundation-sites/test/javascript/components/accordionMenu' {
  declare module.exports: any;
}

declare module 'foundation-sites/test/javascript/components/drilldown' {
  declare module.exports: any;
}

declare module 'foundation-sites/test/javascript/components/dropdown' {
  declare module.exports: any;
}

declare module 'foundation-sites/test/javascript/components/dropdownMenu' {
  declare module.exports: any;
}

declare module 'foundation-sites/test/javascript/components/equalizer' {
  declare module.exports: any;
}

declare module 'foundation-sites/test/javascript/components/interchange' {
  declare module.exports: any;
}

declare module 'foundation-sites/test/javascript/components/magellan' {
  declare module.exports: any;
}

declare module 'foundation-sites/test/javascript/components/offcanvas' {
  declare module.exports: any;
}

declare module 'foundation-sites/test/javascript/components/orbit' {
  declare module.exports: any;
}

declare module 'foundation-sites/test/javascript/components/responsiveMenu' {
  declare module.exports: any;
}

declare module 'foundation-sites/test/javascript/components/responsiveToggle' {
  declare module.exports: any;
}

declare module 'foundation-sites/test/javascript/components/reveal' {
  declare module.exports: any;
}

declare module 'foundation-sites/test/javascript/components/slider' {
  declare module.exports: any;
}

declare module 'foundation-sites/test/javascript/components/sticky' {
  declare module.exports: any;
}

declare module 'foundation-sites/test/javascript/components/tabs' {
  declare module.exports: any;
}

declare module 'foundation-sites/test/javascript/components/toggler' {
  declare module.exports: any;
}

declare module 'foundation-sites/test/javascript/components/tooltip' {
  declare module.exports: any;
}

declare module 'foundation-sites/test/javascript/core/core' {
  declare module.exports: any;
}

declare module 'foundation-sites/test/javascript/core/utils' {
  declare module.exports: any;
}

declare module 'foundation-sites/test/javascript/lib/keyboard-event-mock' {
  declare module.exports: any;
}

declare module 'foundation-sites/test/javascript/lib/utils' {
  declare module.exports: any;
}

declare module 'foundation-sites/test/javascript/util/box' {
  declare module.exports: any;
}

declare module 'foundation-sites/test/javascript/util/keyboard' {
  declare module.exports: any;
}

declare module 'foundation-sites/test/javascript/util/mediaQuery' {
  declare module.exports: any;
}

declare module 'foundation-sites/test/sass/test_sass' {
  declare module.exports: any;
}

// Filename aliases
declare module 'foundation-sites/customizer/lib/index' {
  declare module.exports: $Exports<'foundation-sites/customizer/lib'>;
}
declare module 'foundation-sites/customizer/lib/index.js' {
  declare module.exports: $Exports<'foundation-sites/customizer/lib'>;
}
declare module 'foundation-sites/customizer/lib/js.js' {
  declare module.exports: $Exports<'foundation-sites/customizer/lib/js'>;
}
declare module 'foundation-sites/customizer/lib/sass.js' {
  declare module.exports: $Exports<'foundation-sites/customizer/lib/sass'>;
}
declare module 'foundation-sites/dist/js/foundation.cjs.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/foundation.cjs'>;
}
declare module 'foundation-sites/dist/js/foundation.es6.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/foundation.es6'>;
}
declare module 'foundation-sites/dist/js/foundation.esm.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/foundation.esm'>;
}
declare module 'foundation-sites/dist/js/foundation.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/foundation'>;
}
declare module 'foundation-sites/dist/js/foundation.min.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/foundation.min'>;
}
declare module 'foundation-sites/dist/js/plugins/foundation.abide.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/plugins/foundation.abide'>;
}
declare module 'foundation-sites/dist/js/plugins/foundation.abide.min.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/plugins/foundation.abide.min'>;
}
declare module 'foundation-sites/dist/js/plugins/foundation.accordion.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/plugins/foundation.accordion'>;
}
declare module 'foundation-sites/dist/js/plugins/foundation.accordion.min.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/plugins/foundation.accordion.min'>;
}
declare module 'foundation-sites/dist/js/plugins/foundation.accordionMenu.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/plugins/foundation.accordionMenu'>;
}
declare module 'foundation-sites/dist/js/plugins/foundation.accordionMenu.min.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/plugins/foundation.accordionMenu.min'>;
}
declare module 'foundation-sites/dist/js/plugins/foundation.core.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/plugins/foundation.core'>;
}
declare module 'foundation-sites/dist/js/plugins/foundation.core.min.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/plugins/foundation.core.min'>;
}
declare module 'foundation-sites/dist/js/plugins/foundation.drilldown.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/plugins/foundation.drilldown'>;
}
declare module 'foundation-sites/dist/js/plugins/foundation.drilldown.min.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/plugins/foundation.drilldown.min'>;
}
declare module 'foundation-sites/dist/js/plugins/foundation.dropdown.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/plugins/foundation.dropdown'>;
}
declare module 'foundation-sites/dist/js/plugins/foundation.dropdown.min.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/plugins/foundation.dropdown.min'>;
}
declare module 'foundation-sites/dist/js/plugins/foundation.dropdownMenu.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/plugins/foundation.dropdownMenu'>;
}
declare module 'foundation-sites/dist/js/plugins/foundation.dropdownMenu.min.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/plugins/foundation.dropdownMenu.min'>;
}
declare module 'foundation-sites/dist/js/plugins/foundation.equalizer.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/plugins/foundation.equalizer'>;
}
declare module 'foundation-sites/dist/js/plugins/foundation.equalizer.min.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/plugins/foundation.equalizer.min'>;
}
declare module 'foundation-sites/dist/js/plugins/foundation.interchange.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/plugins/foundation.interchange'>;
}
declare module 'foundation-sites/dist/js/plugins/foundation.interchange.min.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/plugins/foundation.interchange.min'>;
}
declare module 'foundation-sites/dist/js/plugins/foundation.magellan.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/plugins/foundation.magellan'>;
}
declare module 'foundation-sites/dist/js/plugins/foundation.magellan.min.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/plugins/foundation.magellan.min'>;
}
declare module 'foundation-sites/dist/js/plugins/foundation.offcanvas.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/plugins/foundation.offcanvas'>;
}
declare module 'foundation-sites/dist/js/plugins/foundation.offcanvas.min.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/plugins/foundation.offcanvas.min'>;
}
declare module 'foundation-sites/dist/js/plugins/foundation.orbit.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/plugins/foundation.orbit'>;
}
declare module 'foundation-sites/dist/js/plugins/foundation.orbit.min.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/plugins/foundation.orbit.min'>;
}
declare module 'foundation-sites/dist/js/plugins/foundation.responsiveAccordionTabs.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/plugins/foundation.responsiveAccordionTabs'>;
}
declare module 'foundation-sites/dist/js/plugins/foundation.responsiveAccordionTabs.min.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/plugins/foundation.responsiveAccordionTabs.min'>;
}
declare module 'foundation-sites/dist/js/plugins/foundation.responsiveMenu.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/plugins/foundation.responsiveMenu'>;
}
declare module 'foundation-sites/dist/js/plugins/foundation.responsiveMenu.min.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/plugins/foundation.responsiveMenu.min'>;
}
declare module 'foundation-sites/dist/js/plugins/foundation.responsiveToggle.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/plugins/foundation.responsiveToggle'>;
}
declare module 'foundation-sites/dist/js/plugins/foundation.responsiveToggle.min.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/plugins/foundation.responsiveToggle.min'>;
}
declare module 'foundation-sites/dist/js/plugins/foundation.reveal.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/plugins/foundation.reveal'>;
}
declare module 'foundation-sites/dist/js/plugins/foundation.reveal.min.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/plugins/foundation.reveal.min'>;
}
declare module 'foundation-sites/dist/js/plugins/foundation.slider.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/plugins/foundation.slider'>;
}
declare module 'foundation-sites/dist/js/plugins/foundation.slider.min.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/plugins/foundation.slider.min'>;
}
declare module 'foundation-sites/dist/js/plugins/foundation.smoothScroll.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/plugins/foundation.smoothScroll'>;
}
declare module 'foundation-sites/dist/js/plugins/foundation.smoothScroll.min.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/plugins/foundation.smoothScroll.min'>;
}
declare module 'foundation-sites/dist/js/plugins/foundation.sticky.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/plugins/foundation.sticky'>;
}
declare module 'foundation-sites/dist/js/plugins/foundation.sticky.min.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/plugins/foundation.sticky.min'>;
}
declare module 'foundation-sites/dist/js/plugins/foundation.tabs.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/plugins/foundation.tabs'>;
}
declare module 'foundation-sites/dist/js/plugins/foundation.tabs.min.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/plugins/foundation.tabs.min'>;
}
declare module 'foundation-sites/dist/js/plugins/foundation.toggler.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/plugins/foundation.toggler'>;
}
declare module 'foundation-sites/dist/js/plugins/foundation.toggler.min.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/plugins/foundation.toggler.min'>;
}
declare module 'foundation-sites/dist/js/plugins/foundation.tooltip.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/plugins/foundation.tooltip'>;
}
declare module 'foundation-sites/dist/js/plugins/foundation.tooltip.min.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/plugins/foundation.tooltip.min'>;
}
declare module 'foundation-sites/dist/js/plugins/foundation.util.box.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/plugins/foundation.util.box'>;
}
declare module 'foundation-sites/dist/js/plugins/foundation.util.box.min.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/plugins/foundation.util.box.min'>;
}
declare module 'foundation-sites/dist/js/plugins/foundation.util.imageLoader.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/plugins/foundation.util.imageLoader'>;
}
declare module 'foundation-sites/dist/js/plugins/foundation.util.imageLoader.min.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/plugins/foundation.util.imageLoader.min'>;
}
declare module 'foundation-sites/dist/js/plugins/foundation.util.keyboard.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/plugins/foundation.util.keyboard'>;
}
declare module 'foundation-sites/dist/js/plugins/foundation.util.keyboard.min.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/plugins/foundation.util.keyboard.min'>;
}
declare module 'foundation-sites/dist/js/plugins/foundation.util.mediaQuery.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/plugins/foundation.util.mediaQuery'>;
}
declare module 'foundation-sites/dist/js/plugins/foundation.util.mediaQuery.min.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/plugins/foundation.util.mediaQuery.min'>;
}
declare module 'foundation-sites/dist/js/plugins/foundation.util.motion.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/plugins/foundation.util.motion'>;
}
declare module 'foundation-sites/dist/js/plugins/foundation.util.motion.min.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/plugins/foundation.util.motion.min'>;
}
declare module 'foundation-sites/dist/js/plugins/foundation.util.nest.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/plugins/foundation.util.nest'>;
}
declare module 'foundation-sites/dist/js/plugins/foundation.util.nest.min.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/plugins/foundation.util.nest.min'>;
}
declare module 'foundation-sites/dist/js/plugins/foundation.util.timer.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/plugins/foundation.util.timer'>;
}
declare module 'foundation-sites/dist/js/plugins/foundation.util.timer.min.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/plugins/foundation.util.timer.min'>;
}
declare module 'foundation-sites/dist/js/plugins/foundation.util.touch.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/plugins/foundation.util.touch'>;
}
declare module 'foundation-sites/dist/js/plugins/foundation.util.touch.min.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/plugins/foundation.util.touch.min'>;
}
declare module 'foundation-sites/dist/js/plugins/foundation.util.triggers.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/plugins/foundation.util.triggers'>;
}
declare module 'foundation-sites/dist/js/plugins/foundation.util.triggers.min.js' {
  declare module.exports: $Exports<'foundation-sites/dist/js/plugins/foundation.util.triggers.min'>;
}
declare module 'foundation-sites/docs/assets/img/gulpfile.js' {
  declare module.exports: $Exports<'foundation-sites/docs/assets/img/gulpfile'>;
}
declare module 'foundation-sites/docs/assets/js/docs.ad.js' {
  declare module.exports: $Exports<'foundation-sites/docs/assets/js/docs.ad'>;
}
declare module 'foundation-sites/docs/assets/js/docs.examples.js' {
  declare module.exports: $Exports<'foundation-sites/docs/assets/js/docs.examples'>;
}
declare module 'foundation-sites/docs/assets/js/docs.interchangeMap.js' {
  declare module.exports: $Exports<'foundation-sites/docs/assets/js/docs.interchangeMap'>;
}
declare module 'foundation-sites/docs/assets/js/docs.js' {
  declare module.exports: $Exports<'foundation-sites/docs/assets/js/docs'>;
}
declare module 'foundation-sites/gulp/config.js' {
  declare module.exports: $Exports<'foundation-sites/gulp/config'>;
}
declare module 'foundation-sites/gulp/tasks/babel-error.js' {
  declare module.exports: $Exports<'foundation-sites/gulp/tasks/babel-error'>;
}
declare module 'foundation-sites/gulp/tasks/check.js' {
  declare module.exports: $Exports<'foundation-sites/gulp/tasks/check'>;
}
declare module 'foundation-sites/gulp/tasks/clean.js' {
  declare module.exports: $Exports<'foundation-sites/gulp/tasks/clean'>;
}
declare module 'foundation-sites/gulp/tasks/copy.js' {
  declare module.exports: $Exports<'foundation-sites/gulp/tasks/copy'>;
}
declare module 'foundation-sites/gulp/tasks/customizer.js' {
  declare module.exports: $Exports<'foundation-sites/gulp/tasks/customizer'>;
}
declare module 'foundation-sites/gulp/tasks/deploy.js' {
  declare module.exports: $Exports<'foundation-sites/gulp/tasks/deploy'>;
}
declare module 'foundation-sites/gulp/tasks/docs.js' {
  declare module.exports: $Exports<'foundation-sites/gulp/tasks/docs'>;
}
declare module 'foundation-sites/gulp/tasks/javascript.js' {
  declare module.exports: $Exports<'foundation-sites/gulp/tasks/javascript'>;
}
declare module 'foundation-sites/gulp/tasks/lint.js' {
  declare module.exports: $Exports<'foundation-sites/gulp/tasks/lint'>;
}
declare module 'foundation-sites/gulp/tasks/sass.js' {
  declare module.exports: $Exports<'foundation-sites/gulp/tasks/sass'>;
}
declare module 'foundation-sites/gulp/tasks/test.js' {
  declare module.exports: $Exports<'foundation-sites/gulp/tasks/test'>;
}
declare module 'foundation-sites/gulp/utils.js' {
  declare module.exports: $Exports<'foundation-sites/gulp/utils'>;
}
declare module 'foundation-sites/gulpfile.js' {
  declare module.exports: $Exports<'foundation-sites/gulpfile'>;
}
declare module 'foundation-sites/js/entries/foundation-plugins.js' {
  declare module.exports: $Exports<'foundation-sites/js/entries/foundation-plugins'>;
}
declare module 'foundation-sites/js/entries/foundation.js' {
  declare module.exports: $Exports<'foundation-sites/js/entries/foundation'>;
}
declare module 'foundation-sites/js/entries/plugins/foundation.abide.js' {
  declare module.exports: $Exports<'foundation-sites/js/entries/plugins/foundation.abide'>;
}
declare module 'foundation-sites/js/entries/plugins/foundation.accordion.js' {
  declare module.exports: $Exports<'foundation-sites/js/entries/plugins/foundation.accordion'>;
}
declare module 'foundation-sites/js/entries/plugins/foundation.accordionMenu.js' {
  declare module.exports: $Exports<'foundation-sites/js/entries/plugins/foundation.accordionMenu'>;
}
declare module 'foundation-sites/js/entries/plugins/foundation.core.js' {
  declare module.exports: $Exports<'foundation-sites/js/entries/plugins/foundation.core'>;
}
declare module 'foundation-sites/js/entries/plugins/foundation.drilldown.js' {
  declare module.exports: $Exports<'foundation-sites/js/entries/plugins/foundation.drilldown'>;
}
declare module 'foundation-sites/js/entries/plugins/foundation.dropdown.js' {
  declare module.exports: $Exports<'foundation-sites/js/entries/plugins/foundation.dropdown'>;
}
declare module 'foundation-sites/js/entries/plugins/foundation.dropdownMenu.js' {
  declare module.exports: $Exports<'foundation-sites/js/entries/plugins/foundation.dropdownMenu'>;
}
declare module 'foundation-sites/js/entries/plugins/foundation.equalizer.js' {
  declare module.exports: $Exports<'foundation-sites/js/entries/plugins/foundation.equalizer'>;
}
declare module 'foundation-sites/js/entries/plugins/foundation.interchange.js' {
  declare module.exports: $Exports<'foundation-sites/js/entries/plugins/foundation.interchange'>;
}
declare module 'foundation-sites/js/entries/plugins/foundation.magellan.js' {
  declare module.exports: $Exports<'foundation-sites/js/entries/plugins/foundation.magellan'>;
}
declare module 'foundation-sites/js/entries/plugins/foundation.offcanvas.js' {
  declare module.exports: $Exports<'foundation-sites/js/entries/plugins/foundation.offcanvas'>;
}
declare module 'foundation-sites/js/entries/plugins/foundation.orbit.js' {
  declare module.exports: $Exports<'foundation-sites/js/entries/plugins/foundation.orbit'>;
}
declare module 'foundation-sites/js/entries/plugins/foundation.responsiveAccordionTabs.js' {
  declare module.exports: $Exports<'foundation-sites/js/entries/plugins/foundation.responsiveAccordionTabs'>;
}
declare module 'foundation-sites/js/entries/plugins/foundation.responsiveMenu.js' {
  declare module.exports: $Exports<'foundation-sites/js/entries/plugins/foundation.responsiveMenu'>;
}
declare module 'foundation-sites/js/entries/plugins/foundation.responsiveToggle.js' {
  declare module.exports: $Exports<'foundation-sites/js/entries/plugins/foundation.responsiveToggle'>;
}
declare module 'foundation-sites/js/entries/plugins/foundation.reveal.js' {
  declare module.exports: $Exports<'foundation-sites/js/entries/plugins/foundation.reveal'>;
}
declare module 'foundation-sites/js/entries/plugins/foundation.slider.js' {
  declare module.exports: $Exports<'foundation-sites/js/entries/plugins/foundation.slider'>;
}
declare module 'foundation-sites/js/entries/plugins/foundation.smoothScroll.js' {
  declare module.exports: $Exports<'foundation-sites/js/entries/plugins/foundation.smoothScroll'>;
}
declare module 'foundation-sites/js/entries/plugins/foundation.sticky.js' {
  declare module.exports: $Exports<'foundation-sites/js/entries/plugins/foundation.sticky'>;
}
declare module 'foundation-sites/js/entries/plugins/foundation.tabs.js' {
  declare module.exports: $Exports<'foundation-sites/js/entries/plugins/foundation.tabs'>;
}
declare module 'foundation-sites/js/entries/plugins/foundation.toggler.js' {
  declare module.exports: $Exports<'foundation-sites/js/entries/plugins/foundation.toggler'>;
}
declare module 'foundation-sites/js/entries/plugins/foundation.tooltip.js' {
  declare module.exports: $Exports<'foundation-sites/js/entries/plugins/foundation.tooltip'>;
}
declare module 'foundation-sites/js/entries/plugins/foundation.util.box.js' {
  declare module.exports: $Exports<'foundation-sites/js/entries/plugins/foundation.util.box'>;
}
declare module 'foundation-sites/js/entries/plugins/foundation.util.imageLoader.js' {
  declare module.exports: $Exports<'foundation-sites/js/entries/plugins/foundation.util.imageLoader'>;
}
declare module 'foundation-sites/js/entries/plugins/foundation.util.keyboard.js' {
  declare module.exports: $Exports<'foundation-sites/js/entries/plugins/foundation.util.keyboard'>;
}
declare module 'foundation-sites/js/entries/plugins/foundation.util.mediaQuery.js' {
  declare module.exports: $Exports<'foundation-sites/js/entries/plugins/foundation.util.mediaQuery'>;
}
declare module 'foundation-sites/js/entries/plugins/foundation.util.motion.js' {
  declare module.exports: $Exports<'foundation-sites/js/entries/plugins/foundation.util.motion'>;
}
declare module 'foundation-sites/js/entries/plugins/foundation.util.nest.js' {
  declare module.exports: $Exports<'foundation-sites/js/entries/plugins/foundation.util.nest'>;
}
declare module 'foundation-sites/js/entries/plugins/foundation.util.timer.js' {
  declare module.exports: $Exports<'foundation-sites/js/entries/plugins/foundation.util.timer'>;
}
declare module 'foundation-sites/js/entries/plugins/foundation.util.touch.js' {
  declare module.exports: $Exports<'foundation-sites/js/entries/plugins/foundation.util.touch'>;
}
declare module 'foundation-sites/js/entries/plugins/foundation.util.triggers.js' {
  declare module.exports: $Exports<'foundation-sites/js/entries/plugins/foundation.util.triggers'>;
}
declare module 'foundation-sites/js/foundation.abide.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation.abide'>;
}
declare module 'foundation-sites/js/foundation.accordion.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation.accordion'>;
}
declare module 'foundation-sites/js/foundation.accordionMenu.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation.accordionMenu'>;
}
declare module 'foundation-sites/js/foundation.core.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation.core'>;
}
declare module 'foundation-sites/js/foundation.core.plugin.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation.core.plugin'>;
}
declare module 'foundation-sites/js/foundation.core.utils.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation.core.utils'>;
}
declare module 'foundation-sites/js/foundation.drilldown.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation.drilldown'>;
}
declare module 'foundation-sites/js/foundation.dropdown.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation.dropdown'>;
}
declare module 'foundation-sites/js/foundation.dropdownMenu.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation.dropdownMenu'>;
}
declare module 'foundation-sites/js/foundation.equalizer.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation.equalizer'>;
}
declare module 'foundation-sites/js/foundation.interchange.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation.interchange'>;
}
declare module 'foundation-sites/js/foundation.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation'>;
}
declare module 'foundation-sites/js/foundation.magellan.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation.magellan'>;
}
declare module 'foundation-sites/js/foundation.offcanvas.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation.offcanvas'>;
}
declare module 'foundation-sites/js/foundation.orbit.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation.orbit'>;
}
declare module 'foundation-sites/js/foundation.positionable.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation.positionable'>;
}
declare module 'foundation-sites/js/foundation.responsiveAccordionTabs.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation.responsiveAccordionTabs'>;
}
declare module 'foundation-sites/js/foundation.responsiveMenu.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation.responsiveMenu'>;
}
declare module 'foundation-sites/js/foundation.responsiveToggle.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation.responsiveToggle'>;
}
declare module 'foundation-sites/js/foundation.reveal.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation.reveal'>;
}
declare module 'foundation-sites/js/foundation.slider.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation.slider'>;
}
declare module 'foundation-sites/js/foundation.smoothScroll.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation.smoothScroll'>;
}
declare module 'foundation-sites/js/foundation.sticky.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation.sticky'>;
}
declare module 'foundation-sites/js/foundation.tabs.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation.tabs'>;
}
declare module 'foundation-sites/js/foundation.toggler.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation.toggler'>;
}
declare module 'foundation-sites/js/foundation.tooltip.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation.tooltip'>;
}
declare module 'foundation-sites/js/foundation.util.box.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation.util.box'>;
}
declare module 'foundation-sites/js/foundation.util.imageLoader.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation.util.imageLoader'>;
}
declare module 'foundation-sites/js/foundation.util.keyboard.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation.util.keyboard'>;
}
declare module 'foundation-sites/js/foundation.util.mediaQuery.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation.util.mediaQuery'>;
}
declare module 'foundation-sites/js/foundation.util.motion.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation.util.motion'>;
}
declare module 'foundation-sites/js/foundation.util.nest.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation.util.nest'>;
}
declare module 'foundation-sites/js/foundation.util.timer.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation.util.timer'>;
}
declare module 'foundation-sites/js/foundation.util.touch.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation.util.touch'>;
}
declare module 'foundation-sites/js/foundation.util.triggers.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation.util.triggers'>;
}
declare module 'foundation-sites/rollup.config.js' {
  declare module.exports: $Exports<'foundation-sites/rollup.config'>;
}
declare module 'foundation-sites/script/husky-commit-lint.js' {
  declare module.exports: $Exports<'foundation-sites/script/husky-commit-lint'>;
}
declare module 'foundation-sites/script/husky-commit-test.js' {
  declare module.exports: $Exports<'foundation-sites/script/husky-commit-test'>;
}
declare module 'foundation-sites/script/husky-push-test.js' {
  declare module.exports: $Exports<'foundation-sites/script/husky-push-test'>;
}
declare module 'foundation-sites/test/javascript/components/abide.js' {
  declare module.exports: $Exports<'foundation-sites/test/javascript/components/abide'>;
}
declare module 'foundation-sites/test/javascript/components/accordion.js' {
  declare module.exports: $Exports<'foundation-sites/test/javascript/components/accordion'>;
}
declare module 'foundation-sites/test/javascript/components/accordionMenu.js' {
  declare module.exports: $Exports<'foundation-sites/test/javascript/components/accordionMenu'>;
}
declare module 'foundation-sites/test/javascript/components/drilldown.js' {
  declare module.exports: $Exports<'foundation-sites/test/javascript/components/drilldown'>;
}
declare module 'foundation-sites/test/javascript/components/dropdown.js' {
  declare module.exports: $Exports<'foundation-sites/test/javascript/components/dropdown'>;
}
declare module 'foundation-sites/test/javascript/components/dropdownMenu.js' {
  declare module.exports: $Exports<'foundation-sites/test/javascript/components/dropdownMenu'>;
}
declare module 'foundation-sites/test/javascript/components/equalizer.js' {
  declare module.exports: $Exports<'foundation-sites/test/javascript/components/equalizer'>;
}
declare module 'foundation-sites/test/javascript/components/interchange.js' {
  declare module.exports: $Exports<'foundation-sites/test/javascript/components/interchange'>;
}
declare module 'foundation-sites/test/javascript/components/magellan.js' {
  declare module.exports: $Exports<'foundation-sites/test/javascript/components/magellan'>;
}
declare module 'foundation-sites/test/javascript/components/offcanvas.js' {
  declare module.exports: $Exports<'foundation-sites/test/javascript/components/offcanvas'>;
}
declare module 'foundation-sites/test/javascript/components/orbit.js' {
  declare module.exports: $Exports<'foundation-sites/test/javascript/components/orbit'>;
}
declare module 'foundation-sites/test/javascript/components/responsiveMenu.js' {
  declare module.exports: $Exports<'foundation-sites/test/javascript/components/responsiveMenu'>;
}
declare module 'foundation-sites/test/javascript/components/responsiveToggle.js' {
  declare module.exports: $Exports<'foundation-sites/test/javascript/components/responsiveToggle'>;
}
declare module 'foundation-sites/test/javascript/components/reveal.js' {
  declare module.exports: $Exports<'foundation-sites/test/javascript/components/reveal'>;
}
declare module 'foundation-sites/test/javascript/components/slider.js' {
  declare module.exports: $Exports<'foundation-sites/test/javascript/components/slider'>;
}
declare module 'foundation-sites/test/javascript/components/sticky.js' {
  declare module.exports: $Exports<'foundation-sites/test/javascript/components/sticky'>;
}
declare module 'foundation-sites/test/javascript/components/tabs.js' {
  declare module.exports: $Exports<'foundation-sites/test/javascript/components/tabs'>;
}
declare module 'foundation-sites/test/javascript/components/toggler.js' {
  declare module.exports: $Exports<'foundation-sites/test/javascript/components/toggler'>;
}
declare module 'foundation-sites/test/javascript/components/tooltip.js' {
  declare module.exports: $Exports<'foundation-sites/test/javascript/components/tooltip'>;
}
declare module 'foundation-sites/test/javascript/core/core.js' {
  declare module.exports: $Exports<'foundation-sites/test/javascript/core/core'>;
}
declare module 'foundation-sites/test/javascript/core/utils.js' {
  declare module.exports: $Exports<'foundation-sites/test/javascript/core/utils'>;
}
declare module 'foundation-sites/test/javascript/lib/keyboard-event-mock.js' {
  declare module.exports: $Exports<'foundation-sites/test/javascript/lib/keyboard-event-mock'>;
}
declare module 'foundation-sites/test/javascript/lib/utils.js' {
  declare module.exports: $Exports<'foundation-sites/test/javascript/lib/utils'>;
}
declare module 'foundation-sites/test/javascript/util/box.js' {
  declare module.exports: $Exports<'foundation-sites/test/javascript/util/box'>;
}
declare module 'foundation-sites/test/javascript/util/keyboard.js' {
  declare module.exports: $Exports<'foundation-sites/test/javascript/util/keyboard'>;
}
declare module 'foundation-sites/test/javascript/util/mediaQuery.js' {
  declare module.exports: $Exports<'foundation-sites/test/javascript/util/mediaQuery'>;
}
declare module 'foundation-sites/test/sass/test_sass.js' {
  declare module.exports: $Exports<'foundation-sites/test/sass/test_sass'>;
}
