// flow-typed signature: 5d6e6334894718722dc713bc911ebbe3
// flow-typed version: <<STUB>>/graphql_v^16.6.0/flow_v0.186.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graphql/error/GraphQLError' {
  declare module.exports: any;
}

declare module 'graphql/error' {
  declare module.exports: any;
}

declare module 'graphql/error/locatedError' {
  declare module.exports: any;
}

declare module 'graphql/error/syntaxError' {
  declare module.exports: any;
}

declare module 'graphql/execution/collectFields' {
  declare module.exports: any;
}

declare module 'graphql/execution/execute' {
  declare module.exports: any;
}

declare module 'graphql/execution' {
  declare module.exports: any;
}

declare module 'graphql/execution/mapAsyncIterator' {
  declare module.exports: any;
}

declare module 'graphql/execution/subscribe' {
  declare module.exports: any;
}

declare module 'graphql/execution/values' {
  declare module.exports: any;
}

declare module 'graphql/graphql' {
  declare module.exports: any;
}

declare module 'graphql/jsutils/devAssert' {
  declare module.exports: any;
}

declare module 'graphql/jsutils/didYouMean' {
  declare module.exports: any;
}

declare module 'graphql/jsutils/groupBy' {
  declare module.exports: any;
}

declare module 'graphql/jsutils/identityFunc' {
  declare module.exports: any;
}

declare module 'graphql/jsutils/inspect' {
  declare module.exports: any;
}

declare module 'graphql/jsutils/instanceOf' {
  declare module.exports: any;
}

declare module 'graphql/jsutils/invariant' {
  declare module.exports: any;
}

declare module 'graphql/jsutils/isAsyncIterable' {
  declare module.exports: any;
}

declare module 'graphql/jsutils/isIterableObject' {
  declare module.exports: any;
}

declare module 'graphql/jsutils/isObjectLike' {
  declare module.exports: any;
}

declare module 'graphql/jsutils/isPromise' {
  declare module.exports: any;
}

declare module 'graphql/jsutils/keyMap' {
  declare module.exports: any;
}

declare module 'graphql/jsutils/keyValMap' {
  declare module.exports: any;
}

declare module 'graphql/jsutils/mapValue' {
  declare module.exports: any;
}

declare module 'graphql/jsutils/Maybe' {
  declare module.exports: any;
}

declare module 'graphql/jsutils/memoize3' {
  declare module.exports: any;
}

declare module 'graphql/jsutils/naturalCompare' {
  declare module.exports: any;
}

declare module 'graphql/jsutils/ObjMap' {
  declare module.exports: any;
}

declare module 'graphql/jsutils/Path' {
  declare module.exports: any;
}

declare module 'graphql/jsutils/printPathArray' {
  declare module.exports: any;
}

declare module 'graphql/jsutils/promiseForObject' {
  declare module.exports: any;
}

declare module 'graphql/jsutils/PromiseOrValue' {
  declare module.exports: any;
}

declare module 'graphql/jsutils/promiseReduce' {
  declare module.exports: any;
}

declare module 'graphql/jsutils/suggestionList' {
  declare module.exports: any;
}

declare module 'graphql/jsutils/toError' {
  declare module.exports: any;
}

declare module 'graphql/jsutils/toObjMap' {
  declare module.exports: any;
}

declare module 'graphql/language/ast' {
  declare module.exports: any;
}

declare module 'graphql/language/blockString' {
  declare module.exports: any;
}

declare module 'graphql/language/characterClasses' {
  declare module.exports: any;
}

declare module 'graphql/language/directiveLocation' {
  declare module.exports: any;
}

declare module 'graphql/language' {
  declare module.exports: any;
}

declare module 'graphql/language/kinds' {
  declare module.exports: any;
}

declare module 'graphql/language/lexer' {
  declare module.exports: any;
}

declare module 'graphql/language/location' {
  declare module.exports: any;
}

declare module 'graphql/language/parser' {
  declare module.exports: any;
}

declare module 'graphql/language/predicates' {
  declare module.exports: any;
}

declare module 'graphql/language/printer' {
  declare module.exports: any;
}

declare module 'graphql/language/printLocation' {
  declare module.exports: any;
}

declare module 'graphql/language/printString' {
  declare module.exports: any;
}

declare module 'graphql/language/source' {
  declare module.exports: any;
}

declare module 'graphql/language/tokenKind' {
  declare module.exports: any;
}

declare module 'graphql/language/visitor' {
  declare module.exports: any;
}

declare module 'graphql/subscription' {
  declare module.exports: any;
}

declare module 'graphql/type/assertName' {
  declare module.exports: any;
}

declare module 'graphql/type/definition' {
  declare module.exports: any;
}

declare module 'graphql/type/directives' {
  declare module.exports: any;
}

declare module 'graphql/type' {
  declare module.exports: any;
}

declare module 'graphql/type/introspection' {
  declare module.exports: any;
}

declare module 'graphql/type/scalars' {
  declare module.exports: any;
}

declare module 'graphql/type/schema' {
  declare module.exports: any;
}

declare module 'graphql/type/validate' {
  declare module.exports: any;
}

declare module 'graphql/utilities/assertValidName' {
  declare module.exports: any;
}

declare module 'graphql/utilities/astFromValue' {
  declare module.exports: any;
}

declare module 'graphql/utilities/buildASTSchema' {
  declare module.exports: any;
}

declare module 'graphql/utilities/buildClientSchema' {
  declare module.exports: any;
}

declare module 'graphql/utilities/coerceInputValue' {
  declare module.exports: any;
}

declare module 'graphql/utilities/concatAST' {
  declare module.exports: any;
}

declare module 'graphql/utilities/extendSchema' {
  declare module.exports: any;
}

declare module 'graphql/utilities/findBreakingChanges' {
  declare module.exports: any;
}

declare module 'graphql/utilities/getIntrospectionQuery' {
  declare module.exports: any;
}

declare module 'graphql/utilities/getOperationAST' {
  declare module.exports: any;
}

declare module 'graphql/utilities/getOperationRootType' {
  declare module.exports: any;
}

declare module 'graphql/utilities' {
  declare module.exports: any;
}

declare module 'graphql/utilities/introspectionFromSchema' {
  declare module.exports: any;
}

declare module 'graphql/utilities/lexicographicSortSchema' {
  declare module.exports: any;
}

declare module 'graphql/utilities/printSchema' {
  declare module.exports: any;
}

declare module 'graphql/utilities/separateOperations' {
  declare module.exports: any;
}

declare module 'graphql/utilities/sortValueNode' {
  declare module.exports: any;
}

declare module 'graphql/utilities/stripIgnoredCharacters' {
  declare module.exports: any;
}

declare module 'graphql/utilities/typeComparators' {
  declare module.exports: any;
}

declare module 'graphql/utilities/typedQueryDocumentNode' {
  declare module.exports: any;
}

declare module 'graphql/utilities/typeFromAST' {
  declare module.exports: any;
}

declare module 'graphql/utilities/TypeInfo' {
  declare module.exports: any;
}

declare module 'graphql/utilities/valueFromAST' {
  declare module.exports: any;
}

declare module 'graphql/utilities/valueFromASTUntyped' {
  declare module.exports: any;
}

declare module 'graphql/validation' {
  declare module.exports: any;
}

declare module 'graphql/validation/rules/custom/NoDeprecatedCustomRule' {
  declare module.exports: any;
}

declare module 'graphql/validation/rules/custom/NoSchemaIntrospectionCustomRule' {
  declare module.exports: any;
}

declare module 'graphql/validation/rules/ExecutableDefinitionsRule' {
  declare module.exports: any;
}

declare module 'graphql/validation/rules/FieldsOnCorrectTypeRule' {
  declare module.exports: any;
}

declare module 'graphql/validation/rules/FragmentsOnCompositeTypesRule' {
  declare module.exports: any;
}

declare module 'graphql/validation/rules/KnownArgumentNamesRule' {
  declare module.exports: any;
}

declare module 'graphql/validation/rules/KnownDirectivesRule' {
  declare module.exports: any;
}

declare module 'graphql/validation/rules/KnownFragmentNamesRule' {
  declare module.exports: any;
}

declare module 'graphql/validation/rules/KnownTypeNamesRule' {
  declare module.exports: any;
}

declare module 'graphql/validation/rules/LoneAnonymousOperationRule' {
  declare module.exports: any;
}

declare module 'graphql/validation/rules/LoneSchemaDefinitionRule' {
  declare module.exports: any;
}

declare module 'graphql/validation/rules/NoFragmentCyclesRule' {
  declare module.exports: any;
}

declare module 'graphql/validation/rules/NoUndefinedVariablesRule' {
  declare module.exports: any;
}

declare module 'graphql/validation/rules/NoUnusedFragmentsRule' {
  declare module.exports: any;
}

declare module 'graphql/validation/rules/NoUnusedVariablesRule' {
  declare module.exports: any;
}

declare module 'graphql/validation/rules/OverlappingFieldsCanBeMergedRule' {
  declare module.exports: any;
}

declare module 'graphql/validation/rules/PossibleFragmentSpreadsRule' {
  declare module.exports: any;
}

declare module 'graphql/validation/rules/PossibleTypeExtensionsRule' {
  declare module.exports: any;
}

declare module 'graphql/validation/rules/ProvidedRequiredArgumentsRule' {
  declare module.exports: any;
}

declare module 'graphql/validation/rules/ScalarLeafsRule' {
  declare module.exports: any;
}

declare module 'graphql/validation/rules/SingleFieldSubscriptionsRule' {
  declare module.exports: any;
}

declare module 'graphql/validation/rules/UniqueArgumentDefinitionNamesRule' {
  declare module.exports: any;
}

declare module 'graphql/validation/rules/UniqueArgumentNamesRule' {
  declare module.exports: any;
}

declare module 'graphql/validation/rules/UniqueDirectiveNamesRule' {
  declare module.exports: any;
}

declare module 'graphql/validation/rules/UniqueDirectivesPerLocationRule' {
  declare module.exports: any;
}

declare module 'graphql/validation/rules/UniqueEnumValueNamesRule' {
  declare module.exports: any;
}

declare module 'graphql/validation/rules/UniqueFieldDefinitionNamesRule' {
  declare module.exports: any;
}

declare module 'graphql/validation/rules/UniqueFragmentNamesRule' {
  declare module.exports: any;
}

declare module 'graphql/validation/rules/UniqueInputFieldNamesRule' {
  declare module.exports: any;
}

declare module 'graphql/validation/rules/UniqueOperationNamesRule' {
  declare module.exports: any;
}

declare module 'graphql/validation/rules/UniqueOperationTypesRule' {
  declare module.exports: any;
}

declare module 'graphql/validation/rules/UniqueTypeNamesRule' {
  declare module.exports: any;
}

declare module 'graphql/validation/rules/UniqueVariableNamesRule' {
  declare module.exports: any;
}

declare module 'graphql/validation/rules/ValuesOfCorrectTypeRule' {
  declare module.exports: any;
}

declare module 'graphql/validation/rules/VariablesAreInputTypesRule' {
  declare module.exports: any;
}

declare module 'graphql/validation/rules/VariablesInAllowedPositionRule' {
  declare module.exports: any;
}

declare module 'graphql/validation/specifiedRules' {
  declare module.exports: any;
}

declare module 'graphql/validation/validate' {
  declare module.exports: any;
}

declare module 'graphql/validation/ValidationContext' {
  declare module.exports: any;
}

declare module 'graphql/version' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graphql/error/GraphQLError.js' {
  declare module.exports: $Exports<'graphql/error/GraphQLError'>;
}
declare module 'graphql/error/index' {
  declare module.exports: $Exports<'graphql/error'>;
}
declare module 'graphql/error/index.js' {
  declare module.exports: $Exports<'graphql/error'>;
}
declare module 'graphql/error/locatedError.js' {
  declare module.exports: $Exports<'graphql/error/locatedError'>;
}
declare module 'graphql/error/syntaxError.js' {
  declare module.exports: $Exports<'graphql/error/syntaxError'>;
}
declare module 'graphql/execution/collectFields.js' {
  declare module.exports: $Exports<'graphql/execution/collectFields'>;
}
declare module 'graphql/execution/execute.js' {
  declare module.exports: $Exports<'graphql/execution/execute'>;
}
declare module 'graphql/execution/index' {
  declare module.exports: $Exports<'graphql/execution'>;
}
declare module 'graphql/execution/index.js' {
  declare module.exports: $Exports<'graphql/execution'>;
}
declare module 'graphql/execution/mapAsyncIterator.js' {
  declare module.exports: $Exports<'graphql/execution/mapAsyncIterator'>;
}
declare module 'graphql/execution/subscribe.js' {
  declare module.exports: $Exports<'graphql/execution/subscribe'>;
}
declare module 'graphql/execution/values.js' {
  declare module.exports: $Exports<'graphql/execution/values'>;
}
declare module 'graphql/graphql.js' {
  declare module.exports: $Exports<'graphql/graphql'>;
}
declare module 'graphql/index' {
  declare module.exports: $Exports<'graphql'>;
}
declare module 'graphql/index.js' {
  declare module.exports: $Exports<'graphql'>;
}
declare module 'graphql/jsutils/devAssert.js' {
  declare module.exports: $Exports<'graphql/jsutils/devAssert'>;
}
declare module 'graphql/jsutils/didYouMean.js' {
  declare module.exports: $Exports<'graphql/jsutils/didYouMean'>;
}
declare module 'graphql/jsutils/groupBy.js' {
  declare module.exports: $Exports<'graphql/jsutils/groupBy'>;
}
declare module 'graphql/jsutils/identityFunc.js' {
  declare module.exports: $Exports<'graphql/jsutils/identityFunc'>;
}
declare module 'graphql/jsutils/inspect.js' {
  declare module.exports: $Exports<'graphql/jsutils/inspect'>;
}
declare module 'graphql/jsutils/instanceOf.js' {
  declare module.exports: $Exports<'graphql/jsutils/instanceOf'>;
}
declare module 'graphql/jsutils/invariant.js' {
  declare module.exports: $Exports<'graphql/jsutils/invariant'>;
}
declare module 'graphql/jsutils/isAsyncIterable.js' {
  declare module.exports: $Exports<'graphql/jsutils/isAsyncIterable'>;
}
declare module 'graphql/jsutils/isIterableObject.js' {
  declare module.exports: $Exports<'graphql/jsutils/isIterableObject'>;
}
declare module 'graphql/jsutils/isObjectLike.js' {
  declare module.exports: $Exports<'graphql/jsutils/isObjectLike'>;
}
declare module 'graphql/jsutils/isPromise.js' {
  declare module.exports: $Exports<'graphql/jsutils/isPromise'>;
}
declare module 'graphql/jsutils/keyMap.js' {
  declare module.exports: $Exports<'graphql/jsutils/keyMap'>;
}
declare module 'graphql/jsutils/keyValMap.js' {
  declare module.exports: $Exports<'graphql/jsutils/keyValMap'>;
}
declare module 'graphql/jsutils/mapValue.js' {
  declare module.exports: $Exports<'graphql/jsutils/mapValue'>;
}
declare module 'graphql/jsutils/Maybe.js' {
  declare module.exports: $Exports<'graphql/jsutils/Maybe'>;
}
declare module 'graphql/jsutils/memoize3.js' {
  declare module.exports: $Exports<'graphql/jsutils/memoize3'>;
}
declare module 'graphql/jsutils/naturalCompare.js' {
  declare module.exports: $Exports<'graphql/jsutils/naturalCompare'>;
}
declare module 'graphql/jsutils/ObjMap.js' {
  declare module.exports: $Exports<'graphql/jsutils/ObjMap'>;
}
declare module 'graphql/jsutils/Path.js' {
  declare module.exports: $Exports<'graphql/jsutils/Path'>;
}
declare module 'graphql/jsutils/printPathArray.js' {
  declare module.exports: $Exports<'graphql/jsutils/printPathArray'>;
}
declare module 'graphql/jsutils/promiseForObject.js' {
  declare module.exports: $Exports<'graphql/jsutils/promiseForObject'>;
}
declare module 'graphql/jsutils/PromiseOrValue.js' {
  declare module.exports: $Exports<'graphql/jsutils/PromiseOrValue'>;
}
declare module 'graphql/jsutils/promiseReduce.js' {
  declare module.exports: $Exports<'graphql/jsutils/promiseReduce'>;
}
declare module 'graphql/jsutils/suggestionList.js' {
  declare module.exports: $Exports<'graphql/jsutils/suggestionList'>;
}
declare module 'graphql/jsutils/toError.js' {
  declare module.exports: $Exports<'graphql/jsutils/toError'>;
}
declare module 'graphql/jsutils/toObjMap.js' {
  declare module.exports: $Exports<'graphql/jsutils/toObjMap'>;
}
declare module 'graphql/language/ast.js' {
  declare module.exports: $Exports<'graphql/language/ast'>;
}
declare module 'graphql/language/blockString.js' {
  declare module.exports: $Exports<'graphql/language/blockString'>;
}
declare module 'graphql/language/characterClasses.js' {
  declare module.exports: $Exports<'graphql/language/characterClasses'>;
}
declare module 'graphql/language/directiveLocation.js' {
  declare module.exports: $Exports<'graphql/language/directiveLocation'>;
}
declare module 'graphql/language/index' {
  declare module.exports: $Exports<'graphql/language'>;
}
declare module 'graphql/language/index.js' {
  declare module.exports: $Exports<'graphql/language'>;
}
declare module 'graphql/language/kinds.js' {
  declare module.exports: $Exports<'graphql/language/kinds'>;
}
declare module 'graphql/language/lexer.js' {
  declare module.exports: $Exports<'graphql/language/lexer'>;
}
declare module 'graphql/language/location.js' {
  declare module.exports: $Exports<'graphql/language/location'>;
}
declare module 'graphql/language/parser.js' {
  declare module.exports: $Exports<'graphql/language/parser'>;
}
declare module 'graphql/language/predicates.js' {
  declare module.exports: $Exports<'graphql/language/predicates'>;
}
declare module 'graphql/language/printer.js' {
  declare module.exports: $Exports<'graphql/language/printer'>;
}
declare module 'graphql/language/printLocation.js' {
  declare module.exports: $Exports<'graphql/language/printLocation'>;
}
declare module 'graphql/language/printString.js' {
  declare module.exports: $Exports<'graphql/language/printString'>;
}
declare module 'graphql/language/source.js' {
  declare module.exports: $Exports<'graphql/language/source'>;
}
declare module 'graphql/language/tokenKind.js' {
  declare module.exports: $Exports<'graphql/language/tokenKind'>;
}
declare module 'graphql/language/visitor.js' {
  declare module.exports: $Exports<'graphql/language/visitor'>;
}
declare module 'graphql/subscription/index' {
  declare module.exports: $Exports<'graphql/subscription'>;
}
declare module 'graphql/subscription/index.js' {
  declare module.exports: $Exports<'graphql/subscription'>;
}
declare module 'graphql/type/assertName.js' {
  declare module.exports: $Exports<'graphql/type/assertName'>;
}
declare module 'graphql/type/definition.js' {
  declare module.exports: $Exports<'graphql/type/definition'>;
}
declare module 'graphql/type/directives.js' {
  declare module.exports: $Exports<'graphql/type/directives'>;
}
declare module 'graphql/type/index' {
  declare module.exports: $Exports<'graphql/type'>;
}
declare module 'graphql/type/index.js' {
  declare module.exports: $Exports<'graphql/type'>;
}
declare module 'graphql/type/introspection.js' {
  declare module.exports: $Exports<'graphql/type/introspection'>;
}
declare module 'graphql/type/scalars.js' {
  declare module.exports: $Exports<'graphql/type/scalars'>;
}
declare module 'graphql/type/schema.js' {
  declare module.exports: $Exports<'graphql/type/schema'>;
}
declare module 'graphql/type/validate.js' {
  declare module.exports: $Exports<'graphql/type/validate'>;
}
declare module 'graphql/utilities/assertValidName.js' {
  declare module.exports: $Exports<'graphql/utilities/assertValidName'>;
}
declare module 'graphql/utilities/astFromValue.js' {
  declare module.exports: $Exports<'graphql/utilities/astFromValue'>;
}
declare module 'graphql/utilities/buildASTSchema.js' {
  declare module.exports: $Exports<'graphql/utilities/buildASTSchema'>;
}
declare module 'graphql/utilities/buildClientSchema.js' {
  declare module.exports: $Exports<'graphql/utilities/buildClientSchema'>;
}
declare module 'graphql/utilities/coerceInputValue.js' {
  declare module.exports: $Exports<'graphql/utilities/coerceInputValue'>;
}
declare module 'graphql/utilities/concatAST.js' {
  declare module.exports: $Exports<'graphql/utilities/concatAST'>;
}
declare module 'graphql/utilities/extendSchema.js' {
  declare module.exports: $Exports<'graphql/utilities/extendSchema'>;
}
declare module 'graphql/utilities/findBreakingChanges.js' {
  declare module.exports: $Exports<'graphql/utilities/findBreakingChanges'>;
}
declare module 'graphql/utilities/getIntrospectionQuery.js' {
  declare module.exports: $Exports<'graphql/utilities/getIntrospectionQuery'>;
}
declare module 'graphql/utilities/getOperationAST.js' {
  declare module.exports: $Exports<'graphql/utilities/getOperationAST'>;
}
declare module 'graphql/utilities/getOperationRootType.js' {
  declare module.exports: $Exports<'graphql/utilities/getOperationRootType'>;
}
declare module 'graphql/utilities/index' {
  declare module.exports: $Exports<'graphql/utilities'>;
}
declare module 'graphql/utilities/index.js' {
  declare module.exports: $Exports<'graphql/utilities'>;
}
declare module 'graphql/utilities/introspectionFromSchema.js' {
  declare module.exports: $Exports<'graphql/utilities/introspectionFromSchema'>;
}
declare module 'graphql/utilities/lexicographicSortSchema.js' {
  declare module.exports: $Exports<'graphql/utilities/lexicographicSortSchema'>;
}
declare module 'graphql/utilities/printSchema.js' {
  declare module.exports: $Exports<'graphql/utilities/printSchema'>;
}
declare module 'graphql/utilities/separateOperations.js' {
  declare module.exports: $Exports<'graphql/utilities/separateOperations'>;
}
declare module 'graphql/utilities/sortValueNode.js' {
  declare module.exports: $Exports<'graphql/utilities/sortValueNode'>;
}
declare module 'graphql/utilities/stripIgnoredCharacters.js' {
  declare module.exports: $Exports<'graphql/utilities/stripIgnoredCharacters'>;
}
declare module 'graphql/utilities/typeComparators.js' {
  declare module.exports: $Exports<'graphql/utilities/typeComparators'>;
}
declare module 'graphql/utilities/typedQueryDocumentNode.js' {
  declare module.exports: $Exports<'graphql/utilities/typedQueryDocumentNode'>;
}
declare module 'graphql/utilities/typeFromAST.js' {
  declare module.exports: $Exports<'graphql/utilities/typeFromAST'>;
}
declare module 'graphql/utilities/TypeInfo.js' {
  declare module.exports: $Exports<'graphql/utilities/TypeInfo'>;
}
declare module 'graphql/utilities/valueFromAST.js' {
  declare module.exports: $Exports<'graphql/utilities/valueFromAST'>;
}
declare module 'graphql/utilities/valueFromASTUntyped.js' {
  declare module.exports: $Exports<'graphql/utilities/valueFromASTUntyped'>;
}
declare module 'graphql/validation/index' {
  declare module.exports: $Exports<'graphql/validation'>;
}
declare module 'graphql/validation/index.js' {
  declare module.exports: $Exports<'graphql/validation'>;
}
declare module 'graphql/validation/rules/custom/NoDeprecatedCustomRule.js' {
  declare module.exports: $Exports<'graphql/validation/rules/custom/NoDeprecatedCustomRule'>;
}
declare module 'graphql/validation/rules/custom/NoSchemaIntrospectionCustomRule.js' {
  declare module.exports: $Exports<'graphql/validation/rules/custom/NoSchemaIntrospectionCustomRule'>;
}
declare module 'graphql/validation/rules/ExecutableDefinitionsRule.js' {
  declare module.exports: $Exports<'graphql/validation/rules/ExecutableDefinitionsRule'>;
}
declare module 'graphql/validation/rules/FieldsOnCorrectTypeRule.js' {
  declare module.exports: $Exports<'graphql/validation/rules/FieldsOnCorrectTypeRule'>;
}
declare module 'graphql/validation/rules/FragmentsOnCompositeTypesRule.js' {
  declare module.exports: $Exports<'graphql/validation/rules/FragmentsOnCompositeTypesRule'>;
}
declare module 'graphql/validation/rules/KnownArgumentNamesRule.js' {
  declare module.exports: $Exports<'graphql/validation/rules/KnownArgumentNamesRule'>;
}
declare module 'graphql/validation/rules/KnownDirectivesRule.js' {
  declare module.exports: $Exports<'graphql/validation/rules/KnownDirectivesRule'>;
}
declare module 'graphql/validation/rules/KnownFragmentNamesRule.js' {
  declare module.exports: $Exports<'graphql/validation/rules/KnownFragmentNamesRule'>;
}
declare module 'graphql/validation/rules/KnownTypeNamesRule.js' {
  declare module.exports: $Exports<'graphql/validation/rules/KnownTypeNamesRule'>;
}
declare module 'graphql/validation/rules/LoneAnonymousOperationRule.js' {
  declare module.exports: $Exports<'graphql/validation/rules/LoneAnonymousOperationRule'>;
}
declare module 'graphql/validation/rules/LoneSchemaDefinitionRule.js' {
  declare module.exports: $Exports<'graphql/validation/rules/LoneSchemaDefinitionRule'>;
}
declare module 'graphql/validation/rules/NoFragmentCyclesRule.js' {
  declare module.exports: $Exports<'graphql/validation/rules/NoFragmentCyclesRule'>;
}
declare module 'graphql/validation/rules/NoUndefinedVariablesRule.js' {
  declare module.exports: $Exports<'graphql/validation/rules/NoUndefinedVariablesRule'>;
}
declare module 'graphql/validation/rules/NoUnusedFragmentsRule.js' {
  declare module.exports: $Exports<'graphql/validation/rules/NoUnusedFragmentsRule'>;
}
declare module 'graphql/validation/rules/NoUnusedVariablesRule.js' {
  declare module.exports: $Exports<'graphql/validation/rules/NoUnusedVariablesRule'>;
}
declare module 'graphql/validation/rules/OverlappingFieldsCanBeMergedRule.js' {
  declare module.exports: $Exports<'graphql/validation/rules/OverlappingFieldsCanBeMergedRule'>;
}
declare module 'graphql/validation/rules/PossibleFragmentSpreadsRule.js' {
  declare module.exports: $Exports<'graphql/validation/rules/PossibleFragmentSpreadsRule'>;
}
declare module 'graphql/validation/rules/PossibleTypeExtensionsRule.js' {
  declare module.exports: $Exports<'graphql/validation/rules/PossibleTypeExtensionsRule'>;
}
declare module 'graphql/validation/rules/ProvidedRequiredArgumentsRule.js' {
  declare module.exports: $Exports<'graphql/validation/rules/ProvidedRequiredArgumentsRule'>;
}
declare module 'graphql/validation/rules/ScalarLeafsRule.js' {
  declare module.exports: $Exports<'graphql/validation/rules/ScalarLeafsRule'>;
}
declare module 'graphql/validation/rules/SingleFieldSubscriptionsRule.js' {
  declare module.exports: $Exports<'graphql/validation/rules/SingleFieldSubscriptionsRule'>;
}
declare module 'graphql/validation/rules/UniqueArgumentDefinitionNamesRule.js' {
  declare module.exports: $Exports<'graphql/validation/rules/UniqueArgumentDefinitionNamesRule'>;
}
declare module 'graphql/validation/rules/UniqueArgumentNamesRule.js' {
  declare module.exports: $Exports<'graphql/validation/rules/UniqueArgumentNamesRule'>;
}
declare module 'graphql/validation/rules/UniqueDirectiveNamesRule.js' {
  declare module.exports: $Exports<'graphql/validation/rules/UniqueDirectiveNamesRule'>;
}
declare module 'graphql/validation/rules/UniqueDirectivesPerLocationRule.js' {
  declare module.exports: $Exports<'graphql/validation/rules/UniqueDirectivesPerLocationRule'>;
}
declare module 'graphql/validation/rules/UniqueEnumValueNamesRule.js' {
  declare module.exports: $Exports<'graphql/validation/rules/UniqueEnumValueNamesRule'>;
}
declare module 'graphql/validation/rules/UniqueFieldDefinitionNamesRule.js' {
  declare module.exports: $Exports<'graphql/validation/rules/UniqueFieldDefinitionNamesRule'>;
}
declare module 'graphql/validation/rules/UniqueFragmentNamesRule.js' {
  declare module.exports: $Exports<'graphql/validation/rules/UniqueFragmentNamesRule'>;
}
declare module 'graphql/validation/rules/UniqueInputFieldNamesRule.js' {
  declare module.exports: $Exports<'graphql/validation/rules/UniqueInputFieldNamesRule'>;
}
declare module 'graphql/validation/rules/UniqueOperationNamesRule.js' {
  declare module.exports: $Exports<'graphql/validation/rules/UniqueOperationNamesRule'>;
}
declare module 'graphql/validation/rules/UniqueOperationTypesRule.js' {
  declare module.exports: $Exports<'graphql/validation/rules/UniqueOperationTypesRule'>;
}
declare module 'graphql/validation/rules/UniqueTypeNamesRule.js' {
  declare module.exports: $Exports<'graphql/validation/rules/UniqueTypeNamesRule'>;
}
declare module 'graphql/validation/rules/UniqueVariableNamesRule.js' {
  declare module.exports: $Exports<'graphql/validation/rules/UniqueVariableNamesRule'>;
}
declare module 'graphql/validation/rules/ValuesOfCorrectTypeRule.js' {
  declare module.exports: $Exports<'graphql/validation/rules/ValuesOfCorrectTypeRule'>;
}
declare module 'graphql/validation/rules/VariablesAreInputTypesRule.js' {
  declare module.exports: $Exports<'graphql/validation/rules/VariablesAreInputTypesRule'>;
}
declare module 'graphql/validation/rules/VariablesInAllowedPositionRule.js' {
  declare module.exports: $Exports<'graphql/validation/rules/VariablesInAllowedPositionRule'>;
}
declare module 'graphql/validation/specifiedRules.js' {
  declare module.exports: $Exports<'graphql/validation/specifiedRules'>;
}
declare module 'graphql/validation/validate.js' {
  declare module.exports: $Exports<'graphql/validation/validate'>;
}
declare module 'graphql/validation/ValidationContext.js' {
  declare module.exports: $Exports<'graphql/validation/ValidationContext'>;
}
declare module 'graphql/version.js' {
  declare module.exports: $Exports<'graphql/version'>;
}
