// flow-typed signature: 2577bfb9023eca9ad3f8d9a283cf3f21
// flow-typed version: <<STUB>>/hasura-cli_v^2.0.9/flow_v0.160.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hasura-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hasura-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hasura-cli/dist/asset' {
  declare module.exports: any;
}

declare module 'hasura-cli/dist' {
  declare module.exports: any;
}

declare module 'hasura-cli/dist/install' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hasura-cli/dist/asset.js' {
  declare module.exports: $Exports<'hasura-cli/dist/asset'>;
}
declare module 'hasura-cli/dist/index' {
  declare module.exports: $Exports<'hasura-cli/dist'>;
}
declare module 'hasura-cli/dist/index.js' {
  declare module.exports: $Exports<'hasura-cli/dist'>;
}
declare module 'hasura-cli/dist/install.js' {
  declare module.exports: $Exports<'hasura-cli/dist/install'>;
}
