// flow-typed signature: b90803bcc9092b59b3f27a63d84e0f88
// flow-typed version: <<STUB>>/jest-sonar-reporter_v^2.0.0/flow_v0.186.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-sonar-reporter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-sonar-reporter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-sonar-reporter/lib/getDefaultConfig' {
  declare module.exports: any;
}

declare module 'jest-sonar-reporter/lib/reporter' {
  declare module.exports: any;
}

declare module 'jest-sonar-reporter/lib/utils/getConfig' {
  declare module.exports: any;
}

declare module 'jest-sonar-reporter/lib/utils/getPackageData' {
  declare module.exports: any;
}

declare module 'jest-sonar-reporter/lib/utils/isEmptyObject' {
  declare module.exports: any;
}

declare module 'jest-sonar-reporter/lib/utils/xmlIndent' {
  declare module.exports: any;
}

declare module 'jest-sonar-reporter/lib/xml/failure' {
  declare module.exports: any;
}

declare module 'jest-sonar-reporter/lib/xml/file' {
  declare module.exports: any;
}

declare module 'jest-sonar-reporter/lib/xml/testCase' {
  declare module.exports: any;
}

declare module 'jest-sonar-reporter/lib/xml/testExecutions' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-sonar-reporter/index' {
  declare module.exports: $Exports<'jest-sonar-reporter'>;
}
declare module 'jest-sonar-reporter/index.js' {
  declare module.exports: $Exports<'jest-sonar-reporter'>;
}
declare module 'jest-sonar-reporter/lib/getDefaultConfig.js' {
  declare module.exports: $Exports<'jest-sonar-reporter/lib/getDefaultConfig'>;
}
declare module 'jest-sonar-reporter/lib/reporter.js' {
  declare module.exports: $Exports<'jest-sonar-reporter/lib/reporter'>;
}
declare module 'jest-sonar-reporter/lib/utils/getConfig.js' {
  declare module.exports: $Exports<'jest-sonar-reporter/lib/utils/getConfig'>;
}
declare module 'jest-sonar-reporter/lib/utils/getPackageData.js' {
  declare module.exports: $Exports<'jest-sonar-reporter/lib/utils/getPackageData'>;
}
declare module 'jest-sonar-reporter/lib/utils/isEmptyObject.js' {
  declare module.exports: $Exports<'jest-sonar-reporter/lib/utils/isEmptyObject'>;
}
declare module 'jest-sonar-reporter/lib/utils/xmlIndent.js' {
  declare module.exports: $Exports<'jest-sonar-reporter/lib/utils/xmlIndent'>;
}
declare module 'jest-sonar-reporter/lib/xml/failure.js' {
  declare module.exports: $Exports<'jest-sonar-reporter/lib/xml/failure'>;
}
declare module 'jest-sonar-reporter/lib/xml/file.js' {
  declare module.exports: $Exports<'jest-sonar-reporter/lib/xml/file'>;
}
declare module 'jest-sonar-reporter/lib/xml/testCase.js' {
  declare module.exports: $Exports<'jest-sonar-reporter/lib/xml/testCase'>;
}
declare module 'jest-sonar-reporter/lib/xml/testExecutions.js' {
  declare module.exports: $Exports<'jest-sonar-reporter/lib/xml/testExecutions'>;
}
