// flow-typed signature: 56a623ed491d240a4248156afa4ac078
// flow-typed version: <<STUB>>/lib_vfile:src/main/webapp/lib/flow_v0.176.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lib'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lib' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lib/apollo/client' {
  declare module.exports: any;
}

declare module 'lib/apollo/mutation/locality.mutation' {
  declare module.exports: any;
}

declare module 'lib/apollo/mutation/member.mutation' {
  declare module.exports: any;
}

declare module 'lib/apollo/mutation/project.mutation' {
  declare module.exports: any;
}

declare module 'lib/apollo/query/locality.query' {
  declare module.exports: any;
}

declare module 'lib/apollo/query/project.query' {
  declare module.exports: any;
}

declare module 'lib/auth0/save-router-and-redirect' {
  declare module.exports: any;
}

declare module 'lib/component/project/card' {
  declare module.exports: any;
}

declare module 'lib/component/project/create.form' {
  declare module.exports: any;
}

declare module 'lib/component/project/locality/create.form' {
  declare module.exports: any;
}

declare module 'lib/component/project/locality/locality-drop-list' {
  declare module.exports: any;
}

declare module 'lib/component/project/locality/locality.drag' {
  declare module.exports: any;
}

declare module 'lib/component/project/locality/locality.drop' {
  declare module.exports: any;
}

declare module 'lib/component/project/locality/new-locality.reveal' {
  declare module.exports: any;
}

declare module 'lib/component/project/member' {
  declare module.exports: any;
}

declare module 'lib/component/project/navbar' {
  declare module.exports: any;
}

declare module 'lib/component/project/new-project.reveal' {
  declare module.exports: any;
}

declare module 'lib/constants' {
  declare module.exports: any;
}

declare module 'lib/container/landing-page' {
  declare module.exports: any;
}

declare module 'lib/container/message-list' {
  declare module.exports: any;
}

declare module 'lib/container/project' {
  declare module.exports: any;
}

declare module 'lib/container/project/list' {
  declare module.exports: any;
}

declare module 'lib/container/project/localities' {
  declare module.exports: any;
}

declare module 'lib/foundation/callout' {
  declare module.exports: any;
}

declare module 'lib/foundation/register-reveal-overlay-observer' {
  declare module.exports: any;
}

declare module 'lib/foundation/render-foundation-node' {
  declare module.exports: any;
}

declare module 'lib/layout/message/error.callout' {
  declare module.exports: any;
}

declare module 'lib/layout/message/loading.callout' {
  declare module.exports: any;
}

declare module 'lib/layout/navbar/account-dropdown' {
  declare module.exports: any;
}

declare module 'lib/layout/navbar' {
  declare module.exports: any;
}

declare module 'lib/model/message' {
  declare module.exports: any;
}

declare module 'lib/model/project-permission' {
  declare module.exports: any;
}

declare module 'lib/redux/action/locality.action' {
  declare module.exports: any;
}

declare module 'lib/redux/action/member.action' {
  declare module.exports: any;
}

declare module 'lib/redux/action/message.action' {
  declare module.exports: any;
}

declare module 'lib/redux/action/project.action' {
  declare module.exports: any;
}

declare module 'lib/redux/middleware/crash-reporting.middleware' {
  declare module.exports: any;
}

declare module 'lib/redux/middleware/logger.middleware' {
  declare module.exports: any;
}

declare module 'lib/redux/reducer' {
  declare module.exports: any;
}

declare module 'lib/redux/reducer/localities.reducer' {
  declare module.exports: any;
}

declare module 'lib/redux/reducer/messages.reducer' {
  declare module.exports: any;
}

declare module 'lib/redux/reducer/projects.reducer' {
  declare module.exports: any;
}

declare module 'lib/redux/saga' {
  declare module.exports: any;
}

declare module 'lib/redux/saga/locality.saga' {
  declare module.exports: any;
}

declare module 'lib/redux/saga/member.saga' {
  declare module.exports: any;
}

declare module 'lib/redux/saga/message.saga' {
  declare module.exports: any;
}

declare module 'lib/redux/saga/project.saga' {
  declare module.exports: any;
}

declare module 'lib/redux/selector/locality.selector' {
  declare module.exports: any;
}

declare module 'lib/redux/selector/message.selector' {
  declare module.exports: any;
}

declare module 'lib/redux/selector/project.selector' {
  declare module.exports: any;
}

declare module 'lib/redux/store' {
  declare module.exports: any;
}

declare module 'lib/wrapper/apollo-provider.wrapper' {
  declare module.exports: any;
}

declare module 'lib/wrapper/auth0-provider.wrapper' {
  declare module.exports: any;
}

declare module 'lib/wrapper/dnd-provider' {
  declare module.exports: any;
}

declare module 'lib/wrapper/redux.wrapper' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lib/apollo/client.js' {
  declare module.exports: $Exports<'lib/apollo/client'>;
}
declare module 'lib/apollo/mutation/locality.mutation.js' {
  declare module.exports: $Exports<'lib/apollo/mutation/locality.mutation'>;
}
declare module 'lib/apollo/mutation/member.mutation.js' {
  declare module.exports: $Exports<'lib/apollo/mutation/member.mutation'>;
}
declare module 'lib/apollo/mutation/project.mutation.js' {
  declare module.exports: $Exports<'lib/apollo/mutation/project.mutation'>;
}
declare module 'lib/apollo/query/locality.query.js' {
  declare module.exports: $Exports<'lib/apollo/query/locality.query'>;
}
declare module 'lib/apollo/query/project.query.js' {
  declare module.exports: $Exports<'lib/apollo/query/project.query'>;
}
declare module 'lib/auth0/save-router-and-redirect.js' {
  declare module.exports: $Exports<'lib/auth0/save-router-and-redirect'>;
}
declare module 'lib/component/project/card.js' {
  declare module.exports: $Exports<'lib/component/project/card'>;
}
declare module 'lib/component/project/create.form.js' {
  declare module.exports: $Exports<'lib/component/project/create.form'>;
}
declare module 'lib/component/project/locality/create.form.js' {
  declare module.exports: $Exports<'lib/component/project/locality/create.form'>;
}
declare module 'lib/component/project/locality/locality-drop-list.js' {
  declare module.exports: $Exports<'lib/component/project/locality/locality-drop-list'>;
}
declare module 'lib/component/project/locality/locality.drag.js' {
  declare module.exports: $Exports<'lib/component/project/locality/locality.drag'>;
}
declare module 'lib/component/project/locality/locality.drop.js' {
  declare module.exports: $Exports<'lib/component/project/locality/locality.drop'>;
}
declare module 'lib/component/project/locality/new-locality.reveal.js' {
  declare module.exports: $Exports<'lib/component/project/locality/new-locality.reveal'>;
}
declare module 'lib/component/project/member/index' {
  declare module.exports: $Exports<'lib/component/project/member'>;
}
declare module 'lib/component/project/member/index.js' {
  declare module.exports: $Exports<'lib/component/project/member'>;
}
declare module 'lib/component/project/navbar.js' {
  declare module.exports: $Exports<'lib/component/project/navbar'>;
}
declare module 'lib/component/project/new-project.reveal.js' {
  declare module.exports: $Exports<'lib/component/project/new-project.reveal'>;
}
declare module 'lib/constants.js' {
  declare module.exports: $Exports<'lib/constants'>;
}
declare module 'lib/container/landing-page.js' {
  declare module.exports: $Exports<'lib/container/landing-page'>;
}
declare module 'lib/container/message-list.js' {
  declare module.exports: $Exports<'lib/container/message-list'>;
}
declare module 'lib/container/project/index' {
  declare module.exports: $Exports<'lib/container/project'>;
}
declare module 'lib/container/project/index.js' {
  declare module.exports: $Exports<'lib/container/project'>;
}
declare module 'lib/container/project/list.js' {
  declare module.exports: $Exports<'lib/container/project/list'>;
}
declare module 'lib/container/project/localities.js' {
  declare module.exports: $Exports<'lib/container/project/localities'>;
}
declare module 'lib/foundation/callout.js' {
  declare module.exports: $Exports<'lib/foundation/callout'>;
}
declare module 'lib/foundation/register-reveal-overlay-observer.js' {
  declare module.exports: $Exports<'lib/foundation/register-reveal-overlay-observer'>;
}
declare module 'lib/foundation/render-foundation-node.js' {
  declare module.exports: $Exports<'lib/foundation/render-foundation-node'>;
}
declare module 'lib/layout/message/error.callout.js' {
  declare module.exports: $Exports<'lib/layout/message/error.callout'>;
}
declare module 'lib/layout/message/loading.callout.js' {
  declare module.exports: $Exports<'lib/layout/message/loading.callout'>;
}
declare module 'lib/layout/navbar/account-dropdown.js' {
  declare module.exports: $Exports<'lib/layout/navbar/account-dropdown'>;
}
declare module 'lib/layout/navbar/index' {
  declare module.exports: $Exports<'lib/layout/navbar'>;
}
declare module 'lib/layout/navbar/index.js' {
  declare module.exports: $Exports<'lib/layout/navbar'>;
}
declare module 'lib/model/message.js' {
  declare module.exports: $Exports<'lib/model/message'>;
}
declare module 'lib/model/project-permission.js' {
  declare module.exports: $Exports<'lib/model/project-permission'>;
}
declare module 'lib/redux/action/locality.action.js' {
  declare module.exports: $Exports<'lib/redux/action/locality.action'>;
}
declare module 'lib/redux/action/member.action.js' {
  declare module.exports: $Exports<'lib/redux/action/member.action'>;
}
declare module 'lib/redux/action/message.action.js' {
  declare module.exports: $Exports<'lib/redux/action/message.action'>;
}
declare module 'lib/redux/action/project.action.js' {
  declare module.exports: $Exports<'lib/redux/action/project.action'>;
}
declare module 'lib/redux/middleware/crash-reporting.middleware.js' {
  declare module.exports: $Exports<'lib/redux/middleware/crash-reporting.middleware'>;
}
declare module 'lib/redux/middleware/logger.middleware.js' {
  declare module.exports: $Exports<'lib/redux/middleware/logger.middleware'>;
}
declare module 'lib/redux/reducer/index' {
  declare module.exports: $Exports<'lib/redux/reducer'>;
}
declare module 'lib/redux/reducer/index.js' {
  declare module.exports: $Exports<'lib/redux/reducer'>;
}
declare module 'lib/redux/reducer/localities.reducer.js' {
  declare module.exports: $Exports<'lib/redux/reducer/localities.reducer'>;
}
declare module 'lib/redux/reducer/messages.reducer.js' {
  declare module.exports: $Exports<'lib/redux/reducer/messages.reducer'>;
}
declare module 'lib/redux/reducer/projects.reducer.js' {
  declare module.exports: $Exports<'lib/redux/reducer/projects.reducer'>;
}
declare module 'lib/redux/saga/index' {
  declare module.exports: $Exports<'lib/redux/saga'>;
}
declare module 'lib/redux/saga/index.js' {
  declare module.exports: $Exports<'lib/redux/saga'>;
}
declare module 'lib/redux/saga/locality.saga.js' {
  declare module.exports: $Exports<'lib/redux/saga/locality.saga'>;
}
declare module 'lib/redux/saga/member.saga.js' {
  declare module.exports: $Exports<'lib/redux/saga/member.saga'>;
}
declare module 'lib/redux/saga/message.saga.js' {
  declare module.exports: $Exports<'lib/redux/saga/message.saga'>;
}
declare module 'lib/redux/saga/project.saga.js' {
  declare module.exports: $Exports<'lib/redux/saga/project.saga'>;
}
declare module 'lib/redux/selector/locality.selector.js' {
  declare module.exports: $Exports<'lib/redux/selector/locality.selector'>;
}
declare module 'lib/redux/selector/message.selector.js' {
  declare module.exports: $Exports<'lib/redux/selector/message.selector'>;
}
declare module 'lib/redux/selector/project.selector.js' {
  declare module.exports: $Exports<'lib/redux/selector/project.selector'>;
}
declare module 'lib/redux/store.js' {
  declare module.exports: $Exports<'lib/redux/store'>;
}
declare module 'lib/wrapper/apollo-provider.wrapper.js' {
  declare module.exports: $Exports<'lib/wrapper/apollo-provider.wrapper'>;
}
declare module 'lib/wrapper/auth0-provider.wrapper.js' {
  declare module.exports: $Exports<'lib/wrapper/auth0-provider.wrapper'>;
}
declare module 'lib/wrapper/dnd-provider.js' {
  declare module.exports: $Exports<'lib/wrapper/dnd-provider'>;
}
declare module 'lib/wrapper/redux.wrapper.js' {
  declare module.exports: $Exports<'lib/wrapper/redux.wrapper'>;
}
