// flow-typed signature: 003f4dd58de8445757cd0ff6de121780
// flow-typed version: <<STUB>>/next-redux-wrapper_v^7.0.5/flow_v0.160.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'next-redux-wrapper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'next-redux-wrapper' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'next-redux-wrapper/es6' {
  declare module.exports: any;
}

declare module 'next-redux-wrapper/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'next-redux-wrapper/es6/index' {
  declare module.exports: $Exports<'next-redux-wrapper/es6'>;
}
declare module 'next-redux-wrapper/es6/index.js' {
  declare module.exports: $Exports<'next-redux-wrapper/es6'>;
}
declare module 'next-redux-wrapper/lib/index' {
  declare module.exports: $Exports<'next-redux-wrapper/lib'>;
}
declare module 'next-redux-wrapper/lib/index.js' {
  declare module.exports: $Exports<'next-redux-wrapper/lib'>;
}
