// flow-typed signature: 8ede24a0559af450ff09ae8e50c9de59
// flow-typed version: <<STUB>>/pages_vfile:src/pages/flow_v0.176.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pages'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pages' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pages/_app' {
  declare module.exports: any;
}

declare module 'pages/projects' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pages/_app.js' {
  declare module.exports: $Exports<'pages/_app'>;
}
declare module 'pages/index' {
  declare module.exports: $Exports<'pages'>;
}
declare module 'pages/index.js' {
  declare module.exports: $Exports<'pages'>;
}
declare module 'pages/projects.js' {
  declare module.exports: $Exports<'pages/projects'>;
}
