// flow-typed signature: 2c8ed2e51ba0ebf48217057793a2dad1
// flow-typed version: <<STUB>>/prettier-plugin-java_v^1.6.2/flow_v0.186.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prettier-plugin-java'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'prettier-plugin-java' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'prettier-plugin-java/dist/base-cst-printer' {
  declare module.exports: any;
}

declare module 'prettier-plugin-java/dist/cst-printer' {
  declare module.exports: any;
}

declare module 'prettier-plugin-java/dist' {
  declare module.exports: any;
}

declare module 'prettier-plugin-java/dist/options' {
  declare module.exports: any;
}

declare module 'prettier-plugin-java/dist/parser' {
  declare module.exports: any;
}

declare module 'prettier-plugin-java/dist/printer' {
  declare module.exports: any;
}

declare module 'prettier-plugin-java/dist/printers/arrays' {
  declare module.exports: any;
}

declare module 'prettier-plugin-java/dist/printers/blocks-and-statements' {
  declare module.exports: any;
}

declare module 'prettier-plugin-java/dist/printers/classes' {
  declare module.exports: any;
}

declare module 'prettier-plugin-java/dist/printers/comments/comments-utils' {
  declare module.exports: any;
}

declare module 'prettier-plugin-java/dist/printers/comments/format-comments' {
  declare module.exports: any;
}

declare module 'prettier-plugin-java/dist/printers/comments/handle-comments' {
  declare module.exports: any;
}

declare module 'prettier-plugin-java/dist/printers/expressions' {
  declare module.exports: any;
}

declare module 'prettier-plugin-java/dist/printers/interfaces' {
  declare module.exports: any;
}

declare module 'prettier-plugin-java/dist/printers/lexical-structure' {
  declare module.exports: any;
}

declare module 'prettier-plugin-java/dist/printers/names' {
  declare module.exports: any;
}

declare module 'prettier-plugin-java/dist/printers/packages-and-modules' {
  declare module.exports: any;
}

declare module 'prettier-plugin-java/dist/printers/prettier-builder' {
  declare module.exports: any;
}

declare module 'prettier-plugin-java/dist/printers/printer-utils' {
  declare module.exports: any;
}

declare module 'prettier-plugin-java/dist/printers/types-values-and-variables' {
  declare module.exports: any;
}

declare module 'prettier-plugin-java/dist/types/utils' {
  declare module.exports: any;
}

declare module 'prettier-plugin-java/dist/utils/constants' {
  declare module.exports: any;
}

declare module 'prettier-plugin-java/dist/utils/expressions-utils' {
  declare module.exports: any;
}

declare module 'prettier-plugin-java/dist/utils' {
  declare module.exports: any;
}

declare module 'prettier-plugin-java/dist/utils/printArgumentListWithBraces' {
  declare module.exports: any;
}

declare module 'prettier-plugin-java/dist/utils/printSingleLambdaInvocation' {
  declare module.exports: any;
}

// Filename aliases
declare module 'prettier-plugin-java/dist/base-cst-printer.js' {
  declare module.exports: $Exports<'prettier-plugin-java/dist/base-cst-printer'>;
}
declare module 'prettier-plugin-java/dist/cst-printer.js' {
  declare module.exports: $Exports<'prettier-plugin-java/dist/cst-printer'>;
}
declare module 'prettier-plugin-java/dist/index' {
  declare module.exports: $Exports<'prettier-plugin-java/dist'>;
}
declare module 'prettier-plugin-java/dist/index.js' {
  declare module.exports: $Exports<'prettier-plugin-java/dist'>;
}
declare module 'prettier-plugin-java/dist/options.js' {
  declare module.exports: $Exports<'prettier-plugin-java/dist/options'>;
}
declare module 'prettier-plugin-java/dist/parser.js' {
  declare module.exports: $Exports<'prettier-plugin-java/dist/parser'>;
}
declare module 'prettier-plugin-java/dist/printer.js' {
  declare module.exports: $Exports<'prettier-plugin-java/dist/printer'>;
}
declare module 'prettier-plugin-java/dist/printers/arrays.js' {
  declare module.exports: $Exports<'prettier-plugin-java/dist/printers/arrays'>;
}
declare module 'prettier-plugin-java/dist/printers/blocks-and-statements.js' {
  declare module.exports: $Exports<'prettier-plugin-java/dist/printers/blocks-and-statements'>;
}
declare module 'prettier-plugin-java/dist/printers/classes.js' {
  declare module.exports: $Exports<'prettier-plugin-java/dist/printers/classes'>;
}
declare module 'prettier-plugin-java/dist/printers/comments/comments-utils.js' {
  declare module.exports: $Exports<'prettier-plugin-java/dist/printers/comments/comments-utils'>;
}
declare module 'prettier-plugin-java/dist/printers/comments/format-comments.js' {
  declare module.exports: $Exports<'prettier-plugin-java/dist/printers/comments/format-comments'>;
}
declare module 'prettier-plugin-java/dist/printers/comments/handle-comments.js' {
  declare module.exports: $Exports<'prettier-plugin-java/dist/printers/comments/handle-comments'>;
}
declare module 'prettier-plugin-java/dist/printers/expressions.js' {
  declare module.exports: $Exports<'prettier-plugin-java/dist/printers/expressions'>;
}
declare module 'prettier-plugin-java/dist/printers/interfaces.js' {
  declare module.exports: $Exports<'prettier-plugin-java/dist/printers/interfaces'>;
}
declare module 'prettier-plugin-java/dist/printers/lexical-structure.js' {
  declare module.exports: $Exports<'prettier-plugin-java/dist/printers/lexical-structure'>;
}
declare module 'prettier-plugin-java/dist/printers/names.js' {
  declare module.exports: $Exports<'prettier-plugin-java/dist/printers/names'>;
}
declare module 'prettier-plugin-java/dist/printers/packages-and-modules.js' {
  declare module.exports: $Exports<'prettier-plugin-java/dist/printers/packages-and-modules'>;
}
declare module 'prettier-plugin-java/dist/printers/prettier-builder.js' {
  declare module.exports: $Exports<'prettier-plugin-java/dist/printers/prettier-builder'>;
}
declare module 'prettier-plugin-java/dist/printers/printer-utils.js' {
  declare module.exports: $Exports<'prettier-plugin-java/dist/printers/printer-utils'>;
}
declare module 'prettier-plugin-java/dist/printers/types-values-and-variables.js' {
  declare module.exports: $Exports<'prettier-plugin-java/dist/printers/types-values-and-variables'>;
}
declare module 'prettier-plugin-java/dist/types/utils.js' {
  declare module.exports: $Exports<'prettier-plugin-java/dist/types/utils'>;
}
declare module 'prettier-plugin-java/dist/utils/constants.js' {
  declare module.exports: $Exports<'prettier-plugin-java/dist/utils/constants'>;
}
declare module 'prettier-plugin-java/dist/utils/expressions-utils.js' {
  declare module.exports: $Exports<'prettier-plugin-java/dist/utils/expressions-utils'>;
}
declare module 'prettier-plugin-java/dist/utils/index' {
  declare module.exports: $Exports<'prettier-plugin-java/dist/utils'>;
}
declare module 'prettier-plugin-java/dist/utils/index.js' {
  declare module.exports: $Exports<'prettier-plugin-java/dist/utils'>;
}
declare module 'prettier-plugin-java/dist/utils/printArgumentListWithBraces.js' {
  declare module.exports: $Exports<'prettier-plugin-java/dist/utils/printArgumentListWithBraces'>;
}
declare module 'prettier-plugin-java/dist/utils/printSingleLambdaInvocation.js' {
  declare module.exports: $Exports<'prettier-plugin-java/dist/utils/printSingleLambdaInvocation'>;
}
