// flow-typed signature: 5e4a2f79c800ff889426cb9b6edcc2c0
// flow-typed version: <<STUB>>/react-dnd-html5-backend_v^16.0.1/flow_v0.176.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-dnd-html5-backend'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-dnd-html5-backend' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-dnd-html5-backend/dist/BrowserDetector' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/dist/EnterLeaveCounter' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/dist/getEmptyImage' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/dist/HTML5BackendImpl' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/dist' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/dist/matchesType' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/dist/MonotonicInterpolant' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/dist/NativeDragSources/getDataFromDataTransfer' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/dist/NativeDragSources' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/dist/NativeDragSources/NativeDragSource' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/dist/NativeDragSources/nativeTypesConfig' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/dist/NativeTypes' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/dist/OffsetUtils' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/dist/OptionsReader' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/dist/types' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/dist/utils/js_utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-dnd-html5-backend/dist/BrowserDetector.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/dist/BrowserDetector'>;
}
declare module 'react-dnd-html5-backend/dist/EnterLeaveCounter.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/dist/EnterLeaveCounter'>;
}
declare module 'react-dnd-html5-backend/dist/getEmptyImage.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/dist/getEmptyImage'>;
}
declare module 'react-dnd-html5-backend/dist/HTML5BackendImpl.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/dist/HTML5BackendImpl'>;
}
declare module 'react-dnd-html5-backend/dist/index' {
  declare module.exports: $Exports<'react-dnd-html5-backend/dist'>;
}
declare module 'react-dnd-html5-backend/dist/index.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/dist'>;
}
declare module 'react-dnd-html5-backend/dist/matchesType.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/dist/matchesType'>;
}
declare module 'react-dnd-html5-backend/dist/MonotonicInterpolant.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/dist/MonotonicInterpolant'>;
}
declare module 'react-dnd-html5-backend/dist/NativeDragSources/getDataFromDataTransfer.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/dist/NativeDragSources/getDataFromDataTransfer'>;
}
declare module 'react-dnd-html5-backend/dist/NativeDragSources/index' {
  declare module.exports: $Exports<'react-dnd-html5-backend/dist/NativeDragSources'>;
}
declare module 'react-dnd-html5-backend/dist/NativeDragSources/index.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/dist/NativeDragSources'>;
}
declare module 'react-dnd-html5-backend/dist/NativeDragSources/NativeDragSource.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/dist/NativeDragSources/NativeDragSource'>;
}
declare module 'react-dnd-html5-backend/dist/NativeDragSources/nativeTypesConfig.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/dist/NativeDragSources/nativeTypesConfig'>;
}
declare module 'react-dnd-html5-backend/dist/NativeTypes.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/dist/NativeTypes'>;
}
declare module 'react-dnd-html5-backend/dist/OffsetUtils.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/dist/OffsetUtils'>;
}
declare module 'react-dnd-html5-backend/dist/OptionsReader.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/dist/OptionsReader'>;
}
declare module 'react-dnd-html5-backend/dist/types.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/dist/types'>;
}
declare module 'react-dnd-html5-backend/dist/utils/js_utils.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/dist/utils/js_utils'>;
}
