// flow-typed signature: 2e096cbe37ad2101ebae5e9a0beafb20
// flow-typed version: <<STUB>>/react-datepicker_v^4.7.0/flow_v0.176.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-datepicker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-datepicker' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-datepicker/dist/es' {
  declare module.exports: any;
}

declare module 'react-datepicker/dist' {
  declare module.exports: any;
}

declare module 'react-datepicker/dist/react-datepicker' {
  declare module.exports: any;
}

declare module 'react-datepicker/dist/react-datepicker.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-datepicker/dist/es/index' {
  declare module.exports: $Exports<'react-datepicker/dist/es'>;
}
declare module 'react-datepicker/dist/es/index.js' {
  declare module.exports: $Exports<'react-datepicker/dist/es'>;
}
declare module 'react-datepicker/dist/index' {
  declare module.exports: $Exports<'react-datepicker/dist'>;
}
declare module 'react-datepicker/dist/index.js' {
  declare module.exports: $Exports<'react-datepicker/dist'>;
}
declare module 'react-datepicker/dist/react-datepicker.js' {
  declare module.exports: $Exports<'react-datepicker/dist/react-datepicker'>;
}
declare module 'react-datepicker/dist/react-datepicker.min.js' {
  declare module.exports: $Exports<'react-datepicker/dist/react-datepicker.min'>;
}
