// flow-typed signature: 8c382ad54560a809edad8995daab27d7
// flow-typed version: <<STUB>>/react-dnd_v^14.0.5/flow_v0.170.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-dnd'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-dnd' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-dnd/dist/cjs/core/DndContext' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/core/DndProvider' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/core/DragPreviewImage' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/core' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/decorators/createSourceFactory' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/decorators/createTargetFactory' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/decorators/decorateHandler' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/decorators/disposables' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/decorators/DragLayer' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/decorators/DragSource' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/decorators/DropTarget' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/decorators' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/decorators/types' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/decorators/utils' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/hooks' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/hooks/types' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/hooks/useCollectedProps' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/hooks/useCollector' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/hooks/useDrag/connectors' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/hooks/useDrag/DragSourceImpl' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/hooks/useDrag' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/hooks/useDrag/useDrag' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/hooks/useDrag/useDragSource' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/hooks/useDrag/useDragSourceConnector' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/hooks/useDrag/useDragSourceMonitor' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/hooks/useDrag/useDragType' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/hooks/useDrag/useRegisteredDragSource' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/hooks/useDragDropManager' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/hooks/useDragLayer' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/hooks/useDrop/connectors' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/hooks/useDrop/DropTargetImpl' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/hooks/useDrop' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/hooks/useDrop/useAccept' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/hooks/useDrop/useDrop' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/hooks/useDrop/useDropTarget' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/hooks/useDrop/useDropTargetConnector' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/hooks/useDrop/useDropTargetMonitor' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/hooks/useDrop/useRegisteredDropTarget' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/hooks/useIsomorphicLayoutEffect' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/hooks/useMonitorOutput' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/hooks/useOptionalFactory' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/internals/DragSourceMonitorImpl' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/internals/DropTargetMonitorImpl' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/internals' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/internals/isRef' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/internals/registration' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/internals/SourceConnector' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/internals/TargetConnector' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/internals/wrapConnectorHooks' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/types/connectors' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/types' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/types/monitors' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/types/options' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/core/DndContext' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/core/DndProvider' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/core/DragPreviewImage' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/core' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/decorators/createSourceFactory' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/decorators/createTargetFactory' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/decorators/decorateHandler' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/decorators/disposables' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/decorators/DragLayer' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/decorators/DragSource' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/decorators/DropTarget' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/decorators' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/decorators/types' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/decorators/utils' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/hooks' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/hooks/types' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/hooks/useCollectedProps' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/hooks/useCollector' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/hooks/useDrag/connectors' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/hooks/useDrag/DragSourceImpl' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/hooks/useDrag' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/hooks/useDrag/useDrag' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/hooks/useDrag/useDragSource' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/hooks/useDrag/useDragSourceConnector' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/hooks/useDrag/useDragSourceMonitor' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/hooks/useDrag/useDragType' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/hooks/useDrag/useRegisteredDragSource' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/hooks/useDragDropManager' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/hooks/useDragLayer' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/hooks/useDrop/connectors' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/hooks/useDrop/DropTargetImpl' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/hooks/useDrop' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/hooks/useDrop/useAccept' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/hooks/useDrop/useDrop' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/hooks/useDrop/useDropTarget' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/hooks/useDrop/useDropTargetConnector' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/hooks/useDrop/useDropTargetMonitor' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/hooks/useDrop/useRegisteredDropTarget' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/hooks/useIsomorphicLayoutEffect' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/hooks/useMonitorOutput' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/hooks/useOptionalFactory' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/internals/DragSourceMonitorImpl' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/internals/DropTargetMonitorImpl' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/internals' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/internals/isRef' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/internals/registration' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/internals/SourceConnector' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/internals/TargetConnector' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/internals/wrapConnectorHooks' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/types/connectors' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/types' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/types/monitors' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/types/options' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/umd/ReactDnD' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/umd/ReactDnD.min' {
  declare module.exports: any;
}

declare module 'react-dnd/gulpfile' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/core/DndContext' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/core/DndProvider' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/core/DragPreviewImage' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/core' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/decorators/createSourceFactory' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/decorators/createTargetFactory' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/decorators/decorateHandler' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/decorators/disposables' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/decorators/DragLayer' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/decorators/DragSource' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/decorators/DropTarget' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/decorators' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/decorators/types' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/decorators/utils' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/hooks' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/hooks/types' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/hooks/useCollectedProps' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/hooks/useCollector' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/hooks/useDrag/connectors' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/hooks/useDrag/DragSourceImpl' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/hooks/useDrag' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/hooks/useDrag/useDrag' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/hooks/useDrag/useDragSource' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/hooks/useDrag/useDragSourceConnector' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/hooks/useDrag/useDragSourceMonitor' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/hooks/useDrag/useDragType' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/hooks/useDrag/useRegisteredDragSource' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/hooks/useDragDropManager' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/hooks/useDragLayer' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/hooks/useDrop/connectors' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/hooks/useDrop/DropTargetImpl' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/hooks/useDrop' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/hooks/useDrop/useAccept' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/hooks/useDrop/useDrop' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/hooks/useDrop/useDropTarget' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/hooks/useDrop/useDropTargetConnector' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/hooks/useDrop/useDropTargetMonitor' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/hooks/useDrop/useRegisteredDropTarget' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/hooks/useIsomorphicLayoutEffect' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/hooks/useMonitorOutput' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/hooks/useOptionalFactory' {
  declare module.exports: any;
}

declare module 'react-dnd/lib' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/internals/DragSourceMonitorImpl' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/internals/DropTargetMonitorImpl' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/internals' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/internals/isRef' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/internals/registration' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/internals/SourceConnector' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/internals/TargetConnector' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/internals/wrapConnectorHooks' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/types/connectors' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/types' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/types/monitors' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/types/options' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-dnd/dist/cjs/core/DndContext.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/core/DndContext'>;
}
declare module 'react-dnd/dist/cjs/core/DndProvider.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/core/DndProvider'>;
}
declare module 'react-dnd/dist/cjs/core/DragPreviewImage.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/core/DragPreviewImage'>;
}
declare module 'react-dnd/dist/cjs/core/index' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/core'>;
}
declare module 'react-dnd/dist/cjs/core/index.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/core'>;
}
declare module 'react-dnd/dist/cjs/decorators/createSourceFactory.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/decorators/createSourceFactory'>;
}
declare module 'react-dnd/dist/cjs/decorators/createTargetFactory.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/decorators/createTargetFactory'>;
}
declare module 'react-dnd/dist/cjs/decorators/decorateHandler.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/decorators/decorateHandler'>;
}
declare module 'react-dnd/dist/cjs/decorators/disposables.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/decorators/disposables'>;
}
declare module 'react-dnd/dist/cjs/decorators/DragLayer.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/decorators/DragLayer'>;
}
declare module 'react-dnd/dist/cjs/decorators/DragSource.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/decorators/DragSource'>;
}
declare module 'react-dnd/dist/cjs/decorators/DropTarget.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/decorators/DropTarget'>;
}
declare module 'react-dnd/dist/cjs/decorators/index' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/decorators'>;
}
declare module 'react-dnd/dist/cjs/decorators/index.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/decorators'>;
}
declare module 'react-dnd/dist/cjs/decorators/types.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/decorators/types'>;
}
declare module 'react-dnd/dist/cjs/decorators/utils.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/decorators/utils'>;
}
declare module 'react-dnd/dist/cjs/hooks/index' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/hooks'>;
}
declare module 'react-dnd/dist/cjs/hooks/index.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/hooks'>;
}
declare module 'react-dnd/dist/cjs/hooks/types.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/hooks/types'>;
}
declare module 'react-dnd/dist/cjs/hooks/useCollectedProps.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/hooks/useCollectedProps'>;
}
declare module 'react-dnd/dist/cjs/hooks/useCollector.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/hooks/useCollector'>;
}
declare module 'react-dnd/dist/cjs/hooks/useDrag/connectors.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/hooks/useDrag/connectors'>;
}
declare module 'react-dnd/dist/cjs/hooks/useDrag/DragSourceImpl.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/hooks/useDrag/DragSourceImpl'>;
}
declare module 'react-dnd/dist/cjs/hooks/useDrag/index' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/hooks/useDrag'>;
}
declare module 'react-dnd/dist/cjs/hooks/useDrag/index.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/hooks/useDrag'>;
}
declare module 'react-dnd/dist/cjs/hooks/useDrag/useDrag.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/hooks/useDrag/useDrag'>;
}
declare module 'react-dnd/dist/cjs/hooks/useDrag/useDragSource.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/hooks/useDrag/useDragSource'>;
}
declare module 'react-dnd/dist/cjs/hooks/useDrag/useDragSourceConnector.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/hooks/useDrag/useDragSourceConnector'>;
}
declare module 'react-dnd/dist/cjs/hooks/useDrag/useDragSourceMonitor.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/hooks/useDrag/useDragSourceMonitor'>;
}
declare module 'react-dnd/dist/cjs/hooks/useDrag/useDragType.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/hooks/useDrag/useDragType'>;
}
declare module 'react-dnd/dist/cjs/hooks/useDrag/useRegisteredDragSource.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/hooks/useDrag/useRegisteredDragSource'>;
}
declare module 'react-dnd/dist/cjs/hooks/useDragDropManager.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/hooks/useDragDropManager'>;
}
declare module 'react-dnd/dist/cjs/hooks/useDragLayer.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/hooks/useDragLayer'>;
}
declare module 'react-dnd/dist/cjs/hooks/useDrop/connectors.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/hooks/useDrop/connectors'>;
}
declare module 'react-dnd/dist/cjs/hooks/useDrop/DropTargetImpl.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/hooks/useDrop/DropTargetImpl'>;
}
declare module 'react-dnd/dist/cjs/hooks/useDrop/index' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/hooks/useDrop'>;
}
declare module 'react-dnd/dist/cjs/hooks/useDrop/index.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/hooks/useDrop'>;
}
declare module 'react-dnd/dist/cjs/hooks/useDrop/useAccept.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/hooks/useDrop/useAccept'>;
}
declare module 'react-dnd/dist/cjs/hooks/useDrop/useDrop.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/hooks/useDrop/useDrop'>;
}
declare module 'react-dnd/dist/cjs/hooks/useDrop/useDropTarget.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/hooks/useDrop/useDropTarget'>;
}
declare module 'react-dnd/dist/cjs/hooks/useDrop/useDropTargetConnector.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/hooks/useDrop/useDropTargetConnector'>;
}
declare module 'react-dnd/dist/cjs/hooks/useDrop/useDropTargetMonitor.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/hooks/useDrop/useDropTargetMonitor'>;
}
declare module 'react-dnd/dist/cjs/hooks/useDrop/useRegisteredDropTarget.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/hooks/useDrop/useRegisteredDropTarget'>;
}
declare module 'react-dnd/dist/cjs/hooks/useIsomorphicLayoutEffect.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/hooks/useIsomorphicLayoutEffect'>;
}
declare module 'react-dnd/dist/cjs/hooks/useMonitorOutput.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/hooks/useMonitorOutput'>;
}
declare module 'react-dnd/dist/cjs/hooks/useOptionalFactory.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/hooks/useOptionalFactory'>;
}
declare module 'react-dnd/dist/cjs/index' {
  declare module.exports: $Exports<'react-dnd/dist/cjs'>;
}
declare module 'react-dnd/dist/cjs/index.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs'>;
}
declare module 'react-dnd/dist/cjs/internals/DragSourceMonitorImpl.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/internals/DragSourceMonitorImpl'>;
}
declare module 'react-dnd/dist/cjs/internals/DropTargetMonitorImpl.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/internals/DropTargetMonitorImpl'>;
}
declare module 'react-dnd/dist/cjs/internals/index' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/internals'>;
}
declare module 'react-dnd/dist/cjs/internals/index.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/internals'>;
}
declare module 'react-dnd/dist/cjs/internals/isRef.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/internals/isRef'>;
}
declare module 'react-dnd/dist/cjs/internals/registration.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/internals/registration'>;
}
declare module 'react-dnd/dist/cjs/internals/SourceConnector.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/internals/SourceConnector'>;
}
declare module 'react-dnd/dist/cjs/internals/TargetConnector.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/internals/TargetConnector'>;
}
declare module 'react-dnd/dist/cjs/internals/wrapConnectorHooks.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/internals/wrapConnectorHooks'>;
}
declare module 'react-dnd/dist/cjs/types/connectors.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/types/connectors'>;
}
declare module 'react-dnd/dist/cjs/types/index' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/types'>;
}
declare module 'react-dnd/dist/cjs/types/index.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/types'>;
}
declare module 'react-dnd/dist/cjs/types/monitors.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/types/monitors'>;
}
declare module 'react-dnd/dist/cjs/types/options.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/types/options'>;
}
declare module 'react-dnd/dist/esm/core/DndContext.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/core/DndContext'>;
}
declare module 'react-dnd/dist/esm/core/DndProvider.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/core/DndProvider'>;
}
declare module 'react-dnd/dist/esm/core/DragPreviewImage.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/core/DragPreviewImage'>;
}
declare module 'react-dnd/dist/esm/core/index' {
  declare module.exports: $Exports<'react-dnd/dist/esm/core'>;
}
declare module 'react-dnd/dist/esm/core/index.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/core'>;
}
declare module 'react-dnd/dist/esm/decorators/createSourceFactory.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/decorators/createSourceFactory'>;
}
declare module 'react-dnd/dist/esm/decorators/createTargetFactory.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/decorators/createTargetFactory'>;
}
declare module 'react-dnd/dist/esm/decorators/decorateHandler.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/decorators/decorateHandler'>;
}
declare module 'react-dnd/dist/esm/decorators/disposables.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/decorators/disposables'>;
}
declare module 'react-dnd/dist/esm/decorators/DragLayer.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/decorators/DragLayer'>;
}
declare module 'react-dnd/dist/esm/decorators/DragSource.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/decorators/DragSource'>;
}
declare module 'react-dnd/dist/esm/decorators/DropTarget.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/decorators/DropTarget'>;
}
declare module 'react-dnd/dist/esm/decorators/index' {
  declare module.exports: $Exports<'react-dnd/dist/esm/decorators'>;
}
declare module 'react-dnd/dist/esm/decorators/index.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/decorators'>;
}
declare module 'react-dnd/dist/esm/decorators/types.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/decorators/types'>;
}
declare module 'react-dnd/dist/esm/decorators/utils.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/decorators/utils'>;
}
declare module 'react-dnd/dist/esm/hooks/index' {
  declare module.exports: $Exports<'react-dnd/dist/esm/hooks'>;
}
declare module 'react-dnd/dist/esm/hooks/index.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/hooks'>;
}
declare module 'react-dnd/dist/esm/hooks/types.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/hooks/types'>;
}
declare module 'react-dnd/dist/esm/hooks/useCollectedProps.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/hooks/useCollectedProps'>;
}
declare module 'react-dnd/dist/esm/hooks/useCollector.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/hooks/useCollector'>;
}
declare module 'react-dnd/dist/esm/hooks/useDrag/connectors.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/hooks/useDrag/connectors'>;
}
declare module 'react-dnd/dist/esm/hooks/useDrag/DragSourceImpl.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/hooks/useDrag/DragSourceImpl'>;
}
declare module 'react-dnd/dist/esm/hooks/useDrag/index' {
  declare module.exports: $Exports<'react-dnd/dist/esm/hooks/useDrag'>;
}
declare module 'react-dnd/dist/esm/hooks/useDrag/index.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/hooks/useDrag'>;
}
declare module 'react-dnd/dist/esm/hooks/useDrag/useDrag.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/hooks/useDrag/useDrag'>;
}
declare module 'react-dnd/dist/esm/hooks/useDrag/useDragSource.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/hooks/useDrag/useDragSource'>;
}
declare module 'react-dnd/dist/esm/hooks/useDrag/useDragSourceConnector.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/hooks/useDrag/useDragSourceConnector'>;
}
declare module 'react-dnd/dist/esm/hooks/useDrag/useDragSourceMonitor.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/hooks/useDrag/useDragSourceMonitor'>;
}
declare module 'react-dnd/dist/esm/hooks/useDrag/useDragType.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/hooks/useDrag/useDragType'>;
}
declare module 'react-dnd/dist/esm/hooks/useDrag/useRegisteredDragSource.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/hooks/useDrag/useRegisteredDragSource'>;
}
declare module 'react-dnd/dist/esm/hooks/useDragDropManager.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/hooks/useDragDropManager'>;
}
declare module 'react-dnd/dist/esm/hooks/useDragLayer.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/hooks/useDragLayer'>;
}
declare module 'react-dnd/dist/esm/hooks/useDrop/connectors.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/hooks/useDrop/connectors'>;
}
declare module 'react-dnd/dist/esm/hooks/useDrop/DropTargetImpl.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/hooks/useDrop/DropTargetImpl'>;
}
declare module 'react-dnd/dist/esm/hooks/useDrop/index' {
  declare module.exports: $Exports<'react-dnd/dist/esm/hooks/useDrop'>;
}
declare module 'react-dnd/dist/esm/hooks/useDrop/index.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/hooks/useDrop'>;
}
declare module 'react-dnd/dist/esm/hooks/useDrop/useAccept.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/hooks/useDrop/useAccept'>;
}
declare module 'react-dnd/dist/esm/hooks/useDrop/useDrop.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/hooks/useDrop/useDrop'>;
}
declare module 'react-dnd/dist/esm/hooks/useDrop/useDropTarget.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/hooks/useDrop/useDropTarget'>;
}
declare module 'react-dnd/dist/esm/hooks/useDrop/useDropTargetConnector.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/hooks/useDrop/useDropTargetConnector'>;
}
declare module 'react-dnd/dist/esm/hooks/useDrop/useDropTargetMonitor.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/hooks/useDrop/useDropTargetMonitor'>;
}
declare module 'react-dnd/dist/esm/hooks/useDrop/useRegisteredDropTarget.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/hooks/useDrop/useRegisteredDropTarget'>;
}
declare module 'react-dnd/dist/esm/hooks/useIsomorphicLayoutEffect.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/hooks/useIsomorphicLayoutEffect'>;
}
declare module 'react-dnd/dist/esm/hooks/useMonitorOutput.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/hooks/useMonitorOutput'>;
}
declare module 'react-dnd/dist/esm/hooks/useOptionalFactory.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/hooks/useOptionalFactory'>;
}
declare module 'react-dnd/dist/esm/index' {
  declare module.exports: $Exports<'react-dnd/dist/esm'>;
}
declare module 'react-dnd/dist/esm/index.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm'>;
}
declare module 'react-dnd/dist/esm/internals/DragSourceMonitorImpl.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/internals/DragSourceMonitorImpl'>;
}
declare module 'react-dnd/dist/esm/internals/DropTargetMonitorImpl.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/internals/DropTargetMonitorImpl'>;
}
declare module 'react-dnd/dist/esm/internals/index' {
  declare module.exports: $Exports<'react-dnd/dist/esm/internals'>;
}
declare module 'react-dnd/dist/esm/internals/index.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/internals'>;
}
declare module 'react-dnd/dist/esm/internals/isRef.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/internals/isRef'>;
}
declare module 'react-dnd/dist/esm/internals/registration.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/internals/registration'>;
}
declare module 'react-dnd/dist/esm/internals/SourceConnector.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/internals/SourceConnector'>;
}
declare module 'react-dnd/dist/esm/internals/TargetConnector.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/internals/TargetConnector'>;
}
declare module 'react-dnd/dist/esm/internals/wrapConnectorHooks.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/internals/wrapConnectorHooks'>;
}
declare module 'react-dnd/dist/esm/types/connectors.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/types/connectors'>;
}
declare module 'react-dnd/dist/esm/types/index' {
  declare module.exports: $Exports<'react-dnd/dist/esm/types'>;
}
declare module 'react-dnd/dist/esm/types/index.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/types'>;
}
declare module 'react-dnd/dist/esm/types/monitors.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/types/monitors'>;
}
declare module 'react-dnd/dist/esm/types/options.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/types/options'>;
}
declare module 'react-dnd/dist/umd/ReactDnD.js' {
  declare module.exports: $Exports<'react-dnd/dist/umd/ReactDnD'>;
}
declare module 'react-dnd/dist/umd/ReactDnD.min.js' {
  declare module.exports: $Exports<'react-dnd/dist/umd/ReactDnD.min'>;
}
declare module 'react-dnd/gulpfile.js' {
  declare module.exports: $Exports<'react-dnd/gulpfile'>;
}
declare module 'react-dnd/lib/core/DndContext.js' {
  declare module.exports: $Exports<'react-dnd/lib/core/DndContext'>;
}
declare module 'react-dnd/lib/core/DndProvider.js' {
  declare module.exports: $Exports<'react-dnd/lib/core/DndProvider'>;
}
declare module 'react-dnd/lib/core/DragPreviewImage.js' {
  declare module.exports: $Exports<'react-dnd/lib/core/DragPreviewImage'>;
}
declare module 'react-dnd/lib/core/index' {
  declare module.exports: $Exports<'react-dnd/lib/core'>;
}
declare module 'react-dnd/lib/core/index.js' {
  declare module.exports: $Exports<'react-dnd/lib/core'>;
}
declare module 'react-dnd/lib/decorators/createSourceFactory.js' {
  declare module.exports: $Exports<'react-dnd/lib/decorators/createSourceFactory'>;
}
declare module 'react-dnd/lib/decorators/createTargetFactory.js' {
  declare module.exports: $Exports<'react-dnd/lib/decorators/createTargetFactory'>;
}
declare module 'react-dnd/lib/decorators/decorateHandler.js' {
  declare module.exports: $Exports<'react-dnd/lib/decorators/decorateHandler'>;
}
declare module 'react-dnd/lib/decorators/disposables.js' {
  declare module.exports: $Exports<'react-dnd/lib/decorators/disposables'>;
}
declare module 'react-dnd/lib/decorators/DragLayer.js' {
  declare module.exports: $Exports<'react-dnd/lib/decorators/DragLayer'>;
}
declare module 'react-dnd/lib/decorators/DragSource.js' {
  declare module.exports: $Exports<'react-dnd/lib/decorators/DragSource'>;
}
declare module 'react-dnd/lib/decorators/DropTarget.js' {
  declare module.exports: $Exports<'react-dnd/lib/decorators/DropTarget'>;
}
declare module 'react-dnd/lib/decorators/index' {
  declare module.exports: $Exports<'react-dnd/lib/decorators'>;
}
declare module 'react-dnd/lib/decorators/index.js' {
  declare module.exports: $Exports<'react-dnd/lib/decorators'>;
}
declare module 'react-dnd/lib/decorators/types.js' {
  declare module.exports: $Exports<'react-dnd/lib/decorators/types'>;
}
declare module 'react-dnd/lib/decorators/utils.js' {
  declare module.exports: $Exports<'react-dnd/lib/decorators/utils'>;
}
declare module 'react-dnd/lib/hooks/index' {
  declare module.exports: $Exports<'react-dnd/lib/hooks'>;
}
declare module 'react-dnd/lib/hooks/index.js' {
  declare module.exports: $Exports<'react-dnd/lib/hooks'>;
}
declare module 'react-dnd/lib/hooks/types.js' {
  declare module.exports: $Exports<'react-dnd/lib/hooks/types'>;
}
declare module 'react-dnd/lib/hooks/useCollectedProps.js' {
  declare module.exports: $Exports<'react-dnd/lib/hooks/useCollectedProps'>;
}
declare module 'react-dnd/lib/hooks/useCollector.js' {
  declare module.exports: $Exports<'react-dnd/lib/hooks/useCollector'>;
}
declare module 'react-dnd/lib/hooks/useDrag/connectors.js' {
  declare module.exports: $Exports<'react-dnd/lib/hooks/useDrag/connectors'>;
}
declare module 'react-dnd/lib/hooks/useDrag/DragSourceImpl.js' {
  declare module.exports: $Exports<'react-dnd/lib/hooks/useDrag/DragSourceImpl'>;
}
declare module 'react-dnd/lib/hooks/useDrag/index' {
  declare module.exports: $Exports<'react-dnd/lib/hooks/useDrag'>;
}
declare module 'react-dnd/lib/hooks/useDrag/index.js' {
  declare module.exports: $Exports<'react-dnd/lib/hooks/useDrag'>;
}
declare module 'react-dnd/lib/hooks/useDrag/useDrag.js' {
  declare module.exports: $Exports<'react-dnd/lib/hooks/useDrag/useDrag'>;
}
declare module 'react-dnd/lib/hooks/useDrag/useDragSource.js' {
  declare module.exports: $Exports<'react-dnd/lib/hooks/useDrag/useDragSource'>;
}
declare module 'react-dnd/lib/hooks/useDrag/useDragSourceConnector.js' {
  declare module.exports: $Exports<'react-dnd/lib/hooks/useDrag/useDragSourceConnector'>;
}
declare module 'react-dnd/lib/hooks/useDrag/useDragSourceMonitor.js' {
  declare module.exports: $Exports<'react-dnd/lib/hooks/useDrag/useDragSourceMonitor'>;
}
declare module 'react-dnd/lib/hooks/useDrag/useDragType.js' {
  declare module.exports: $Exports<'react-dnd/lib/hooks/useDrag/useDragType'>;
}
declare module 'react-dnd/lib/hooks/useDrag/useRegisteredDragSource.js' {
  declare module.exports: $Exports<'react-dnd/lib/hooks/useDrag/useRegisteredDragSource'>;
}
declare module 'react-dnd/lib/hooks/useDragDropManager.js' {
  declare module.exports: $Exports<'react-dnd/lib/hooks/useDragDropManager'>;
}
declare module 'react-dnd/lib/hooks/useDragLayer.js' {
  declare module.exports: $Exports<'react-dnd/lib/hooks/useDragLayer'>;
}
declare module 'react-dnd/lib/hooks/useDrop/connectors.js' {
  declare module.exports: $Exports<'react-dnd/lib/hooks/useDrop/connectors'>;
}
declare module 'react-dnd/lib/hooks/useDrop/DropTargetImpl.js' {
  declare module.exports: $Exports<'react-dnd/lib/hooks/useDrop/DropTargetImpl'>;
}
declare module 'react-dnd/lib/hooks/useDrop/index' {
  declare module.exports: $Exports<'react-dnd/lib/hooks/useDrop'>;
}
declare module 'react-dnd/lib/hooks/useDrop/index.js' {
  declare module.exports: $Exports<'react-dnd/lib/hooks/useDrop'>;
}
declare module 'react-dnd/lib/hooks/useDrop/useAccept.js' {
  declare module.exports: $Exports<'react-dnd/lib/hooks/useDrop/useAccept'>;
}
declare module 'react-dnd/lib/hooks/useDrop/useDrop.js' {
  declare module.exports: $Exports<'react-dnd/lib/hooks/useDrop/useDrop'>;
}
declare module 'react-dnd/lib/hooks/useDrop/useDropTarget.js' {
  declare module.exports: $Exports<'react-dnd/lib/hooks/useDrop/useDropTarget'>;
}
declare module 'react-dnd/lib/hooks/useDrop/useDropTargetConnector.js' {
  declare module.exports: $Exports<'react-dnd/lib/hooks/useDrop/useDropTargetConnector'>;
}
declare module 'react-dnd/lib/hooks/useDrop/useDropTargetMonitor.js' {
  declare module.exports: $Exports<'react-dnd/lib/hooks/useDrop/useDropTargetMonitor'>;
}
declare module 'react-dnd/lib/hooks/useDrop/useRegisteredDropTarget.js' {
  declare module.exports: $Exports<'react-dnd/lib/hooks/useDrop/useRegisteredDropTarget'>;
}
declare module 'react-dnd/lib/hooks/useIsomorphicLayoutEffect.js' {
  declare module.exports: $Exports<'react-dnd/lib/hooks/useIsomorphicLayoutEffect'>;
}
declare module 'react-dnd/lib/hooks/useMonitorOutput.js' {
  declare module.exports: $Exports<'react-dnd/lib/hooks/useMonitorOutput'>;
}
declare module 'react-dnd/lib/hooks/useOptionalFactory.js' {
  declare module.exports: $Exports<'react-dnd/lib/hooks/useOptionalFactory'>;
}
declare module 'react-dnd/lib/index' {
  declare module.exports: $Exports<'react-dnd/lib'>;
}
declare module 'react-dnd/lib/index.js' {
  declare module.exports: $Exports<'react-dnd/lib'>;
}
declare module 'react-dnd/lib/internals/DragSourceMonitorImpl.js' {
  declare module.exports: $Exports<'react-dnd/lib/internals/DragSourceMonitorImpl'>;
}
declare module 'react-dnd/lib/internals/DropTargetMonitorImpl.js' {
  declare module.exports: $Exports<'react-dnd/lib/internals/DropTargetMonitorImpl'>;
}
declare module 'react-dnd/lib/internals/index' {
  declare module.exports: $Exports<'react-dnd/lib/internals'>;
}
declare module 'react-dnd/lib/internals/index.js' {
  declare module.exports: $Exports<'react-dnd/lib/internals'>;
}
declare module 'react-dnd/lib/internals/isRef.js' {
  declare module.exports: $Exports<'react-dnd/lib/internals/isRef'>;
}
declare module 'react-dnd/lib/internals/registration.js' {
  declare module.exports: $Exports<'react-dnd/lib/internals/registration'>;
}
declare module 'react-dnd/lib/internals/SourceConnector.js' {
  declare module.exports: $Exports<'react-dnd/lib/internals/SourceConnector'>;
}
declare module 'react-dnd/lib/internals/TargetConnector.js' {
  declare module.exports: $Exports<'react-dnd/lib/internals/TargetConnector'>;
}
declare module 'react-dnd/lib/internals/wrapConnectorHooks.js' {
  declare module.exports: $Exports<'react-dnd/lib/internals/wrapConnectorHooks'>;
}
declare module 'react-dnd/lib/types/connectors.js' {
  declare module.exports: $Exports<'react-dnd/lib/types/connectors'>;
}
declare module 'react-dnd/lib/types/index' {
  declare module.exports: $Exports<'react-dnd/lib/types'>;
}
declare module 'react-dnd/lib/types/index.js' {
  declare module.exports: $Exports<'react-dnd/lib/types'>;
}
declare module 'react-dnd/lib/types/monitors.js' {
  declare module.exports: $Exports<'react-dnd/lib/types/monitors'>;
}
declare module 'react-dnd/lib/types/options.js' {
  declare module.exports: $Exports<'react-dnd/lib/types/options'>;
}
