// flow-typed signature: ca26684f690bb8e39458f83bbf868a15
// flow-typed version: <<STUB>>/react-dnd_v^16.0.1/flow_v0.176.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-dnd'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-dnd' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-dnd/dist/core/DndContext' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/core/DndProvider' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/core/DragPreviewImage' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/core' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/hooks' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/hooks/types' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/hooks/useCollectedProps' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/hooks/useCollector' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/hooks/useDrag/connectors' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/hooks/useDrag/DragSourceImpl' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/hooks/useDrag' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/hooks/useDrag/useDrag' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/hooks/useDrag/useDragSource' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/hooks/useDrag/useDragSourceConnector' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/hooks/useDrag/useDragSourceMonitor' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/hooks/useDrag/useDragType' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/hooks/useDrag/useRegisteredDragSource' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/hooks/useDragDropManager' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/hooks/useDragLayer' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/hooks/useDrop/connectors' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/hooks/useDrop/DropTargetImpl' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/hooks/useDrop' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/hooks/useDrop/useAccept' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/hooks/useDrop/useDrop' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/hooks/useDrop/useDropTarget' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/hooks/useDrop/useDropTargetConnector' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/hooks/useDrop/useDropTargetMonitor' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/hooks/useDrop/useRegisteredDropTarget' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/hooks/useIsomorphicLayoutEffect' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/hooks/useMonitorOutput' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/hooks/useOptionalFactory' {
  declare module.exports: any;
}

declare module 'react-dnd/dist' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/internals/DragSourceMonitorImpl' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/internals/DropTargetMonitorImpl' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/internals' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/internals/isRef' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/internals/registration' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/internals/SourceConnector' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/internals/TargetConnector' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/internals/wrapConnectorHooks' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/types/connectors' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/types' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/types/monitors' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/types/options' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-dnd/dist/core/DndContext.js' {
  declare module.exports: $Exports<'react-dnd/dist/core/DndContext'>;
}
declare module 'react-dnd/dist/core/DndProvider.js' {
  declare module.exports: $Exports<'react-dnd/dist/core/DndProvider'>;
}
declare module 'react-dnd/dist/core/DragPreviewImage.js' {
  declare module.exports: $Exports<'react-dnd/dist/core/DragPreviewImage'>;
}
declare module 'react-dnd/dist/core/index' {
  declare module.exports: $Exports<'react-dnd/dist/core'>;
}
declare module 'react-dnd/dist/core/index.js' {
  declare module.exports: $Exports<'react-dnd/dist/core'>;
}
declare module 'react-dnd/dist/hooks/index' {
  declare module.exports: $Exports<'react-dnd/dist/hooks'>;
}
declare module 'react-dnd/dist/hooks/index.js' {
  declare module.exports: $Exports<'react-dnd/dist/hooks'>;
}
declare module 'react-dnd/dist/hooks/types.js' {
  declare module.exports: $Exports<'react-dnd/dist/hooks/types'>;
}
declare module 'react-dnd/dist/hooks/useCollectedProps.js' {
  declare module.exports: $Exports<'react-dnd/dist/hooks/useCollectedProps'>;
}
declare module 'react-dnd/dist/hooks/useCollector.js' {
  declare module.exports: $Exports<'react-dnd/dist/hooks/useCollector'>;
}
declare module 'react-dnd/dist/hooks/useDrag/connectors.js' {
  declare module.exports: $Exports<'react-dnd/dist/hooks/useDrag/connectors'>;
}
declare module 'react-dnd/dist/hooks/useDrag/DragSourceImpl.js' {
  declare module.exports: $Exports<'react-dnd/dist/hooks/useDrag/DragSourceImpl'>;
}
declare module 'react-dnd/dist/hooks/useDrag/index' {
  declare module.exports: $Exports<'react-dnd/dist/hooks/useDrag'>;
}
declare module 'react-dnd/dist/hooks/useDrag/index.js' {
  declare module.exports: $Exports<'react-dnd/dist/hooks/useDrag'>;
}
declare module 'react-dnd/dist/hooks/useDrag/useDrag.js' {
  declare module.exports: $Exports<'react-dnd/dist/hooks/useDrag/useDrag'>;
}
declare module 'react-dnd/dist/hooks/useDrag/useDragSource.js' {
  declare module.exports: $Exports<'react-dnd/dist/hooks/useDrag/useDragSource'>;
}
declare module 'react-dnd/dist/hooks/useDrag/useDragSourceConnector.js' {
  declare module.exports: $Exports<'react-dnd/dist/hooks/useDrag/useDragSourceConnector'>;
}
declare module 'react-dnd/dist/hooks/useDrag/useDragSourceMonitor.js' {
  declare module.exports: $Exports<'react-dnd/dist/hooks/useDrag/useDragSourceMonitor'>;
}
declare module 'react-dnd/dist/hooks/useDrag/useDragType.js' {
  declare module.exports: $Exports<'react-dnd/dist/hooks/useDrag/useDragType'>;
}
declare module 'react-dnd/dist/hooks/useDrag/useRegisteredDragSource.js' {
  declare module.exports: $Exports<'react-dnd/dist/hooks/useDrag/useRegisteredDragSource'>;
}
declare module 'react-dnd/dist/hooks/useDragDropManager.js' {
  declare module.exports: $Exports<'react-dnd/dist/hooks/useDragDropManager'>;
}
declare module 'react-dnd/dist/hooks/useDragLayer.js' {
  declare module.exports: $Exports<'react-dnd/dist/hooks/useDragLayer'>;
}
declare module 'react-dnd/dist/hooks/useDrop/connectors.js' {
  declare module.exports: $Exports<'react-dnd/dist/hooks/useDrop/connectors'>;
}
declare module 'react-dnd/dist/hooks/useDrop/DropTargetImpl.js' {
  declare module.exports: $Exports<'react-dnd/dist/hooks/useDrop/DropTargetImpl'>;
}
declare module 'react-dnd/dist/hooks/useDrop/index' {
  declare module.exports: $Exports<'react-dnd/dist/hooks/useDrop'>;
}
declare module 'react-dnd/dist/hooks/useDrop/index.js' {
  declare module.exports: $Exports<'react-dnd/dist/hooks/useDrop'>;
}
declare module 'react-dnd/dist/hooks/useDrop/useAccept.js' {
  declare module.exports: $Exports<'react-dnd/dist/hooks/useDrop/useAccept'>;
}
declare module 'react-dnd/dist/hooks/useDrop/useDrop.js' {
  declare module.exports: $Exports<'react-dnd/dist/hooks/useDrop/useDrop'>;
}
declare module 'react-dnd/dist/hooks/useDrop/useDropTarget.js' {
  declare module.exports: $Exports<'react-dnd/dist/hooks/useDrop/useDropTarget'>;
}
declare module 'react-dnd/dist/hooks/useDrop/useDropTargetConnector.js' {
  declare module.exports: $Exports<'react-dnd/dist/hooks/useDrop/useDropTargetConnector'>;
}
declare module 'react-dnd/dist/hooks/useDrop/useDropTargetMonitor.js' {
  declare module.exports: $Exports<'react-dnd/dist/hooks/useDrop/useDropTargetMonitor'>;
}
declare module 'react-dnd/dist/hooks/useDrop/useRegisteredDropTarget.js' {
  declare module.exports: $Exports<'react-dnd/dist/hooks/useDrop/useRegisteredDropTarget'>;
}
declare module 'react-dnd/dist/hooks/useIsomorphicLayoutEffect.js' {
  declare module.exports: $Exports<'react-dnd/dist/hooks/useIsomorphicLayoutEffect'>;
}
declare module 'react-dnd/dist/hooks/useMonitorOutput.js' {
  declare module.exports: $Exports<'react-dnd/dist/hooks/useMonitorOutput'>;
}
declare module 'react-dnd/dist/hooks/useOptionalFactory.js' {
  declare module.exports: $Exports<'react-dnd/dist/hooks/useOptionalFactory'>;
}
declare module 'react-dnd/dist/index' {
  declare module.exports: $Exports<'react-dnd/dist'>;
}
declare module 'react-dnd/dist/index.js' {
  declare module.exports: $Exports<'react-dnd/dist'>;
}
declare module 'react-dnd/dist/internals/DragSourceMonitorImpl.js' {
  declare module.exports: $Exports<'react-dnd/dist/internals/DragSourceMonitorImpl'>;
}
declare module 'react-dnd/dist/internals/DropTargetMonitorImpl.js' {
  declare module.exports: $Exports<'react-dnd/dist/internals/DropTargetMonitorImpl'>;
}
declare module 'react-dnd/dist/internals/index' {
  declare module.exports: $Exports<'react-dnd/dist/internals'>;
}
declare module 'react-dnd/dist/internals/index.js' {
  declare module.exports: $Exports<'react-dnd/dist/internals'>;
}
declare module 'react-dnd/dist/internals/isRef.js' {
  declare module.exports: $Exports<'react-dnd/dist/internals/isRef'>;
}
declare module 'react-dnd/dist/internals/registration.js' {
  declare module.exports: $Exports<'react-dnd/dist/internals/registration'>;
}
declare module 'react-dnd/dist/internals/SourceConnector.js' {
  declare module.exports: $Exports<'react-dnd/dist/internals/SourceConnector'>;
}
declare module 'react-dnd/dist/internals/TargetConnector.js' {
  declare module.exports: $Exports<'react-dnd/dist/internals/TargetConnector'>;
}
declare module 'react-dnd/dist/internals/wrapConnectorHooks.js' {
  declare module.exports: $Exports<'react-dnd/dist/internals/wrapConnectorHooks'>;
}
declare module 'react-dnd/dist/types/connectors.js' {
  declare module.exports: $Exports<'react-dnd/dist/types/connectors'>;
}
declare module 'react-dnd/dist/types/index' {
  declare module.exports: $Exports<'react-dnd/dist/types'>;
}
declare module 'react-dnd/dist/types/index.js' {
  declare module.exports: $Exports<'react-dnd/dist/types'>;
}
declare module 'react-dnd/dist/types/monitors.js' {
  declare module.exports: $Exports<'react-dnd/dist/types/monitors'>;
}
declare module 'react-dnd/dist/types/options.js' {
  declare module.exports: $Exports<'react-dnd/dist/types/options'>;
}
