// flow-typed signature: 3ddb512309a1732e210e79b2fb4d0f68
// flow-typed version: <<STUB>>/react-redux_v^8.0.1/flow_v0.176.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-redux'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-redux' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-redux/dist/react-redux' {
  declare module.exports: any;
}

declare module 'react-redux/dist/react-redux.min' {
  declare module.exports: any;
}

declare module 'react-redux/es/alternate-renderers' {
  declare module.exports: any;
}

declare module 'react-redux/es/components/connect' {
  declare module.exports: any;
}

declare module 'react-redux/es/components/Context' {
  declare module.exports: any;
}

declare module 'react-redux/es/components/Provider' {
  declare module.exports: any;
}

declare module 'react-redux/es/connect/invalidArgFactory' {
  declare module.exports: any;
}

declare module 'react-redux/es/connect/mapDispatchToProps' {
  declare module.exports: any;
}

declare module 'react-redux/es/connect/mapStateToProps' {
  declare module.exports: any;
}

declare module 'react-redux/es/connect/mergeProps' {
  declare module.exports: any;
}

declare module 'react-redux/es/connect/selectorFactory' {
  declare module.exports: any;
}

declare module 'react-redux/es/connect/verifySubselectors' {
  declare module.exports: any;
}

declare module 'react-redux/es/connect/wrapMapToProps' {
  declare module.exports: any;
}

declare module 'react-redux/es/exports' {
  declare module.exports: any;
}

declare module 'react-redux/es/hooks/useDispatch' {
  declare module.exports: any;
}

declare module 'react-redux/es/hooks/useReduxContext' {
  declare module.exports: any;
}

declare module 'react-redux/es/hooks/useSelector' {
  declare module.exports: any;
}

declare module 'react-redux/es/hooks/useStore' {
  declare module.exports: any;
}

declare module 'react-redux/es' {
  declare module.exports: any;
}

declare module 'react-redux/es/next' {
  declare module.exports: any;
}

declare module 'react-redux/es/types' {
  declare module.exports: any;
}

declare module 'react-redux/es/utils/batch' {
  declare module.exports: any;
}

declare module 'react-redux/es/utils/bindActionCreators' {
  declare module.exports: any;
}

declare module 'react-redux/es/utils/isPlainObject' {
  declare module.exports: any;
}

declare module 'react-redux/es/utils/reactBatchedUpdates' {
  declare module.exports: any;
}

declare module 'react-redux/es/utils/reactBatchedUpdates.native' {
  declare module.exports: any;
}

declare module 'react-redux/es/utils/shallowEqual' {
  declare module.exports: any;
}

declare module 'react-redux/es/utils/Subscription' {
  declare module.exports: any;
}

declare module 'react-redux/es/utils/useIsomorphicLayoutEffect' {
  declare module.exports: any;
}

declare module 'react-redux/es/utils/useIsomorphicLayoutEffect.native' {
  declare module.exports: any;
}

declare module 'react-redux/es/utils/useSyncExternalStore' {
  declare module.exports: any;
}

declare module 'react-redux/es/utils/verifyPlainObject' {
  declare module.exports: any;
}

declare module 'react-redux/es/utils/warning' {
  declare module.exports: any;
}

declare module 'react-redux/lib/alternate-renderers' {
  declare module.exports: any;
}

declare module 'react-redux/lib/components/connect' {
  declare module.exports: any;
}

declare module 'react-redux/lib/components/Context' {
  declare module.exports: any;
}

declare module 'react-redux/lib/components/Provider' {
  declare module.exports: any;
}

declare module 'react-redux/lib/connect/invalidArgFactory' {
  declare module.exports: any;
}

declare module 'react-redux/lib/connect/mapDispatchToProps' {
  declare module.exports: any;
}

declare module 'react-redux/lib/connect/mapStateToProps' {
  declare module.exports: any;
}

declare module 'react-redux/lib/connect/mergeProps' {
  declare module.exports: any;
}

declare module 'react-redux/lib/connect/selectorFactory' {
  declare module.exports: any;
}

declare module 'react-redux/lib/connect/verifySubselectors' {
  declare module.exports: any;
}

declare module 'react-redux/lib/connect/wrapMapToProps' {
  declare module.exports: any;
}

declare module 'react-redux/lib/exports' {
  declare module.exports: any;
}

declare module 'react-redux/lib/hooks/useDispatch' {
  declare module.exports: any;
}

declare module 'react-redux/lib/hooks/useReduxContext' {
  declare module.exports: any;
}

declare module 'react-redux/lib/hooks/useSelector' {
  declare module.exports: any;
}

declare module 'react-redux/lib/hooks/useStore' {
  declare module.exports: any;
}

declare module 'react-redux/lib' {
  declare module.exports: any;
}

declare module 'react-redux/lib/next' {
  declare module.exports: any;
}

declare module 'react-redux/lib/types' {
  declare module.exports: any;
}

declare module 'react-redux/lib/utils/batch' {
  declare module.exports: any;
}

declare module 'react-redux/lib/utils/bindActionCreators' {
  declare module.exports: any;
}

declare module 'react-redux/lib/utils/isPlainObject' {
  declare module.exports: any;
}

declare module 'react-redux/lib/utils/reactBatchedUpdates' {
  declare module.exports: any;
}

declare module 'react-redux/lib/utils/reactBatchedUpdates.native' {
  declare module.exports: any;
}

declare module 'react-redux/lib/utils/shallowEqual' {
  declare module.exports: any;
}

declare module 'react-redux/lib/utils/Subscription' {
  declare module.exports: any;
}

declare module 'react-redux/lib/utils/useIsomorphicLayoutEffect' {
  declare module.exports: any;
}

declare module 'react-redux/lib/utils/useIsomorphicLayoutEffect.native' {
  declare module.exports: any;
}

declare module 'react-redux/lib/utils/useSyncExternalStore' {
  declare module.exports: any;
}

declare module 'react-redux/lib/utils/verifyPlainObject' {
  declare module.exports: any;
}

declare module 'react-redux/lib/utils/warning' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-redux/dist/react-redux.js' {
  declare module.exports: $Exports<'react-redux/dist/react-redux'>;
}
declare module 'react-redux/dist/react-redux.min.js' {
  declare module.exports: $Exports<'react-redux/dist/react-redux.min'>;
}
declare module 'react-redux/es/alternate-renderers.js' {
  declare module.exports: $Exports<'react-redux/es/alternate-renderers'>;
}
declare module 'react-redux/es/components/connect.js' {
  declare module.exports: $Exports<'react-redux/es/components/connect'>;
}
declare module 'react-redux/es/components/Context.js' {
  declare module.exports: $Exports<'react-redux/es/components/Context'>;
}
declare module 'react-redux/es/components/Provider.js' {
  declare module.exports: $Exports<'react-redux/es/components/Provider'>;
}
declare module 'react-redux/es/connect/invalidArgFactory.js' {
  declare module.exports: $Exports<'react-redux/es/connect/invalidArgFactory'>;
}
declare module 'react-redux/es/connect/mapDispatchToProps.js' {
  declare module.exports: $Exports<'react-redux/es/connect/mapDispatchToProps'>;
}
declare module 'react-redux/es/connect/mapStateToProps.js' {
  declare module.exports: $Exports<'react-redux/es/connect/mapStateToProps'>;
}
declare module 'react-redux/es/connect/mergeProps.js' {
  declare module.exports: $Exports<'react-redux/es/connect/mergeProps'>;
}
declare module 'react-redux/es/connect/selectorFactory.js' {
  declare module.exports: $Exports<'react-redux/es/connect/selectorFactory'>;
}
declare module 'react-redux/es/connect/verifySubselectors.js' {
  declare module.exports: $Exports<'react-redux/es/connect/verifySubselectors'>;
}
declare module 'react-redux/es/connect/wrapMapToProps.js' {
  declare module.exports: $Exports<'react-redux/es/connect/wrapMapToProps'>;
}
declare module 'react-redux/es/exports.js' {
  declare module.exports: $Exports<'react-redux/es/exports'>;
}
declare module 'react-redux/es/hooks/useDispatch.js' {
  declare module.exports: $Exports<'react-redux/es/hooks/useDispatch'>;
}
declare module 'react-redux/es/hooks/useReduxContext.js' {
  declare module.exports: $Exports<'react-redux/es/hooks/useReduxContext'>;
}
declare module 'react-redux/es/hooks/useSelector.js' {
  declare module.exports: $Exports<'react-redux/es/hooks/useSelector'>;
}
declare module 'react-redux/es/hooks/useStore.js' {
  declare module.exports: $Exports<'react-redux/es/hooks/useStore'>;
}
declare module 'react-redux/es/index' {
  declare module.exports: $Exports<'react-redux/es'>;
}
declare module 'react-redux/es/index.js' {
  declare module.exports: $Exports<'react-redux/es'>;
}
declare module 'react-redux/es/next.js' {
  declare module.exports: $Exports<'react-redux/es/next'>;
}
declare module 'react-redux/es/types.js' {
  declare module.exports: $Exports<'react-redux/es/types'>;
}
declare module 'react-redux/es/utils/batch.js' {
  declare module.exports: $Exports<'react-redux/es/utils/batch'>;
}
declare module 'react-redux/es/utils/bindActionCreators.js' {
  declare module.exports: $Exports<'react-redux/es/utils/bindActionCreators'>;
}
declare module 'react-redux/es/utils/isPlainObject.js' {
  declare module.exports: $Exports<'react-redux/es/utils/isPlainObject'>;
}
declare module 'react-redux/es/utils/reactBatchedUpdates.js' {
  declare module.exports: $Exports<'react-redux/es/utils/reactBatchedUpdates'>;
}
declare module 'react-redux/es/utils/reactBatchedUpdates.native.js' {
  declare module.exports: $Exports<'react-redux/es/utils/reactBatchedUpdates.native'>;
}
declare module 'react-redux/es/utils/shallowEqual.js' {
  declare module.exports: $Exports<'react-redux/es/utils/shallowEqual'>;
}
declare module 'react-redux/es/utils/Subscription.js' {
  declare module.exports: $Exports<'react-redux/es/utils/Subscription'>;
}
declare module 'react-redux/es/utils/useIsomorphicLayoutEffect.js' {
  declare module.exports: $Exports<'react-redux/es/utils/useIsomorphicLayoutEffect'>;
}
declare module 'react-redux/es/utils/useIsomorphicLayoutEffect.native.js' {
  declare module.exports: $Exports<'react-redux/es/utils/useIsomorphicLayoutEffect.native'>;
}
declare module 'react-redux/es/utils/useSyncExternalStore.js' {
  declare module.exports: $Exports<'react-redux/es/utils/useSyncExternalStore'>;
}
declare module 'react-redux/es/utils/verifyPlainObject.js' {
  declare module.exports: $Exports<'react-redux/es/utils/verifyPlainObject'>;
}
declare module 'react-redux/es/utils/warning.js' {
  declare module.exports: $Exports<'react-redux/es/utils/warning'>;
}
declare module 'react-redux/lib/alternate-renderers.js' {
  declare module.exports: $Exports<'react-redux/lib/alternate-renderers'>;
}
declare module 'react-redux/lib/components/connect.js' {
  declare module.exports: $Exports<'react-redux/lib/components/connect'>;
}
declare module 'react-redux/lib/components/Context.js' {
  declare module.exports: $Exports<'react-redux/lib/components/Context'>;
}
declare module 'react-redux/lib/components/Provider.js' {
  declare module.exports: $Exports<'react-redux/lib/components/Provider'>;
}
declare module 'react-redux/lib/connect/invalidArgFactory.js' {
  declare module.exports: $Exports<'react-redux/lib/connect/invalidArgFactory'>;
}
declare module 'react-redux/lib/connect/mapDispatchToProps.js' {
  declare module.exports: $Exports<'react-redux/lib/connect/mapDispatchToProps'>;
}
declare module 'react-redux/lib/connect/mapStateToProps.js' {
  declare module.exports: $Exports<'react-redux/lib/connect/mapStateToProps'>;
}
declare module 'react-redux/lib/connect/mergeProps.js' {
  declare module.exports: $Exports<'react-redux/lib/connect/mergeProps'>;
}
declare module 'react-redux/lib/connect/selectorFactory.js' {
  declare module.exports: $Exports<'react-redux/lib/connect/selectorFactory'>;
}
declare module 'react-redux/lib/connect/verifySubselectors.js' {
  declare module.exports: $Exports<'react-redux/lib/connect/verifySubselectors'>;
}
declare module 'react-redux/lib/connect/wrapMapToProps.js' {
  declare module.exports: $Exports<'react-redux/lib/connect/wrapMapToProps'>;
}
declare module 'react-redux/lib/exports.js' {
  declare module.exports: $Exports<'react-redux/lib/exports'>;
}
declare module 'react-redux/lib/hooks/useDispatch.js' {
  declare module.exports: $Exports<'react-redux/lib/hooks/useDispatch'>;
}
declare module 'react-redux/lib/hooks/useReduxContext.js' {
  declare module.exports: $Exports<'react-redux/lib/hooks/useReduxContext'>;
}
declare module 'react-redux/lib/hooks/useSelector.js' {
  declare module.exports: $Exports<'react-redux/lib/hooks/useSelector'>;
}
declare module 'react-redux/lib/hooks/useStore.js' {
  declare module.exports: $Exports<'react-redux/lib/hooks/useStore'>;
}
declare module 'react-redux/lib/index' {
  declare module.exports: $Exports<'react-redux/lib'>;
}
declare module 'react-redux/lib/index.js' {
  declare module.exports: $Exports<'react-redux/lib'>;
}
declare module 'react-redux/lib/next.js' {
  declare module.exports: $Exports<'react-redux/lib/next'>;
}
declare module 'react-redux/lib/types.js' {
  declare module.exports: $Exports<'react-redux/lib/types'>;
}
declare module 'react-redux/lib/utils/batch.js' {
  declare module.exports: $Exports<'react-redux/lib/utils/batch'>;
}
declare module 'react-redux/lib/utils/bindActionCreators.js' {
  declare module.exports: $Exports<'react-redux/lib/utils/bindActionCreators'>;
}
declare module 'react-redux/lib/utils/isPlainObject.js' {
  declare module.exports: $Exports<'react-redux/lib/utils/isPlainObject'>;
}
declare module 'react-redux/lib/utils/reactBatchedUpdates.js' {
  declare module.exports: $Exports<'react-redux/lib/utils/reactBatchedUpdates'>;
}
declare module 'react-redux/lib/utils/reactBatchedUpdates.native.js' {
  declare module.exports: $Exports<'react-redux/lib/utils/reactBatchedUpdates.native'>;
}
declare module 'react-redux/lib/utils/shallowEqual.js' {
  declare module.exports: $Exports<'react-redux/lib/utils/shallowEqual'>;
}
declare module 'react-redux/lib/utils/Subscription.js' {
  declare module.exports: $Exports<'react-redux/lib/utils/Subscription'>;
}
declare module 'react-redux/lib/utils/useIsomorphicLayoutEffect.js' {
  declare module.exports: $Exports<'react-redux/lib/utils/useIsomorphicLayoutEffect'>;
}
declare module 'react-redux/lib/utils/useIsomorphicLayoutEffect.native.js' {
  declare module.exports: $Exports<'react-redux/lib/utils/useIsomorphicLayoutEffect.native'>;
}
declare module 'react-redux/lib/utils/useSyncExternalStore.js' {
  declare module.exports: $Exports<'react-redux/lib/utils/useSyncExternalStore'>;
}
declare module 'react-redux/lib/utils/verifyPlainObject.js' {
  declare module.exports: $Exports<'react-redux/lib/utils/verifyPlainObject'>;
}
declare module 'react-redux/lib/utils/warning.js' {
  declare module.exports: $Exports<'react-redux/lib/utils/warning'>;
}
