// flow-typed signature: 9b460dd41a00d6945e055d5197287ac1
// flow-typed version: <<STUB>>/react-dnd-html5-backend_v^14.1.0/flow_v0.170.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-dnd-html5-backend'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-dnd-html5-backend' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-dnd-html5-backend/dist/cjs/BrowserDetector' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/dist/cjs/EnterLeaveCounter' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/dist/cjs/getEmptyImage' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/dist/cjs/HTML5BackendImpl' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/dist/cjs' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/dist/cjs/matchesType' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/dist/cjs/MonotonicInterpolant' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/dist/cjs/NativeDragSources/getDataFromDataTransfer' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/dist/cjs/NativeDragSources' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/dist/cjs/NativeDragSources/NativeDragSource' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/dist/cjs/NativeDragSources/nativeTypesConfig' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/dist/cjs/NativeTypes' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/dist/cjs/OffsetUtils' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/dist/cjs/OptionsReader' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/dist/cjs/types' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/dist/cjs/utils/js_utils' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/dist/esm/BrowserDetector' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/dist/esm/EnterLeaveCounter' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/dist/esm/getEmptyImage' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/dist/esm/HTML5BackendImpl' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/dist/esm' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/dist/esm/matchesType' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/dist/esm/MonotonicInterpolant' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/dist/esm/NativeDragSources/getDataFromDataTransfer' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/dist/esm/NativeDragSources' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/dist/esm/NativeDragSources/NativeDragSource' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/dist/esm/NativeDragSources/nativeTypesConfig' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/dist/esm/NativeTypes' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/dist/esm/OffsetUtils' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/dist/esm/OptionsReader' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/dist/esm/types' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/dist/esm/utils/js_utils' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/dist/umd/ReactDnDHTML5Backend' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/dist/umd/ReactDnDHTML5Backend.min' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/gulpfile' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/lib/BrowserDetector' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/lib/EnterLeaveCounter' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/lib/getEmptyImage' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/lib/HTML5BackendImpl' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/lib' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/lib/matchesType' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/lib/MonotonicInterpolant' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/lib/NativeDragSources/getDataFromDataTransfer' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/lib/NativeDragSources' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/lib/NativeDragSources/NativeDragSource' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/lib/NativeDragSources/nativeTypesConfig' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/lib/NativeTypes' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/lib/OffsetUtils' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/lib/OptionsReader' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/lib/types' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/lib/utils/js_utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-dnd-html5-backend/dist/cjs/BrowserDetector.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/dist/cjs/BrowserDetector'>;
}
declare module 'react-dnd-html5-backend/dist/cjs/EnterLeaveCounter.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/dist/cjs/EnterLeaveCounter'>;
}
declare module 'react-dnd-html5-backend/dist/cjs/getEmptyImage.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/dist/cjs/getEmptyImage'>;
}
declare module 'react-dnd-html5-backend/dist/cjs/HTML5BackendImpl.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/dist/cjs/HTML5BackendImpl'>;
}
declare module 'react-dnd-html5-backend/dist/cjs/index' {
  declare module.exports: $Exports<'react-dnd-html5-backend/dist/cjs'>;
}
declare module 'react-dnd-html5-backend/dist/cjs/index.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/dist/cjs'>;
}
declare module 'react-dnd-html5-backend/dist/cjs/matchesType.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/dist/cjs/matchesType'>;
}
declare module 'react-dnd-html5-backend/dist/cjs/MonotonicInterpolant.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/dist/cjs/MonotonicInterpolant'>;
}
declare module 'react-dnd-html5-backend/dist/cjs/NativeDragSources/getDataFromDataTransfer.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/dist/cjs/NativeDragSources/getDataFromDataTransfer'>;
}
declare module 'react-dnd-html5-backend/dist/cjs/NativeDragSources/index' {
  declare module.exports: $Exports<'react-dnd-html5-backend/dist/cjs/NativeDragSources'>;
}
declare module 'react-dnd-html5-backend/dist/cjs/NativeDragSources/index.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/dist/cjs/NativeDragSources'>;
}
declare module 'react-dnd-html5-backend/dist/cjs/NativeDragSources/NativeDragSource.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/dist/cjs/NativeDragSources/NativeDragSource'>;
}
declare module 'react-dnd-html5-backend/dist/cjs/NativeDragSources/nativeTypesConfig.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/dist/cjs/NativeDragSources/nativeTypesConfig'>;
}
declare module 'react-dnd-html5-backend/dist/cjs/NativeTypes.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/dist/cjs/NativeTypes'>;
}
declare module 'react-dnd-html5-backend/dist/cjs/OffsetUtils.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/dist/cjs/OffsetUtils'>;
}
declare module 'react-dnd-html5-backend/dist/cjs/OptionsReader.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/dist/cjs/OptionsReader'>;
}
declare module 'react-dnd-html5-backend/dist/cjs/types.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/dist/cjs/types'>;
}
declare module 'react-dnd-html5-backend/dist/cjs/utils/js_utils.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/dist/cjs/utils/js_utils'>;
}
declare module 'react-dnd-html5-backend/dist/esm/BrowserDetector.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/dist/esm/BrowserDetector'>;
}
declare module 'react-dnd-html5-backend/dist/esm/EnterLeaveCounter.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/dist/esm/EnterLeaveCounter'>;
}
declare module 'react-dnd-html5-backend/dist/esm/getEmptyImage.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/dist/esm/getEmptyImage'>;
}
declare module 'react-dnd-html5-backend/dist/esm/HTML5BackendImpl.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/dist/esm/HTML5BackendImpl'>;
}
declare module 'react-dnd-html5-backend/dist/esm/index' {
  declare module.exports: $Exports<'react-dnd-html5-backend/dist/esm'>;
}
declare module 'react-dnd-html5-backend/dist/esm/index.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/dist/esm'>;
}
declare module 'react-dnd-html5-backend/dist/esm/matchesType.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/dist/esm/matchesType'>;
}
declare module 'react-dnd-html5-backend/dist/esm/MonotonicInterpolant.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/dist/esm/MonotonicInterpolant'>;
}
declare module 'react-dnd-html5-backend/dist/esm/NativeDragSources/getDataFromDataTransfer.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/dist/esm/NativeDragSources/getDataFromDataTransfer'>;
}
declare module 'react-dnd-html5-backend/dist/esm/NativeDragSources/index' {
  declare module.exports: $Exports<'react-dnd-html5-backend/dist/esm/NativeDragSources'>;
}
declare module 'react-dnd-html5-backend/dist/esm/NativeDragSources/index.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/dist/esm/NativeDragSources'>;
}
declare module 'react-dnd-html5-backend/dist/esm/NativeDragSources/NativeDragSource.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/dist/esm/NativeDragSources/NativeDragSource'>;
}
declare module 'react-dnd-html5-backend/dist/esm/NativeDragSources/nativeTypesConfig.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/dist/esm/NativeDragSources/nativeTypesConfig'>;
}
declare module 'react-dnd-html5-backend/dist/esm/NativeTypes.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/dist/esm/NativeTypes'>;
}
declare module 'react-dnd-html5-backend/dist/esm/OffsetUtils.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/dist/esm/OffsetUtils'>;
}
declare module 'react-dnd-html5-backend/dist/esm/OptionsReader.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/dist/esm/OptionsReader'>;
}
declare module 'react-dnd-html5-backend/dist/esm/types.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/dist/esm/types'>;
}
declare module 'react-dnd-html5-backend/dist/esm/utils/js_utils.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/dist/esm/utils/js_utils'>;
}
declare module 'react-dnd-html5-backend/dist/umd/ReactDnDHTML5Backend.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/dist/umd/ReactDnDHTML5Backend'>;
}
declare module 'react-dnd-html5-backend/dist/umd/ReactDnDHTML5Backend.min.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/dist/umd/ReactDnDHTML5Backend.min'>;
}
declare module 'react-dnd-html5-backend/gulpfile.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/gulpfile'>;
}
declare module 'react-dnd-html5-backend/lib/BrowserDetector.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/lib/BrowserDetector'>;
}
declare module 'react-dnd-html5-backend/lib/EnterLeaveCounter.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/lib/EnterLeaveCounter'>;
}
declare module 'react-dnd-html5-backend/lib/getEmptyImage.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/lib/getEmptyImage'>;
}
declare module 'react-dnd-html5-backend/lib/HTML5BackendImpl.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/lib/HTML5BackendImpl'>;
}
declare module 'react-dnd-html5-backend/lib/index' {
  declare module.exports: $Exports<'react-dnd-html5-backend/lib'>;
}
declare module 'react-dnd-html5-backend/lib/index.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/lib'>;
}
declare module 'react-dnd-html5-backend/lib/matchesType.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/lib/matchesType'>;
}
declare module 'react-dnd-html5-backend/lib/MonotonicInterpolant.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/lib/MonotonicInterpolant'>;
}
declare module 'react-dnd-html5-backend/lib/NativeDragSources/getDataFromDataTransfer.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/lib/NativeDragSources/getDataFromDataTransfer'>;
}
declare module 'react-dnd-html5-backend/lib/NativeDragSources/index' {
  declare module.exports: $Exports<'react-dnd-html5-backend/lib/NativeDragSources'>;
}
declare module 'react-dnd-html5-backend/lib/NativeDragSources/index.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/lib/NativeDragSources'>;
}
declare module 'react-dnd-html5-backend/lib/NativeDragSources/NativeDragSource.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/lib/NativeDragSources/NativeDragSource'>;
}
declare module 'react-dnd-html5-backend/lib/NativeDragSources/nativeTypesConfig.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/lib/NativeDragSources/nativeTypesConfig'>;
}
declare module 'react-dnd-html5-backend/lib/NativeTypes.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/lib/NativeTypes'>;
}
declare module 'react-dnd-html5-backend/lib/OffsetUtils.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/lib/OffsetUtils'>;
}
declare module 'react-dnd-html5-backend/lib/OptionsReader.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/lib/OptionsReader'>;
}
declare module 'react-dnd-html5-backend/lib/types.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/lib/types'>;
}
declare module 'react-dnd-html5-backend/lib/utils/js_utils.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/lib/utils/js_utils'>;
}
