// flow-typed signature: 5bd3294ca5da892b36dfafe8e2d7db2b
// flow-typed version: <<STUB>>/sonar-web-frontend-reporters_v^2.1.1/flow_v0.176.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sonar-web-frontend-reporters'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sonar-web-frontend-reporters' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sonar-web-frontend-reporters/cssReporter' {
  declare module.exports: any;
}

declare module 'sonar-web-frontend-reporters/esLintAngularReporter' {
  declare module.exports: any;
}

declare module 'sonar-web-frontend-reporters/esLintReporter' {
  declare module.exports: any;
}

declare module 'sonar-web-frontend-reporters/htmlReporter' {
  declare module.exports: any;
}

declare module 'sonar-web-frontend-reporters/jsReporter' {
  declare module.exports: any;
}

declare module 'sonar-web-frontend-reporters/reporterModel' {
  declare module.exports: any;
}

declare module 'sonar-web-frontend-reporters/scssReporter' {
  declare module.exports: any;
}

declare module 'sonar-web-frontend-reporters/sonarWebReporters' {
  declare module.exports: any;
}

declare module 'sonar-web-frontend-reporters/tslintReporter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sonar-web-frontend-reporters/cssReporter.js' {
  declare module.exports: $Exports<'sonar-web-frontend-reporters/cssReporter'>;
}
declare module 'sonar-web-frontend-reporters/esLintAngularReporter.js' {
  declare module.exports: $Exports<'sonar-web-frontend-reporters/esLintAngularReporter'>;
}
declare module 'sonar-web-frontend-reporters/esLintReporter.js' {
  declare module.exports: $Exports<'sonar-web-frontend-reporters/esLintReporter'>;
}
declare module 'sonar-web-frontend-reporters/htmlReporter.js' {
  declare module.exports: $Exports<'sonar-web-frontend-reporters/htmlReporter'>;
}
declare module 'sonar-web-frontend-reporters/jsReporter.js' {
  declare module.exports: $Exports<'sonar-web-frontend-reporters/jsReporter'>;
}
declare module 'sonar-web-frontend-reporters/reporterModel.js' {
  declare module.exports: $Exports<'sonar-web-frontend-reporters/reporterModel'>;
}
declare module 'sonar-web-frontend-reporters/scssReporter.js' {
  declare module.exports: $Exports<'sonar-web-frontend-reporters/scssReporter'>;
}
declare module 'sonar-web-frontend-reporters/sonarWebReporters.js' {
  declare module.exports: $Exports<'sonar-web-frontend-reporters/sonarWebReporters'>;
}
declare module 'sonar-web-frontend-reporters/tslintReporter.js' {
  declare module.exports: $Exports<'sonar-web-frontend-reporters/tslintReporter'>;
}
