// flow-typed signature: 84b0f769550676d5295d8ef6d704b052
// flow-typed version: <<STUB>>/sonar-web-frontend-reporters_v^3.4.0/flow_v0.186.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sonar-web-frontend-reporters'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sonar-web-frontend-reporters' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sonar-web-frontend-reporters/build/api' {
  declare module.exports: any;
}

declare module 'sonar-web-frontend-reporters/build/cli' {
  declare module.exports: any;
}

declare module 'sonar-web-frontend-reporters/build/reporter.enum' {
  declare module.exports: any;
}

declare module 'sonar-web-frontend-reporters/build/reporter.factory' {
  declare module.exports: any;
}

declare module 'sonar-web-frontend-reporters/build/reporter' {
  declare module.exports: any;
}

declare module 'sonar-web-frontend-reporters/build/reporters' {
  declare module.exports: any;
}

declare module 'sonar-web-frontend-reporters/build/reporters/csslint.reporter' {
  declare module.exports: any;
}

declare module 'sonar-web-frontend-reporters/build/reporters/eslint-angular.reporter' {
  declare module.exports: any;
}

declare module 'sonar-web-frontend-reporters/build/reporters/eslint.reporter' {
  declare module.exports: any;
}

declare module 'sonar-web-frontend-reporters/build/reporters/htmlhint.reporter' {
  declare module.exports: any;
}

declare module 'sonar-web-frontend-reporters/build/reporters/jshint.reporter' {
  declare module.exports: any;
}

declare module 'sonar-web-frontend-reporters/build/reporters/sass-to-scsslint.reporter' {
  declare module.exports: any;
}

declare module 'sonar-web-frontend-reporters/build/reporters/sasslint.reporter' {
  declare module.exports: any;
}

declare module 'sonar-web-frontend-reporters/build/reporters/sassTranslator' {
  declare module.exports: any;
}

declare module 'sonar-web-frontend-reporters/build/reporters/tslint.reporter' {
  declare module.exports: any;
}

declare module 'sonar-web-frontend-reporters/lib/api' {
  declare module.exports: any;
}

declare module 'sonar-web-frontend-reporters/lib/cli' {
  declare module.exports: any;
}

declare module 'sonar-web-frontend-reporters/lib/reporter.enum' {
  declare module.exports: any;
}

declare module 'sonar-web-frontend-reporters/lib/reporter.factory' {
  declare module.exports: any;
}

declare module 'sonar-web-frontend-reporters/lib/reporter' {
  declare module.exports: any;
}

declare module 'sonar-web-frontend-reporters/lib/reporters' {
  declare module.exports: any;
}

declare module 'sonar-web-frontend-reporters/lib/reporters/csslint.reporter' {
  declare module.exports: any;
}

declare module 'sonar-web-frontend-reporters/lib/reporters/eslint-angular.reporter' {
  declare module.exports: any;
}

declare module 'sonar-web-frontend-reporters/lib/reporters/eslint.reporter' {
  declare module.exports: any;
}

declare module 'sonar-web-frontend-reporters/lib/reporters/htmlhint.reporter' {
  declare module.exports: any;
}

declare module 'sonar-web-frontend-reporters/lib/reporters/jshint.reporter' {
  declare module.exports: any;
}

declare module 'sonar-web-frontend-reporters/lib/reporters/sass-to-scsslint.reporter' {
  declare module.exports: any;
}

declare module 'sonar-web-frontend-reporters/lib/reporters/sasslint.reporter' {
  declare module.exports: any;
}

declare module 'sonar-web-frontend-reporters/lib/reporters/sassTranslator' {
  declare module.exports: any;
}

declare module 'sonar-web-frontend-reporters/lib/reporters/tslint.reporter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sonar-web-frontend-reporters/build/api.js' {
  declare module.exports: $Exports<'sonar-web-frontend-reporters/build/api'>;
}
declare module 'sonar-web-frontend-reporters/build/cli.js' {
  declare module.exports: $Exports<'sonar-web-frontend-reporters/build/cli'>;
}
declare module 'sonar-web-frontend-reporters/build/reporter.enum.js' {
  declare module.exports: $Exports<'sonar-web-frontend-reporters/build/reporter.enum'>;
}
declare module 'sonar-web-frontend-reporters/build/reporter.factory.js' {
  declare module.exports: $Exports<'sonar-web-frontend-reporters/build/reporter.factory'>;
}
declare module 'sonar-web-frontend-reporters/build/reporter.js' {
  declare module.exports: $Exports<'sonar-web-frontend-reporters/build/reporter'>;
}
declare module 'sonar-web-frontend-reporters/build/reporters.js' {
  declare module.exports: $Exports<'sonar-web-frontend-reporters/build/reporters'>;
}
declare module 'sonar-web-frontend-reporters/build/reporters/csslint.reporter.js' {
  declare module.exports: $Exports<'sonar-web-frontend-reporters/build/reporters/csslint.reporter'>;
}
declare module 'sonar-web-frontend-reporters/build/reporters/eslint-angular.reporter.js' {
  declare module.exports: $Exports<'sonar-web-frontend-reporters/build/reporters/eslint-angular.reporter'>;
}
declare module 'sonar-web-frontend-reporters/build/reporters/eslint.reporter.js' {
  declare module.exports: $Exports<'sonar-web-frontend-reporters/build/reporters/eslint.reporter'>;
}
declare module 'sonar-web-frontend-reporters/build/reporters/htmlhint.reporter.js' {
  declare module.exports: $Exports<'sonar-web-frontend-reporters/build/reporters/htmlhint.reporter'>;
}
declare module 'sonar-web-frontend-reporters/build/reporters/jshint.reporter.js' {
  declare module.exports: $Exports<'sonar-web-frontend-reporters/build/reporters/jshint.reporter'>;
}
declare module 'sonar-web-frontend-reporters/build/reporters/sass-to-scsslint.reporter.js' {
  declare module.exports: $Exports<'sonar-web-frontend-reporters/build/reporters/sass-to-scsslint.reporter'>;
}
declare module 'sonar-web-frontend-reporters/build/reporters/sasslint.reporter.js' {
  declare module.exports: $Exports<'sonar-web-frontend-reporters/build/reporters/sasslint.reporter'>;
}
declare module 'sonar-web-frontend-reporters/build/reporters/sassTranslator.js' {
  declare module.exports: $Exports<'sonar-web-frontend-reporters/build/reporters/sassTranslator'>;
}
declare module 'sonar-web-frontend-reporters/build/reporters/tslint.reporter.js' {
  declare module.exports: $Exports<'sonar-web-frontend-reporters/build/reporters/tslint.reporter'>;
}
declare module 'sonar-web-frontend-reporters/lib/api.js' {
  declare module.exports: $Exports<'sonar-web-frontend-reporters/lib/api'>;
}
declare module 'sonar-web-frontend-reporters/lib/cli.js' {
  declare module.exports: $Exports<'sonar-web-frontend-reporters/lib/cli'>;
}
declare module 'sonar-web-frontend-reporters/lib/reporter.enum.js' {
  declare module.exports: $Exports<'sonar-web-frontend-reporters/lib/reporter.enum'>;
}
declare module 'sonar-web-frontend-reporters/lib/reporter.factory.js' {
  declare module.exports: $Exports<'sonar-web-frontend-reporters/lib/reporter.factory'>;
}
declare module 'sonar-web-frontend-reporters/lib/reporter.js' {
  declare module.exports: $Exports<'sonar-web-frontend-reporters/lib/reporter'>;
}
declare module 'sonar-web-frontend-reporters/lib/reporters.js' {
  declare module.exports: $Exports<'sonar-web-frontend-reporters/lib/reporters'>;
}
declare module 'sonar-web-frontend-reporters/lib/reporters/csslint.reporter.js' {
  declare module.exports: $Exports<'sonar-web-frontend-reporters/lib/reporters/csslint.reporter'>;
}
declare module 'sonar-web-frontend-reporters/lib/reporters/eslint-angular.reporter.js' {
  declare module.exports: $Exports<'sonar-web-frontend-reporters/lib/reporters/eslint-angular.reporter'>;
}
declare module 'sonar-web-frontend-reporters/lib/reporters/eslint.reporter.js' {
  declare module.exports: $Exports<'sonar-web-frontend-reporters/lib/reporters/eslint.reporter'>;
}
declare module 'sonar-web-frontend-reporters/lib/reporters/htmlhint.reporter.js' {
  declare module.exports: $Exports<'sonar-web-frontend-reporters/lib/reporters/htmlhint.reporter'>;
}
declare module 'sonar-web-frontend-reporters/lib/reporters/jshint.reporter.js' {
  declare module.exports: $Exports<'sonar-web-frontend-reporters/lib/reporters/jshint.reporter'>;
}
declare module 'sonar-web-frontend-reporters/lib/reporters/sass-to-scsslint.reporter.js' {
  declare module.exports: $Exports<'sonar-web-frontend-reporters/lib/reporters/sass-to-scsslint.reporter'>;
}
declare module 'sonar-web-frontend-reporters/lib/reporters/sasslint.reporter.js' {
  declare module.exports: $Exports<'sonar-web-frontend-reporters/lib/reporters/sasslint.reporter'>;
}
declare module 'sonar-web-frontend-reporters/lib/reporters/sassTranslator.js' {
  declare module.exports: $Exports<'sonar-web-frontend-reporters/lib/reporters/sassTranslator'>;
}
declare module 'sonar-web-frontend-reporters/lib/reporters/tslint.reporter.js' {
  declare module.exports: $Exports<'sonar-web-frontend-reporters/lib/reporters/tslint.reporter'>;
}
