// flow-typed signature: 7330750c9438d49718b9c43be384f2d7
// flow-typed version: <<STUB>>/@graphql-codegen/cli_v^2.12.0/flow_v0.186.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@graphql-codegen/cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@graphql-codegen/cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@graphql-codegen/cli/cjs/bin' {
  declare module.exports: any;
}

declare module '@graphql-codegen/cli/cjs/cli' {
  declare module.exports: any;
}

declare module '@graphql-codegen/cli/cjs/codegen' {
  declare module.exports: any;
}

declare module '@graphql-codegen/cli/cjs/config' {
  declare module.exports: any;
}

declare module '@graphql-codegen/cli/cjs/generate-and-save' {
  declare module.exports: any;
}

declare module '@graphql-codegen/cli/cjs/graphql-config' {
  declare module.exports: any;
}

declare module '@graphql-codegen/cli/cjs/hooks' {
  declare module.exports: any;
}

declare module '@graphql-codegen/cli/cjs' {
  declare module.exports: any;
}

declare module '@graphql-codegen/cli/cjs/init/helpers' {
  declare module.exports: any;
}

declare module '@graphql-codegen/cli/cjs/init' {
  declare module.exports: any;
}

declare module '@graphql-codegen/cli/cjs/init/plugins' {
  declare module.exports: any;
}

declare module '@graphql-codegen/cli/cjs/init/questions' {
  declare module.exports: any;
}

declare module '@graphql-codegen/cli/cjs/init/targets' {
  declare module.exports: any;
}

declare module '@graphql-codegen/cli/cjs/init/types' {
  declare module.exports: any;
}

declare module '@graphql-codegen/cli/cjs/load' {
  declare module.exports: any;
}

declare module '@graphql-codegen/cli/cjs/plugins' {
  declare module.exports: any;
}

declare module '@graphql-codegen/cli/cjs/presets' {
  declare module.exports: any;
}

declare module '@graphql-codegen/cli/cjs/utils/cli-error' {
  declare module.exports: any;
}

declare module '@graphql-codegen/cli/cjs/utils/debugging' {
  declare module.exports: any;
}

declare module '@graphql-codegen/cli/cjs/utils/file-system' {
  declare module.exports: any;
}

declare module '@graphql-codegen/cli/cjs/utils/get-latest-version' {
  declare module.exports: any;
}

declare module '@graphql-codegen/cli/cjs/utils/logger' {
  declare module.exports: any;
}

declare module '@graphql-codegen/cli/cjs/utils/watcher' {
  declare module.exports: any;
}

declare module '@graphql-codegen/cli/esm/bin' {
  declare module.exports: any;
}

declare module '@graphql-codegen/cli/esm/cli' {
  declare module.exports: any;
}

declare module '@graphql-codegen/cli/esm/codegen' {
  declare module.exports: any;
}

declare module '@graphql-codegen/cli/esm/config' {
  declare module.exports: any;
}

declare module '@graphql-codegen/cli/esm/generate-and-save' {
  declare module.exports: any;
}

declare module '@graphql-codegen/cli/esm/graphql-config' {
  declare module.exports: any;
}

declare module '@graphql-codegen/cli/esm/hooks' {
  declare module.exports: any;
}

declare module '@graphql-codegen/cli/esm' {
  declare module.exports: any;
}

declare module '@graphql-codegen/cli/esm/init/helpers' {
  declare module.exports: any;
}

declare module '@graphql-codegen/cli/esm/init' {
  declare module.exports: any;
}

declare module '@graphql-codegen/cli/esm/init/plugins' {
  declare module.exports: any;
}

declare module '@graphql-codegen/cli/esm/init/questions' {
  declare module.exports: any;
}

declare module '@graphql-codegen/cli/esm/init/targets' {
  declare module.exports: any;
}

declare module '@graphql-codegen/cli/esm/init/types' {
  declare module.exports: any;
}

declare module '@graphql-codegen/cli/esm/load' {
  declare module.exports: any;
}

declare module '@graphql-codegen/cli/esm/plugins' {
  declare module.exports: any;
}

declare module '@graphql-codegen/cli/esm/presets' {
  declare module.exports: any;
}

declare module '@graphql-codegen/cli/esm/utils/cli-error' {
  declare module.exports: any;
}

declare module '@graphql-codegen/cli/esm/utils/debugging' {
  declare module.exports: any;
}

declare module '@graphql-codegen/cli/esm/utils/file-system' {
  declare module.exports: any;
}

declare module '@graphql-codegen/cli/esm/utils/get-latest-version' {
  declare module.exports: any;
}

declare module '@graphql-codegen/cli/esm/utils/logger' {
  declare module.exports: any;
}

declare module '@graphql-codegen/cli/esm/utils/watcher' {
  declare module.exports: any;
}

// Filename aliases
declare module '@graphql-codegen/cli/cjs/bin.js' {
  declare module.exports: $Exports<'@graphql-codegen/cli/cjs/bin'>;
}
declare module '@graphql-codegen/cli/cjs/cli.js' {
  declare module.exports: $Exports<'@graphql-codegen/cli/cjs/cli'>;
}
declare module '@graphql-codegen/cli/cjs/codegen.js' {
  declare module.exports: $Exports<'@graphql-codegen/cli/cjs/codegen'>;
}
declare module '@graphql-codegen/cli/cjs/config.js' {
  declare module.exports: $Exports<'@graphql-codegen/cli/cjs/config'>;
}
declare module '@graphql-codegen/cli/cjs/generate-and-save.js' {
  declare module.exports: $Exports<'@graphql-codegen/cli/cjs/generate-and-save'>;
}
declare module '@graphql-codegen/cli/cjs/graphql-config.js' {
  declare module.exports: $Exports<'@graphql-codegen/cli/cjs/graphql-config'>;
}
declare module '@graphql-codegen/cli/cjs/hooks.js' {
  declare module.exports: $Exports<'@graphql-codegen/cli/cjs/hooks'>;
}
declare module '@graphql-codegen/cli/cjs/index' {
  declare module.exports: $Exports<'@graphql-codegen/cli/cjs'>;
}
declare module '@graphql-codegen/cli/cjs/index.js' {
  declare module.exports: $Exports<'@graphql-codegen/cli/cjs'>;
}
declare module '@graphql-codegen/cli/cjs/init/helpers.js' {
  declare module.exports: $Exports<'@graphql-codegen/cli/cjs/init/helpers'>;
}
declare module '@graphql-codegen/cli/cjs/init/index' {
  declare module.exports: $Exports<'@graphql-codegen/cli/cjs/init'>;
}
declare module '@graphql-codegen/cli/cjs/init/index.js' {
  declare module.exports: $Exports<'@graphql-codegen/cli/cjs/init'>;
}
declare module '@graphql-codegen/cli/cjs/init/plugins.js' {
  declare module.exports: $Exports<'@graphql-codegen/cli/cjs/init/plugins'>;
}
declare module '@graphql-codegen/cli/cjs/init/questions.js' {
  declare module.exports: $Exports<'@graphql-codegen/cli/cjs/init/questions'>;
}
declare module '@graphql-codegen/cli/cjs/init/targets.js' {
  declare module.exports: $Exports<'@graphql-codegen/cli/cjs/init/targets'>;
}
declare module '@graphql-codegen/cli/cjs/init/types.js' {
  declare module.exports: $Exports<'@graphql-codegen/cli/cjs/init/types'>;
}
declare module '@graphql-codegen/cli/cjs/load.js' {
  declare module.exports: $Exports<'@graphql-codegen/cli/cjs/load'>;
}
declare module '@graphql-codegen/cli/cjs/plugins.js' {
  declare module.exports: $Exports<'@graphql-codegen/cli/cjs/plugins'>;
}
declare module '@graphql-codegen/cli/cjs/presets.js' {
  declare module.exports: $Exports<'@graphql-codegen/cli/cjs/presets'>;
}
declare module '@graphql-codegen/cli/cjs/utils/cli-error.js' {
  declare module.exports: $Exports<'@graphql-codegen/cli/cjs/utils/cli-error'>;
}
declare module '@graphql-codegen/cli/cjs/utils/debugging.js' {
  declare module.exports: $Exports<'@graphql-codegen/cli/cjs/utils/debugging'>;
}
declare module '@graphql-codegen/cli/cjs/utils/file-system.js' {
  declare module.exports: $Exports<'@graphql-codegen/cli/cjs/utils/file-system'>;
}
declare module '@graphql-codegen/cli/cjs/utils/get-latest-version.js' {
  declare module.exports: $Exports<'@graphql-codegen/cli/cjs/utils/get-latest-version'>;
}
declare module '@graphql-codegen/cli/cjs/utils/logger.js' {
  declare module.exports: $Exports<'@graphql-codegen/cli/cjs/utils/logger'>;
}
declare module '@graphql-codegen/cli/cjs/utils/watcher.js' {
  declare module.exports: $Exports<'@graphql-codegen/cli/cjs/utils/watcher'>;
}
declare module '@graphql-codegen/cli/esm/bin.js' {
  declare module.exports: $Exports<'@graphql-codegen/cli/esm/bin'>;
}
declare module '@graphql-codegen/cli/esm/cli.js' {
  declare module.exports: $Exports<'@graphql-codegen/cli/esm/cli'>;
}
declare module '@graphql-codegen/cli/esm/codegen.js' {
  declare module.exports: $Exports<'@graphql-codegen/cli/esm/codegen'>;
}
declare module '@graphql-codegen/cli/esm/config.js' {
  declare module.exports: $Exports<'@graphql-codegen/cli/esm/config'>;
}
declare module '@graphql-codegen/cli/esm/generate-and-save.js' {
  declare module.exports: $Exports<'@graphql-codegen/cli/esm/generate-and-save'>;
}
declare module '@graphql-codegen/cli/esm/graphql-config.js' {
  declare module.exports: $Exports<'@graphql-codegen/cli/esm/graphql-config'>;
}
declare module '@graphql-codegen/cli/esm/hooks.js' {
  declare module.exports: $Exports<'@graphql-codegen/cli/esm/hooks'>;
}
declare module '@graphql-codegen/cli/esm/index' {
  declare module.exports: $Exports<'@graphql-codegen/cli/esm'>;
}
declare module '@graphql-codegen/cli/esm/index.js' {
  declare module.exports: $Exports<'@graphql-codegen/cli/esm'>;
}
declare module '@graphql-codegen/cli/esm/init/helpers.js' {
  declare module.exports: $Exports<'@graphql-codegen/cli/esm/init/helpers'>;
}
declare module '@graphql-codegen/cli/esm/init/index' {
  declare module.exports: $Exports<'@graphql-codegen/cli/esm/init'>;
}
declare module '@graphql-codegen/cli/esm/init/index.js' {
  declare module.exports: $Exports<'@graphql-codegen/cli/esm/init'>;
}
declare module '@graphql-codegen/cli/esm/init/plugins.js' {
  declare module.exports: $Exports<'@graphql-codegen/cli/esm/init/plugins'>;
}
declare module '@graphql-codegen/cli/esm/init/questions.js' {
  declare module.exports: $Exports<'@graphql-codegen/cli/esm/init/questions'>;
}
declare module '@graphql-codegen/cli/esm/init/targets.js' {
  declare module.exports: $Exports<'@graphql-codegen/cli/esm/init/targets'>;
}
declare module '@graphql-codegen/cli/esm/init/types.js' {
  declare module.exports: $Exports<'@graphql-codegen/cli/esm/init/types'>;
}
declare module '@graphql-codegen/cli/esm/load.js' {
  declare module.exports: $Exports<'@graphql-codegen/cli/esm/load'>;
}
declare module '@graphql-codegen/cli/esm/plugins.js' {
  declare module.exports: $Exports<'@graphql-codegen/cli/esm/plugins'>;
}
declare module '@graphql-codegen/cli/esm/presets.js' {
  declare module.exports: $Exports<'@graphql-codegen/cli/esm/presets'>;
}
declare module '@graphql-codegen/cli/esm/utils/cli-error.js' {
  declare module.exports: $Exports<'@graphql-codegen/cli/esm/utils/cli-error'>;
}
declare module '@graphql-codegen/cli/esm/utils/debugging.js' {
  declare module.exports: $Exports<'@graphql-codegen/cli/esm/utils/debugging'>;
}
declare module '@graphql-codegen/cli/esm/utils/file-system.js' {
  declare module.exports: $Exports<'@graphql-codegen/cli/esm/utils/file-system'>;
}
declare module '@graphql-codegen/cli/esm/utils/get-latest-version.js' {
  declare module.exports: $Exports<'@graphql-codegen/cli/esm/utils/get-latest-version'>;
}
declare module '@graphql-codegen/cli/esm/utils/logger.js' {
  declare module.exports: $Exports<'@graphql-codegen/cli/esm/utils/logger'>;
}
declare module '@graphql-codegen/cli/esm/utils/watcher.js' {
  declare module.exports: $Exports<'@graphql-codegen/cli/esm/utils/watcher'>;
}
