// flow-typed signature: d5d49702f11eb6f5f08fb46cef33a644
// flow-typed version: <<STUB>>/@graphql-codegen/cli_v^2.4.0/flow_v0.170.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@graphql-codegen/cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@graphql-codegen/cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@graphql-codegen/cli/bin' {
  declare module.exports: any;
}

// Filename aliases
declare module '@graphql-codegen/cli/bin.js' {
  declare module.exports: $Exports<'@graphql-codegen/cli/bin'>;
}
declare module '@graphql-codegen/cli/index' {
  declare module.exports: $Exports<'@graphql-codegen/cli'>;
}
declare module '@graphql-codegen/cli/index.js' {
  declare module.exports: $Exports<'@graphql-codegen/cli'>;
}
