// flow-typed signature: e770bfb38f4ecdb319904e996330ac3d
// flow-typed version: <<STUB>>/@graphql-codegen/flow_v^2.1.4/flow_v0.160.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@graphql-codegen/flow'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@graphql-codegen/flow' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@graphql-codegen/flow/index' {
  declare module.exports: $Exports<'@graphql-codegen/flow'>;
}
declare module '@graphql-codegen/flow/index.js' {
  declare module.exports: $Exports<'@graphql-codegen/flow'>;
}
