// flow-typed signature: efbd099f0c41a639fa9a1002d6ad94f5
// flow-typed version: <<STUB>>/@graphql-codegen/introspection_v^2.1.0/flow_v0.160.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@graphql-codegen/introspection'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@graphql-codegen/introspection' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@graphql-codegen/introspection/index' {
  declare module.exports: $Exports<'@graphql-codegen/introspection'>;
}
declare module '@graphql-codegen/introspection/index.js' {
  declare module.exports: $Exports<'@graphql-codegen/introspection'>;
}
