spring:
  session:
    store-type: redis
    redis:
      flush-mode: immediate
      namespace: spring:session
    timeout: ${server.servlet.session.timeout}
  redis:
    host: ${APPL_REDIS_HOST}
    password: ${APPL_REDIS_PASSWORD}
    port: ${APPL_REDIS_PORT}
server:
  servlet:
    session:
      timeout: 3600
