apiVersion: v1
kind: Pod
metadata:
  name: pg-client
spec:
  containers:
    - image: bitnami/postgresql:14-debian-10
      name: postgresql
      env:
        - name: ALLOW_EMPTY_PASSWORD
          value: 'yes'
