apiVersion: v1
kind: Service
metadata:
  name: postgresql-nodeport
spec:
  type: NodePort
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
      protocol: TCP
  selector:
    app: pgpool
