// flow-typed signature: 72efc5df6e96d1fb5c30f216c07543b5
// flow-typed version: <<STUB>>/@playwright/test_v^1.21.1/flow_v0.176.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@playwright/test'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@playwright/test' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@playwright/test/cli' {
  declare module.exports: any;
}

declare module '@playwright/test/lib/ci' {
  declare module.exports: any;
}

declare module '@playwright/test/lib/cli' {
  declare module.exports: any;
}

declare module '@playwright/test/lib/dispatcher' {
  declare module.exports: any;
}

declare module '@playwright/test/lib/expect' {
  declare module.exports: any;
}

declare module '@playwright/test/lib/experimentalLoader' {
  declare module.exports: any;
}

declare module '@playwright/test/lib/fixtures' {
  declare module.exports: any;
}

declare module '@playwright/test/lib/globals' {
  declare module.exports: any;
}

declare module '@playwright/test/lib' {
  declare module.exports: any;
}

declare module '@playwright/test/lib/ipc' {
  declare module.exports: any;
}

declare module '@playwright/test/lib/loader' {
  declare module.exports: any;
}

declare module '@playwright/test/lib/matchers/matchers' {
  declare module.exports: any;
}

declare module '@playwright/test/lib/matchers/toBeTruthy' {
  declare module.exports: any;
}

declare module '@playwright/test/lib/matchers/toEqual' {
  declare module.exports: any;
}

declare module '@playwright/test/lib/matchers/toMatchSnapshot' {
  declare module.exports: any;
}

declare module '@playwright/test/lib/matchers/toMatchText' {
  declare module.exports: any;
}

declare module '@playwright/test/lib/mount' {
  declare module.exports: any;
}

declare module '@playwright/test/lib/profiler' {
  declare module.exports: any;
}

declare module '@playwright/test/lib/project' {
  declare module.exports: any;
}

declare module '@playwright/test/lib/reporters/base' {
  declare module.exports: any;
}

declare module '@playwright/test/lib/reporters/dot' {
  declare module.exports: any;
}

declare module '@playwright/test/lib/reporters/empty' {
  declare module.exports: any;
}

declare module '@playwright/test/lib/reporters/github' {
  declare module.exports: any;
}

declare module '@playwright/test/lib/reporters/html' {
  declare module.exports: any;
}

declare module '@playwright/test/lib/reporters/json' {
  declare module.exports: any;
}

declare module '@playwright/test/lib/reporters/junit' {
  declare module.exports: any;
}

declare module '@playwright/test/lib/reporters/line' {
  declare module.exports: any;
}

declare module '@playwright/test/lib/reporters/list' {
  declare module.exports: any;
}

declare module '@playwright/test/lib/reporters/multiplexer' {
  declare module.exports: any;
}

declare module '@playwright/test/lib/reporters/raw' {
  declare module.exports: any;
}

declare module '@playwright/test/lib/runner' {
  declare module.exports: any;
}

declare module '@playwright/test/lib/sigIntWatcher' {
  declare module.exports: any;
}

declare module '@playwright/test/lib/test' {
  declare module.exports: any;
}

declare module '@playwright/test/lib/testInfo' {
  declare module.exports: any;
}

declare module '@playwright/test/lib/testType' {
  declare module.exports: any;
}

declare module '@playwright/test/lib/third_party/tsconfig-loader' {
  declare module.exports: any;
}

declare module '@playwright/test/lib/timeoutManager' {
  declare module.exports: any;
}

declare module '@playwright/test/lib/transform' {
  declare module.exports: any;
}

declare module '@playwright/test/lib/tsxTransform' {
  declare module.exports: any;
}

declare module '@playwright/test/lib/types' {
  declare module.exports: any;
}

declare module '@playwright/test/lib/util' {
  declare module.exports: any;
}

declare module '@playwright/test/lib/webServer' {
  declare module.exports: any;
}

declare module '@playwright/test/lib/worker' {
  declare module.exports: any;
}

declare module '@playwright/test/lib/workerRunner' {
  declare module.exports: any;
}

declare module '@playwright/test/reporter' {
  declare module.exports: any;
}

// Filename aliases
declare module '@playwright/test/cli.js' {
  declare module.exports: $Exports<'@playwright/test/cli'>;
}
declare module '@playwright/test/index' {
  declare module.exports: $Exports<'@playwright/test'>;
}
declare module '@playwright/test/index.js' {
  declare module.exports: $Exports<'@playwright/test'>;
}
declare module '@playwright/test/lib/ci.js' {
  declare module.exports: $Exports<'@playwright/test/lib/ci'>;
}
declare module '@playwright/test/lib/cli.js' {
  declare module.exports: $Exports<'@playwright/test/lib/cli'>;
}
declare module '@playwright/test/lib/dispatcher.js' {
  declare module.exports: $Exports<'@playwright/test/lib/dispatcher'>;
}
declare module '@playwright/test/lib/expect.js' {
  declare module.exports: $Exports<'@playwright/test/lib/expect'>;
}
declare module '@playwright/test/lib/experimentalLoader.js' {
  declare module.exports: $Exports<'@playwright/test/lib/experimentalLoader'>;
}
declare module '@playwright/test/lib/fixtures.js' {
  declare module.exports: $Exports<'@playwright/test/lib/fixtures'>;
}
declare module '@playwright/test/lib/globals.js' {
  declare module.exports: $Exports<'@playwright/test/lib/globals'>;
}
declare module '@playwright/test/lib/index' {
  declare module.exports: $Exports<'@playwright/test/lib'>;
}
declare module '@playwright/test/lib/index.js' {
  declare module.exports: $Exports<'@playwright/test/lib'>;
}
declare module '@playwright/test/lib/ipc.js' {
  declare module.exports: $Exports<'@playwright/test/lib/ipc'>;
}
declare module '@playwright/test/lib/loader.js' {
  declare module.exports: $Exports<'@playwright/test/lib/loader'>;
}
declare module '@playwright/test/lib/matchers/matchers.js' {
  declare module.exports: $Exports<'@playwright/test/lib/matchers/matchers'>;
}
declare module '@playwright/test/lib/matchers/toBeTruthy.js' {
  declare module.exports: $Exports<'@playwright/test/lib/matchers/toBeTruthy'>;
}
declare module '@playwright/test/lib/matchers/toEqual.js' {
  declare module.exports: $Exports<'@playwright/test/lib/matchers/toEqual'>;
}
declare module '@playwright/test/lib/matchers/toMatchSnapshot.js' {
  declare module.exports: $Exports<'@playwright/test/lib/matchers/toMatchSnapshot'>;
}
declare module '@playwright/test/lib/matchers/toMatchText.js' {
  declare module.exports: $Exports<'@playwright/test/lib/matchers/toMatchText'>;
}
declare module '@playwright/test/lib/mount.js' {
  declare module.exports: $Exports<'@playwright/test/lib/mount'>;
}
declare module '@playwright/test/lib/profiler.js' {
  declare module.exports: $Exports<'@playwright/test/lib/profiler'>;
}
declare module '@playwright/test/lib/project.js' {
  declare module.exports: $Exports<'@playwright/test/lib/project'>;
}
declare module '@playwright/test/lib/reporters/base.js' {
  declare module.exports: $Exports<'@playwright/test/lib/reporters/base'>;
}
declare module '@playwright/test/lib/reporters/dot.js' {
  declare module.exports: $Exports<'@playwright/test/lib/reporters/dot'>;
}
declare module '@playwright/test/lib/reporters/empty.js' {
  declare module.exports: $Exports<'@playwright/test/lib/reporters/empty'>;
}
declare module '@playwright/test/lib/reporters/github.js' {
  declare module.exports: $Exports<'@playwright/test/lib/reporters/github'>;
}
declare module '@playwright/test/lib/reporters/html.js' {
  declare module.exports: $Exports<'@playwright/test/lib/reporters/html'>;
}
declare module '@playwright/test/lib/reporters/json.js' {
  declare module.exports: $Exports<'@playwright/test/lib/reporters/json'>;
}
declare module '@playwright/test/lib/reporters/junit.js' {
  declare module.exports: $Exports<'@playwright/test/lib/reporters/junit'>;
}
declare module '@playwright/test/lib/reporters/line.js' {
  declare module.exports: $Exports<'@playwright/test/lib/reporters/line'>;
}
declare module '@playwright/test/lib/reporters/list.js' {
  declare module.exports: $Exports<'@playwright/test/lib/reporters/list'>;
}
declare module '@playwright/test/lib/reporters/multiplexer.js' {
  declare module.exports: $Exports<'@playwright/test/lib/reporters/multiplexer'>;
}
declare module '@playwright/test/lib/reporters/raw.js' {
  declare module.exports: $Exports<'@playwright/test/lib/reporters/raw'>;
}
declare module '@playwright/test/lib/runner.js' {
  declare module.exports: $Exports<'@playwright/test/lib/runner'>;
}
declare module '@playwright/test/lib/sigIntWatcher.js' {
  declare module.exports: $Exports<'@playwright/test/lib/sigIntWatcher'>;
}
declare module '@playwright/test/lib/test.js' {
  declare module.exports: $Exports<'@playwright/test/lib/test'>;
}
declare module '@playwright/test/lib/testInfo.js' {
  declare module.exports: $Exports<'@playwright/test/lib/testInfo'>;
}
declare module '@playwright/test/lib/testType.js' {
  declare module.exports: $Exports<'@playwright/test/lib/testType'>;
}
declare module '@playwright/test/lib/third_party/tsconfig-loader.js' {
  declare module.exports: $Exports<'@playwright/test/lib/third_party/tsconfig-loader'>;
}
declare module '@playwright/test/lib/timeoutManager.js' {
  declare module.exports: $Exports<'@playwright/test/lib/timeoutManager'>;
}
declare module '@playwright/test/lib/transform.js' {
  declare module.exports: $Exports<'@playwright/test/lib/transform'>;
}
declare module '@playwright/test/lib/tsxTransform.js' {
  declare module.exports: $Exports<'@playwright/test/lib/tsxTransform'>;
}
declare module '@playwright/test/lib/types.js' {
  declare module.exports: $Exports<'@playwright/test/lib/types'>;
}
declare module '@playwright/test/lib/util.js' {
  declare module.exports: $Exports<'@playwright/test/lib/util'>;
}
declare module '@playwright/test/lib/webServer.js' {
  declare module.exports: $Exports<'@playwright/test/lib/webServer'>;
}
declare module '@playwright/test/lib/worker.js' {
  declare module.exports: $Exports<'@playwright/test/lib/worker'>;
}
declare module '@playwright/test/lib/workerRunner.js' {
  declare module.exports: $Exports<'@playwright/test/lib/workerRunner'>;
}
declare module '@playwright/test/reporter.js' {
  declare module.exports: $Exports<'@playwright/test/reporter'>;
}
