version: 2.1
orbs:
  secrethub: secrethub/cli@1.1.0
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: cimg/node:14.16.0-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm ci
      - run:
          name: List
          command: npm run lint
      - run:
          name: Test
          command: npm test
      - run:
          name: Build
          command: npm run fullbuild
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/project
          paths: .
  publish:
    working_directory: ~/project
    docker:
      - image: cimg/base:stable
    environment:
      DOCKERHUB_PASSWORD: secrethub://bbortt/event-planner/circle/canary/dockerhub/password
      DOCKERHUB_USERNAME: secrethub://bbortt/event-planner/circle/canary/dockerhub/username
      PIPELINE_NUMBER: << pipeline.number >>
    steps:
      - attach_workspace:
          at: ~/project
      - secrethub/install
      - setup_remote_docker
      - run: docker build . -t bbortt/event-planner:$PIPELINE_NUMBER
      - run: echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run: docker push bbortt/event-planner:$PIPELINE_NUMBER
      - run: .circleci/git_tag_and_push.sh $PIPELINE_NUMBER
workflows:
  fullbuild:
    jobs:
      - build:
          filters:
            branches:
              only: /^(release|canary)$/
      - deploy:
          requires:
            - test-build
          filters:
            branches:
              only: /^(release|canary)$/
