version: '2'
services:
  event-planner-postgresql:
    image: postgres:13-alpine
    # volumes:
    #     - ~/volumes/jhipster/eventPlanner/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=event_planner
      - POSTGRES_PASSWORD=event_planner_password
    ports:
      - 5432:5432
