# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.3'
services:
  # Database
  postgres:
    image: postgres:14.1-alpine
    container_name: event-planner_postgres
    environment:
      - POSTGRES_DB=event_planner
      - POSTGRES_USER=event_planner
      - POSTGRES_PASSWORD=event_planner_password
    volumes:
      - pgdata:/var/lib/postgres/data
      - ./../src/main/resources/db/scripts:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
volumes:
  pgdata:
