version: '3.3'
services:
  postgres:
    image: postgres:13-alpine
    container_name: event-planner_postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=event_planner
      - POSTGRES_PASSWORD=event_planner_password
    ports:
      - 5432:5432
volumes:
  pgdata:
