@startuml

actor user as act
cloud client as req

node "pgpool service" as svc
component "pgpool deployment" as dep

package "postgresql statefulset" {
    component "postgresql-0" as c1
    component "postgresql-1" as c2
    component "postgresql-2" as c3

    database "pv-0" as db1
    database "pv-1" as db2
    database "pv-2" as db3
}

act --> svc
req --> svc

svc --> dep

dep --> c1
dep --> c2
dep --> c3

c1 --> db1
c2 --> db2
c3 --> db3

@enduml
