logging:
  level:
    root: debug
spring:
  cloud:
    gateway:
      routes:
        - id: projects-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/rest/v1/projects
            - Path=/api/rest/v1/projects/**
