kind: Service
apiVersion: v1
metadata:
  name: logstash
spec:
  type: ClusterIP
  ports:
    - name: logstash
      port: 5044
      targetPort: logstash
      protocol: TCP
  selector:
    app: logstash
