# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.3'
services:
  gateway:
    image: event-planner/gateway:local
    volumes:
      - ./application.yml:/home/eventplanner/config/application.yml
    environment:
      APPL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      # note: this must be the keycloak *public* url!
      # on localhost, edit your hosts file: keycloak -> 127.0.0.1
      APPL_OIDC_ISSUER_URI: http://keycloak:9080/auth/realms/jhipster
      APPL_OIDC_CLIENT_ID: web_app
      APPL_OIDC_CLIENT_SECRET: web_app
