// flow-typed signature: 0b41f5ad4c56baaa3293834bd407e1ff
// flow-typed version: <<STUB>>/@testing-library/user-event_v^14.1.1/flow_v0.176.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@testing-library/user-event'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@testing-library/user-event' {
  declare module.exports: any;
}
