apiVersion: apps/v1
kind: Deployment
metadata:
  name: services-user
  labels:
    app: services-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: services-user
  template:
    metadata:
      labels:
        app: services-user
    spec:
      containers:
        - name: services-user
          image: bbortt/event-planner-services-user:468
          env:
            - name: APPL_JDBC_URL
              value: "jdbc:postgresql://kubernetes.docker.internal:5432/service_user"
            - name: APPL_JDBC_USERNAME
              value: "service_user_user"
            - name: APPL_JDBC_PASSWORD
              value: "service_user_password"
            - name: APPL_KAFKA_BOOTSTRAP_SERVERS
              value: "kubernetes.docker.internal:9092"
            - name: APPL_OIDC_ISSUER_URI
              value: "http://kubernetes.docker.internal:9080/auth/realms/jhipster"
            - name: APPL_OIDC_CLIENT_ID
              value: "internal"
            - name: APPL_OIDC_CLIENT_SECRET
              value: "internal"
          resources:
            requests:
              memory: 128Mi
            limits:
              memory: 256Mi
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
