// flow-typed signature: b9fa74874d31717474449f6fe8c60827
// flow-typed version: <<STUB>>/@apollo/client_v^3.6.9/flow_v0.186.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@apollo/client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@apollo/client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@apollo/client/cache/cache.cjs.native' {
  declare module.exports: any;
}

declare module '@apollo/client/cache/core/cache' {
  declare module.exports: any;
}

declare module '@apollo/client/cache/core/types/Cache' {
  declare module.exports: any;
}

declare module '@apollo/client/cache/core/types/common' {
  declare module.exports: any;
}

declare module '@apollo/client/cache/core/types/DataProxy' {
  declare module.exports: any;
}

declare module '@apollo/client/cache' {
  declare module.exports: any;
}

declare module '@apollo/client/cache/inmemory/__mocks__/optimism' {
  declare module.exports: any;
}

declare module '@apollo/client/cache/inmemory/entityStore' {
  declare module.exports: any;
}

declare module '@apollo/client/cache/inmemory/fixPolyfills' {
  declare module.exports: any;
}

declare module '@apollo/client/cache/inmemory/fixPolyfills.native' {
  declare module.exports: any;
}

declare module '@apollo/client/cache/inmemory/helpers' {
  declare module.exports: any;
}

declare module '@apollo/client/cache/inmemory/inMemoryCache' {
  declare module.exports: any;
}

declare module '@apollo/client/cache/inmemory/key-extractor' {
  declare module.exports: any;
}

declare module '@apollo/client/cache/inmemory/object-canon' {
  declare module.exports: any;
}

declare module '@apollo/client/cache/inmemory/policies' {
  declare module.exports: any;
}

declare module '@apollo/client/cache/inmemory/reactiveVars' {
  declare module.exports: any;
}

declare module '@apollo/client/cache/inmemory/readFromStore' {
  declare module.exports: any;
}

declare module '@apollo/client/cache/inmemory/types' {
  declare module.exports: any;
}

declare module '@apollo/client/cache/inmemory/writeToStore' {
  declare module.exports: any;
}

declare module '@apollo/client/config/jest/setup' {
  declare module.exports: any;
}

declare module '@apollo/client/core/ApolloClient' {
  declare module.exports: any;
}

declare module '@apollo/client/core/core.cjs.native' {
  declare module.exports: any;
}

declare module '@apollo/client/core' {
  declare module.exports: any;
}

declare module '@apollo/client/core/LocalState' {
  declare module.exports: any;
}

declare module '@apollo/client/core/networkStatus' {
  declare module.exports: any;
}

declare module '@apollo/client/core/ObservableQuery' {
  declare module.exports: any;
}

declare module '@apollo/client/core/QueryInfo' {
  declare module.exports: any;
}

declare module '@apollo/client/core/QueryManager' {
  declare module.exports: any;
}

declare module '@apollo/client/core/types' {
  declare module.exports: any;
}

declare module '@apollo/client/core/watchQueryOptions' {
  declare module.exports: any;
}

declare module '@apollo/client/errors/errors.cjs.native' {
  declare module.exports: any;
}

declare module '@apollo/client/errors' {
  declare module.exports: any;
}

declare module '@apollo/client/invariantErrorCodes' {
  declare module.exports: any;
}

declare module '@apollo/client/link/batch-http/batch-http.cjs.native' {
  declare module.exports: any;
}

declare module '@apollo/client/link/batch-http/batchHttpLink' {
  declare module.exports: any;
}

declare module '@apollo/client/link/batch-http' {
  declare module.exports: any;
}

declare module '@apollo/client/link/batch/batch.cjs.native' {
  declare module.exports: any;
}

declare module '@apollo/client/link/batch/batching' {
  declare module.exports: any;
}

declare module '@apollo/client/link/batch/batchLink' {
  declare module.exports: any;
}

declare module '@apollo/client/link/batch' {
  declare module.exports: any;
}

declare module '@apollo/client/link/context/context.cjs.native' {
  declare module.exports: any;
}

declare module '@apollo/client/link/context' {
  declare module.exports: any;
}

declare module '@apollo/client/link/core/ApolloLink' {
  declare module.exports: any;
}

declare module '@apollo/client/link/core/concat' {
  declare module.exports: any;
}

declare module '@apollo/client/link/core/core.cjs.native' {
  declare module.exports: any;
}

declare module '@apollo/client/link/core/empty' {
  declare module.exports: any;
}

declare module '@apollo/client/link/core/execute' {
  declare module.exports: any;
}

declare module '@apollo/client/link/core/from' {
  declare module.exports: any;
}

declare module '@apollo/client/link/core' {
  declare module.exports: any;
}

declare module '@apollo/client/link/core/split' {
  declare module.exports: any;
}

declare module '@apollo/client/link/core/types' {
  declare module.exports: any;
}

declare module '@apollo/client/link/error/error.cjs.native' {
  declare module.exports: any;
}

declare module '@apollo/client/link/error' {
  declare module.exports: any;
}

declare module '@apollo/client/link/http/checkFetcher' {
  declare module.exports: any;
}

declare module '@apollo/client/link/http/createHttpLink' {
  declare module.exports: any;
}

declare module '@apollo/client/link/http/createSignalIfSupported' {
  declare module.exports: any;
}

declare module '@apollo/client/link/http/http.cjs.native' {
  declare module.exports: any;
}

declare module '@apollo/client/link/http/HttpLink' {
  declare module.exports: any;
}

declare module '@apollo/client/link/http' {
  declare module.exports: any;
}

declare module '@apollo/client/link/http/parseAndCheckHttpResponse' {
  declare module.exports: any;
}

declare module '@apollo/client/link/http/rewriteURIForGET' {
  declare module.exports: any;
}

declare module '@apollo/client/link/http/selectHttpOptionsAndBody' {
  declare module.exports: any;
}

declare module '@apollo/client/link/http/selectURI' {
  declare module.exports: any;
}

declare module '@apollo/client/link/http/serializeFetchParameter' {
  declare module.exports: any;
}

declare module '@apollo/client/link/persisted-queries' {
  declare module.exports: any;
}

declare module '@apollo/client/link/persisted-queries/persisted-queries.cjs.native' {
  declare module.exports: any;
}

declare module '@apollo/client/link/retry/delayFunction' {
  declare module.exports: any;
}

declare module '@apollo/client/link/retry' {
  declare module.exports: any;
}

declare module '@apollo/client/link/retry/retry.cjs.native' {
  declare module.exports: any;
}

declare module '@apollo/client/link/retry/retryFunction' {
  declare module.exports: any;
}

declare module '@apollo/client/link/retry/retryLink' {
  declare module.exports: any;
}

declare module '@apollo/client/link/schema' {
  declare module.exports: any;
}

declare module '@apollo/client/link/schema/schema.cjs.native' {
  declare module.exports: any;
}

declare module '@apollo/client/link/subscriptions' {
  declare module.exports: any;
}

declare module '@apollo/client/link/subscriptions/subscriptions.cjs.native' {
  declare module.exports: any;
}

declare module '@apollo/client/link/utils/createOperation' {
  declare module.exports: any;
}

declare module '@apollo/client/link/utils/fromError' {
  declare module.exports: any;
}

declare module '@apollo/client/link/utils/fromPromise' {
  declare module.exports: any;
}

declare module '@apollo/client/link/utils' {
  declare module.exports: any;
}

declare module '@apollo/client/link/utils/throwServerError' {
  declare module.exports: any;
}

declare module '@apollo/client/link/utils/toPromise' {
  declare module.exports: any;
}

declare module '@apollo/client/link/utils/transformOperation' {
  declare module.exports: any;
}

declare module '@apollo/client/link/utils/utils.cjs.native' {
  declare module.exports: any;
}

declare module '@apollo/client/link/utils/validateOperation' {
  declare module.exports: any;
}

declare module '@apollo/client/link/ws' {
  declare module.exports: any;
}

declare module '@apollo/client/link/ws/ws.cjs.native' {
  declare module.exports: any;
}

declare module '@apollo/client/main.cjs.native' {
  declare module.exports: any;
}

declare module '@apollo/client/react/components/components.cjs.native' {
  declare module.exports: any;
}

declare module '@apollo/client/react/components' {
  declare module.exports: any;
}

declare module '@apollo/client/react/components/Mutation' {
  declare module.exports: any;
}

declare module '@apollo/client/react/components/Query' {
  declare module.exports: any;
}

declare module '@apollo/client/react/components/Subscription' {
  declare module.exports: any;
}

declare module '@apollo/client/react/components/types' {
  declare module.exports: any;
}

declare module '@apollo/client/react/context/ApolloConsumer' {
  declare module.exports: any;
}

declare module '@apollo/client/react/context/ApolloContext' {
  declare module.exports: any;
}

declare module '@apollo/client/react/context/ApolloProvider' {
  declare module.exports: any;
}

declare module '@apollo/client/react/context/context.cjs.native' {
  declare module.exports: any;
}

declare module '@apollo/client/react/context' {
  declare module.exports: any;
}

declare module '@apollo/client/react/hoc/graphql' {
  declare module.exports: any;
}

declare module '@apollo/client/react/hoc/hoc-utils' {
  declare module.exports: any;
}

declare module '@apollo/client/react/hoc/hoc.cjs.native' {
  declare module.exports: any;
}

declare module '@apollo/client/react/hoc' {
  declare module.exports: any;
}

declare module '@apollo/client/react/hoc/mutation-hoc' {
  declare module.exports: any;
}

declare module '@apollo/client/react/hoc/query-hoc' {
  declare module.exports: any;
}

declare module '@apollo/client/react/hoc/subscription-hoc' {
  declare module.exports: any;
}

declare module '@apollo/client/react/hoc/types' {
  declare module.exports: any;
}

declare module '@apollo/client/react/hoc/withApollo' {
  declare module.exports: any;
}

declare module '@apollo/client/react/hooks/hooks.cjs.native' {
  declare module.exports: any;
}

declare module '@apollo/client/react/hooks' {
  declare module.exports: any;
}

declare module '@apollo/client/react/hooks/useApolloClient' {
  declare module.exports: any;
}

declare module '@apollo/client/react/hooks/useLazyQuery' {
  declare module.exports: any;
}

declare module '@apollo/client/react/hooks/useMutation' {
  declare module.exports: any;
}

declare module '@apollo/client/react/hooks/useQuery' {
  declare module.exports: any;
}

declare module '@apollo/client/react/hooks/useReactiveVar' {
  declare module.exports: any;
}

declare module '@apollo/client/react/hooks/useSubscription' {
  declare module.exports: any;
}

declare module '@apollo/client/react/hooks/useSyncExternalStore' {
  declare module.exports: any;
}

declare module '@apollo/client/react' {
  declare module.exports: any;
}

declare module '@apollo/client/react/parser' {
  declare module.exports: any;
}

declare module '@apollo/client/react/parser/parser.cjs.native' {
  declare module.exports: any;
}

declare module '@apollo/client/react/react.cjs.native' {
  declare module.exports: any;
}

declare module '@apollo/client/react/ssr/getDataFromTree' {
  declare module.exports: any;
}

declare module '@apollo/client/react/ssr' {
  declare module.exports: any;
}

declare module '@apollo/client/react/ssr/RenderPromises' {
  declare module.exports: any;
}

declare module '@apollo/client/react/ssr/renderToStringWithData' {
  declare module.exports: any;
}

declare module '@apollo/client/react/ssr/ssr.cjs.native' {
  declare module.exports: any;
}

declare module '@apollo/client/react/types/types' {
  declare module.exports: any;
}

declare module '@apollo/client/testing/core/core.cjs.native' {
  declare module.exports: any;
}

declare module '@apollo/client/testing/core' {
  declare module.exports: any;
}

declare module '@apollo/client/testing/core/itAsync' {
  declare module.exports: any;
}

declare module '@apollo/client/testing/core/mocking/mockClient' {
  declare module.exports: any;
}

declare module '@apollo/client/testing/core/mocking/mockFetch' {
  declare module.exports: any;
}

declare module '@apollo/client/testing/core/mocking/mockLink' {
  declare module.exports: any;
}

declare module '@apollo/client/testing/core/mocking/mockQueryManager' {
  declare module.exports: any;
}

declare module '@apollo/client/testing/core/mocking/mockSubscriptionLink' {
  declare module.exports: any;
}

declare module '@apollo/client/testing/core/mocking/mockWatchQuery' {
  declare module.exports: any;
}

declare module '@apollo/client/testing/core/observableToPromise' {
  declare module.exports: any;
}

declare module '@apollo/client/testing/core/subscribeAndCount' {
  declare module.exports: any;
}

declare module '@apollo/client/testing/core/withConsoleSpy' {
  declare module.exports: any;
}

declare module '@apollo/client/testing/core/wrap' {
  declare module.exports: any;
}

declare module '@apollo/client/testing' {
  declare module.exports: any;
}

declare module '@apollo/client/testing/react/MockedProvider' {
  declare module.exports: any;
}

declare module '@apollo/client/testing/testing.cjs.native' {
  declare module.exports: any;
}

declare module '@apollo/client/utilities/common/arrays' {
  declare module.exports: any;
}

declare module '@apollo/client/utilities/common/canUse' {
  declare module.exports: any;
}

declare module '@apollo/client/utilities/common/cloneDeep' {
  declare module.exports: any;
}

declare module '@apollo/client/utilities/common/compact' {
  declare module.exports: any;
}

declare module '@apollo/client/utilities/common/errorHandling' {
  declare module.exports: any;
}

declare module '@apollo/client/utilities/common/filterInPlace' {
  declare module.exports: any;
}

declare module '@apollo/client/utilities/common/makeUniqueId' {
  declare module.exports: any;
}

declare module '@apollo/client/utilities/common/maybeDeepFreeze' {
  declare module.exports: any;
}

declare module '@apollo/client/utilities/common/mergeDeep' {
  declare module.exports: any;
}

declare module '@apollo/client/utilities/common/mergeOptions' {
  declare module.exports: any;
}

declare module '@apollo/client/utilities/common/objects' {
  declare module.exports: any;
}

declare module '@apollo/client/utilities/common/stringifyForDisplay' {
  declare module.exports: any;
}

declare module '@apollo/client/utilities/globals/DEV' {
  declare module.exports: any;
}

declare module '@apollo/client/utilities/globals/fix-graphql' {
  declare module.exports: any;
}

declare module '@apollo/client/utilities/globals/global' {
  declare module.exports: any;
}

declare module '@apollo/client/utilities/globals/globals.cjs.native' {
  declare module.exports: any;
}

declare module '@apollo/client/utilities/globals' {
  declare module.exports: any;
}

declare module '@apollo/client/utilities/globals/maybe' {
  declare module.exports: any;
}

declare module '@apollo/client/utilities/graphql/directives' {
  declare module.exports: any;
}

declare module '@apollo/client/utilities/graphql/fragments' {
  declare module.exports: any;
}

declare module '@apollo/client/utilities/graphql/getFromAST' {
  declare module.exports: any;
}

declare module '@apollo/client/utilities/graphql/storeUtils' {
  declare module.exports: any;
}

declare module '@apollo/client/utilities/graphql/transform' {
  declare module.exports: any;
}

declare module '@apollo/client/utilities' {
  declare module.exports: any;
}

declare module '@apollo/client/utilities/observables/asyncMap' {
  declare module.exports: any;
}

declare module '@apollo/client/utilities/observables/Concast' {
  declare module.exports: any;
}

declare module '@apollo/client/utilities/observables/iteration' {
  declare module.exports: any;
}

declare module '@apollo/client/utilities/observables/Observable' {
  declare module.exports: any;
}

declare module '@apollo/client/utilities/observables/subclassing' {
  declare module.exports: any;
}

declare module '@apollo/client/utilities/policies/pagination' {
  declare module.exports: any;
}

declare module '@apollo/client/utilities/types/IsStrictlyAny' {
  declare module.exports: any;
}

declare module '@apollo/client/utilities/utilities.cjs.native' {
  declare module.exports: any;
}

declare module '@apollo/client/version' {
  declare module.exports: any;
}

// Filename aliases
declare module '@apollo/client/cache/cache.cjs.native.js' {
  declare module.exports: $Exports<'@apollo/client/cache/cache.cjs.native'>;
}
declare module '@apollo/client/cache/core/cache.js' {
  declare module.exports: $Exports<'@apollo/client/cache/core/cache'>;
}
declare module '@apollo/client/cache/core/types/Cache.js' {
  declare module.exports: $Exports<'@apollo/client/cache/core/types/Cache'>;
}
declare module '@apollo/client/cache/core/types/common.js' {
  declare module.exports: $Exports<'@apollo/client/cache/core/types/common'>;
}
declare module '@apollo/client/cache/core/types/DataProxy.js' {
  declare module.exports: $Exports<'@apollo/client/cache/core/types/DataProxy'>;
}
declare module '@apollo/client/cache/index' {
  declare module.exports: $Exports<'@apollo/client/cache'>;
}
declare module '@apollo/client/cache/index.js' {
  declare module.exports: $Exports<'@apollo/client/cache'>;
}
declare module '@apollo/client/cache/inmemory/__mocks__/optimism.js' {
  declare module.exports: $Exports<'@apollo/client/cache/inmemory/__mocks__/optimism'>;
}
declare module '@apollo/client/cache/inmemory/entityStore.js' {
  declare module.exports: $Exports<'@apollo/client/cache/inmemory/entityStore'>;
}
declare module '@apollo/client/cache/inmemory/fixPolyfills.js' {
  declare module.exports: $Exports<'@apollo/client/cache/inmemory/fixPolyfills'>;
}
declare module '@apollo/client/cache/inmemory/fixPolyfills.native.js' {
  declare module.exports: $Exports<'@apollo/client/cache/inmemory/fixPolyfills.native'>;
}
declare module '@apollo/client/cache/inmemory/helpers.js' {
  declare module.exports: $Exports<'@apollo/client/cache/inmemory/helpers'>;
}
declare module '@apollo/client/cache/inmemory/inMemoryCache.js' {
  declare module.exports: $Exports<'@apollo/client/cache/inmemory/inMemoryCache'>;
}
declare module '@apollo/client/cache/inmemory/key-extractor.js' {
  declare module.exports: $Exports<'@apollo/client/cache/inmemory/key-extractor'>;
}
declare module '@apollo/client/cache/inmemory/object-canon.js' {
  declare module.exports: $Exports<'@apollo/client/cache/inmemory/object-canon'>;
}
declare module '@apollo/client/cache/inmemory/policies.js' {
  declare module.exports: $Exports<'@apollo/client/cache/inmemory/policies'>;
}
declare module '@apollo/client/cache/inmemory/reactiveVars.js' {
  declare module.exports: $Exports<'@apollo/client/cache/inmemory/reactiveVars'>;
}
declare module '@apollo/client/cache/inmemory/readFromStore.js' {
  declare module.exports: $Exports<'@apollo/client/cache/inmemory/readFromStore'>;
}
declare module '@apollo/client/cache/inmemory/types.js' {
  declare module.exports: $Exports<'@apollo/client/cache/inmemory/types'>;
}
declare module '@apollo/client/cache/inmemory/writeToStore.js' {
  declare module.exports: $Exports<'@apollo/client/cache/inmemory/writeToStore'>;
}
declare module '@apollo/client/config/jest/setup.js' {
  declare module.exports: $Exports<'@apollo/client/config/jest/setup'>;
}
declare module '@apollo/client/core/ApolloClient.js' {
  declare module.exports: $Exports<'@apollo/client/core/ApolloClient'>;
}
declare module '@apollo/client/core/core.cjs.native.js' {
  declare module.exports: $Exports<'@apollo/client/core/core.cjs.native'>;
}
declare module '@apollo/client/core/index' {
  declare module.exports: $Exports<'@apollo/client/core'>;
}
declare module '@apollo/client/core/index.js' {
  declare module.exports: $Exports<'@apollo/client/core'>;
}
declare module '@apollo/client/core/LocalState.js' {
  declare module.exports: $Exports<'@apollo/client/core/LocalState'>;
}
declare module '@apollo/client/core/networkStatus.js' {
  declare module.exports: $Exports<'@apollo/client/core/networkStatus'>;
}
declare module '@apollo/client/core/ObservableQuery.js' {
  declare module.exports: $Exports<'@apollo/client/core/ObservableQuery'>;
}
declare module '@apollo/client/core/QueryInfo.js' {
  declare module.exports: $Exports<'@apollo/client/core/QueryInfo'>;
}
declare module '@apollo/client/core/QueryManager.js' {
  declare module.exports: $Exports<'@apollo/client/core/QueryManager'>;
}
declare module '@apollo/client/core/types.js' {
  declare module.exports: $Exports<'@apollo/client/core/types'>;
}
declare module '@apollo/client/core/watchQueryOptions.js' {
  declare module.exports: $Exports<'@apollo/client/core/watchQueryOptions'>;
}
declare module '@apollo/client/errors/errors.cjs.native.js' {
  declare module.exports: $Exports<'@apollo/client/errors/errors.cjs.native'>;
}
declare module '@apollo/client/errors/index' {
  declare module.exports: $Exports<'@apollo/client/errors'>;
}
declare module '@apollo/client/errors/index.js' {
  declare module.exports: $Exports<'@apollo/client/errors'>;
}
declare module '@apollo/client/index' {
  declare module.exports: $Exports<'@apollo/client'>;
}
declare module '@apollo/client/index.js' {
  declare module.exports: $Exports<'@apollo/client'>;
}
declare module '@apollo/client/invariantErrorCodes.js' {
  declare module.exports: $Exports<'@apollo/client/invariantErrorCodes'>;
}
declare module '@apollo/client/link/batch-http/batch-http.cjs.native.js' {
  declare module.exports: $Exports<'@apollo/client/link/batch-http/batch-http.cjs.native'>;
}
declare module '@apollo/client/link/batch-http/batchHttpLink.js' {
  declare module.exports: $Exports<'@apollo/client/link/batch-http/batchHttpLink'>;
}
declare module '@apollo/client/link/batch-http/index' {
  declare module.exports: $Exports<'@apollo/client/link/batch-http'>;
}
declare module '@apollo/client/link/batch-http/index.js' {
  declare module.exports: $Exports<'@apollo/client/link/batch-http'>;
}
declare module '@apollo/client/link/batch/batch.cjs.native.js' {
  declare module.exports: $Exports<'@apollo/client/link/batch/batch.cjs.native'>;
}
declare module '@apollo/client/link/batch/batching.js' {
  declare module.exports: $Exports<'@apollo/client/link/batch/batching'>;
}
declare module '@apollo/client/link/batch/batchLink.js' {
  declare module.exports: $Exports<'@apollo/client/link/batch/batchLink'>;
}
declare module '@apollo/client/link/batch/index' {
  declare module.exports: $Exports<'@apollo/client/link/batch'>;
}
declare module '@apollo/client/link/batch/index.js' {
  declare module.exports: $Exports<'@apollo/client/link/batch'>;
}
declare module '@apollo/client/link/context/context.cjs.native.js' {
  declare module.exports: $Exports<'@apollo/client/link/context/context.cjs.native'>;
}
declare module '@apollo/client/link/context/index' {
  declare module.exports: $Exports<'@apollo/client/link/context'>;
}
declare module '@apollo/client/link/context/index.js' {
  declare module.exports: $Exports<'@apollo/client/link/context'>;
}
declare module '@apollo/client/link/core/ApolloLink.js' {
  declare module.exports: $Exports<'@apollo/client/link/core/ApolloLink'>;
}
declare module '@apollo/client/link/core/concat.js' {
  declare module.exports: $Exports<'@apollo/client/link/core/concat'>;
}
declare module '@apollo/client/link/core/core.cjs.native.js' {
  declare module.exports: $Exports<'@apollo/client/link/core/core.cjs.native'>;
}
declare module '@apollo/client/link/core/empty.js' {
  declare module.exports: $Exports<'@apollo/client/link/core/empty'>;
}
declare module '@apollo/client/link/core/execute.js' {
  declare module.exports: $Exports<'@apollo/client/link/core/execute'>;
}
declare module '@apollo/client/link/core/from.js' {
  declare module.exports: $Exports<'@apollo/client/link/core/from'>;
}
declare module '@apollo/client/link/core/index' {
  declare module.exports: $Exports<'@apollo/client/link/core'>;
}
declare module '@apollo/client/link/core/index.js' {
  declare module.exports: $Exports<'@apollo/client/link/core'>;
}
declare module '@apollo/client/link/core/split.js' {
  declare module.exports: $Exports<'@apollo/client/link/core/split'>;
}
declare module '@apollo/client/link/core/types.js' {
  declare module.exports: $Exports<'@apollo/client/link/core/types'>;
}
declare module '@apollo/client/link/error/error.cjs.native.js' {
  declare module.exports: $Exports<'@apollo/client/link/error/error.cjs.native'>;
}
declare module '@apollo/client/link/error/index' {
  declare module.exports: $Exports<'@apollo/client/link/error'>;
}
declare module '@apollo/client/link/error/index.js' {
  declare module.exports: $Exports<'@apollo/client/link/error'>;
}
declare module '@apollo/client/link/http/checkFetcher.js' {
  declare module.exports: $Exports<'@apollo/client/link/http/checkFetcher'>;
}
declare module '@apollo/client/link/http/createHttpLink.js' {
  declare module.exports: $Exports<'@apollo/client/link/http/createHttpLink'>;
}
declare module '@apollo/client/link/http/createSignalIfSupported.js' {
  declare module.exports: $Exports<'@apollo/client/link/http/createSignalIfSupported'>;
}
declare module '@apollo/client/link/http/http.cjs.native.js' {
  declare module.exports: $Exports<'@apollo/client/link/http/http.cjs.native'>;
}
declare module '@apollo/client/link/http/HttpLink.js' {
  declare module.exports: $Exports<'@apollo/client/link/http/HttpLink'>;
}
declare module '@apollo/client/link/http/index' {
  declare module.exports: $Exports<'@apollo/client/link/http'>;
}
declare module '@apollo/client/link/http/index.js' {
  declare module.exports: $Exports<'@apollo/client/link/http'>;
}
declare module '@apollo/client/link/http/parseAndCheckHttpResponse.js' {
  declare module.exports: $Exports<'@apollo/client/link/http/parseAndCheckHttpResponse'>;
}
declare module '@apollo/client/link/http/rewriteURIForGET.js' {
  declare module.exports: $Exports<'@apollo/client/link/http/rewriteURIForGET'>;
}
declare module '@apollo/client/link/http/selectHttpOptionsAndBody.js' {
  declare module.exports: $Exports<'@apollo/client/link/http/selectHttpOptionsAndBody'>;
}
declare module '@apollo/client/link/http/selectURI.js' {
  declare module.exports: $Exports<'@apollo/client/link/http/selectURI'>;
}
declare module '@apollo/client/link/http/serializeFetchParameter.js' {
  declare module.exports: $Exports<'@apollo/client/link/http/serializeFetchParameter'>;
}
declare module '@apollo/client/link/persisted-queries/index' {
  declare module.exports: $Exports<'@apollo/client/link/persisted-queries'>;
}
declare module '@apollo/client/link/persisted-queries/index.js' {
  declare module.exports: $Exports<'@apollo/client/link/persisted-queries'>;
}
declare module '@apollo/client/link/persisted-queries/persisted-queries.cjs.native.js' {
  declare module.exports: $Exports<'@apollo/client/link/persisted-queries/persisted-queries.cjs.native'>;
}
declare module '@apollo/client/link/retry/delayFunction.js' {
  declare module.exports: $Exports<'@apollo/client/link/retry/delayFunction'>;
}
declare module '@apollo/client/link/retry/index' {
  declare module.exports: $Exports<'@apollo/client/link/retry'>;
}
declare module '@apollo/client/link/retry/index.js' {
  declare module.exports: $Exports<'@apollo/client/link/retry'>;
}
declare module '@apollo/client/link/retry/retry.cjs.native.js' {
  declare module.exports: $Exports<'@apollo/client/link/retry/retry.cjs.native'>;
}
declare module '@apollo/client/link/retry/retryFunction.js' {
  declare module.exports: $Exports<'@apollo/client/link/retry/retryFunction'>;
}
declare module '@apollo/client/link/retry/retryLink.js' {
  declare module.exports: $Exports<'@apollo/client/link/retry/retryLink'>;
}
declare module '@apollo/client/link/schema/index' {
  declare module.exports: $Exports<'@apollo/client/link/schema'>;
}
declare module '@apollo/client/link/schema/index.js' {
  declare module.exports: $Exports<'@apollo/client/link/schema'>;
}
declare module '@apollo/client/link/schema/schema.cjs.native.js' {
  declare module.exports: $Exports<'@apollo/client/link/schema/schema.cjs.native'>;
}
declare module '@apollo/client/link/subscriptions/index' {
  declare module.exports: $Exports<'@apollo/client/link/subscriptions'>;
}
declare module '@apollo/client/link/subscriptions/index.js' {
  declare module.exports: $Exports<'@apollo/client/link/subscriptions'>;
}
declare module '@apollo/client/link/subscriptions/subscriptions.cjs.native.js' {
  declare module.exports: $Exports<'@apollo/client/link/subscriptions/subscriptions.cjs.native'>;
}
declare module '@apollo/client/link/utils/createOperation.js' {
  declare module.exports: $Exports<'@apollo/client/link/utils/createOperation'>;
}
declare module '@apollo/client/link/utils/fromError.js' {
  declare module.exports: $Exports<'@apollo/client/link/utils/fromError'>;
}
declare module '@apollo/client/link/utils/fromPromise.js' {
  declare module.exports: $Exports<'@apollo/client/link/utils/fromPromise'>;
}
declare module '@apollo/client/link/utils/index' {
  declare module.exports: $Exports<'@apollo/client/link/utils'>;
}
declare module '@apollo/client/link/utils/index.js' {
  declare module.exports: $Exports<'@apollo/client/link/utils'>;
}
declare module '@apollo/client/link/utils/throwServerError.js' {
  declare module.exports: $Exports<'@apollo/client/link/utils/throwServerError'>;
}
declare module '@apollo/client/link/utils/toPromise.js' {
  declare module.exports: $Exports<'@apollo/client/link/utils/toPromise'>;
}
declare module '@apollo/client/link/utils/transformOperation.js' {
  declare module.exports: $Exports<'@apollo/client/link/utils/transformOperation'>;
}
declare module '@apollo/client/link/utils/utils.cjs.native.js' {
  declare module.exports: $Exports<'@apollo/client/link/utils/utils.cjs.native'>;
}
declare module '@apollo/client/link/utils/validateOperation.js' {
  declare module.exports: $Exports<'@apollo/client/link/utils/validateOperation'>;
}
declare module '@apollo/client/link/ws/index' {
  declare module.exports: $Exports<'@apollo/client/link/ws'>;
}
declare module '@apollo/client/link/ws/index.js' {
  declare module.exports: $Exports<'@apollo/client/link/ws'>;
}
declare module '@apollo/client/link/ws/ws.cjs.native.js' {
  declare module.exports: $Exports<'@apollo/client/link/ws/ws.cjs.native'>;
}
declare module '@apollo/client/main.cjs.native.js' {
  declare module.exports: $Exports<'@apollo/client/main.cjs.native'>;
}
declare module '@apollo/client/react/components/components.cjs.native.js' {
  declare module.exports: $Exports<'@apollo/client/react/components/components.cjs.native'>;
}
declare module '@apollo/client/react/components/index' {
  declare module.exports: $Exports<'@apollo/client/react/components'>;
}
declare module '@apollo/client/react/components/index.js' {
  declare module.exports: $Exports<'@apollo/client/react/components'>;
}
declare module '@apollo/client/react/components/Mutation.js' {
  declare module.exports: $Exports<'@apollo/client/react/components/Mutation'>;
}
declare module '@apollo/client/react/components/Query.js' {
  declare module.exports: $Exports<'@apollo/client/react/components/Query'>;
}
declare module '@apollo/client/react/components/Subscription.js' {
  declare module.exports: $Exports<'@apollo/client/react/components/Subscription'>;
}
declare module '@apollo/client/react/components/types.js' {
  declare module.exports: $Exports<'@apollo/client/react/components/types'>;
}
declare module '@apollo/client/react/context/ApolloConsumer.js' {
  declare module.exports: $Exports<'@apollo/client/react/context/ApolloConsumer'>;
}
declare module '@apollo/client/react/context/ApolloContext.js' {
  declare module.exports: $Exports<'@apollo/client/react/context/ApolloContext'>;
}
declare module '@apollo/client/react/context/ApolloProvider.js' {
  declare module.exports: $Exports<'@apollo/client/react/context/ApolloProvider'>;
}
declare module '@apollo/client/react/context/context.cjs.native.js' {
  declare module.exports: $Exports<'@apollo/client/react/context/context.cjs.native'>;
}
declare module '@apollo/client/react/context/index' {
  declare module.exports: $Exports<'@apollo/client/react/context'>;
}
declare module '@apollo/client/react/context/index.js' {
  declare module.exports: $Exports<'@apollo/client/react/context'>;
}
declare module '@apollo/client/react/hoc/graphql.js' {
  declare module.exports: $Exports<'@apollo/client/react/hoc/graphql'>;
}
declare module '@apollo/client/react/hoc/hoc-utils.js' {
  declare module.exports: $Exports<'@apollo/client/react/hoc/hoc-utils'>;
}
declare module '@apollo/client/react/hoc/hoc.cjs.native.js' {
  declare module.exports: $Exports<'@apollo/client/react/hoc/hoc.cjs.native'>;
}
declare module '@apollo/client/react/hoc/index' {
  declare module.exports: $Exports<'@apollo/client/react/hoc'>;
}
declare module '@apollo/client/react/hoc/index.js' {
  declare module.exports: $Exports<'@apollo/client/react/hoc'>;
}
declare module '@apollo/client/react/hoc/mutation-hoc.js' {
  declare module.exports: $Exports<'@apollo/client/react/hoc/mutation-hoc'>;
}
declare module '@apollo/client/react/hoc/query-hoc.js' {
  declare module.exports: $Exports<'@apollo/client/react/hoc/query-hoc'>;
}
declare module '@apollo/client/react/hoc/subscription-hoc.js' {
  declare module.exports: $Exports<'@apollo/client/react/hoc/subscription-hoc'>;
}
declare module '@apollo/client/react/hoc/types.js' {
  declare module.exports: $Exports<'@apollo/client/react/hoc/types'>;
}
declare module '@apollo/client/react/hoc/withApollo.js' {
  declare module.exports: $Exports<'@apollo/client/react/hoc/withApollo'>;
}
declare module '@apollo/client/react/hooks/hooks.cjs.native.js' {
  declare module.exports: $Exports<'@apollo/client/react/hooks/hooks.cjs.native'>;
}
declare module '@apollo/client/react/hooks/index' {
  declare module.exports: $Exports<'@apollo/client/react/hooks'>;
}
declare module '@apollo/client/react/hooks/index.js' {
  declare module.exports: $Exports<'@apollo/client/react/hooks'>;
}
declare module '@apollo/client/react/hooks/useApolloClient.js' {
  declare module.exports: $Exports<'@apollo/client/react/hooks/useApolloClient'>;
}
declare module '@apollo/client/react/hooks/useLazyQuery.js' {
  declare module.exports: $Exports<'@apollo/client/react/hooks/useLazyQuery'>;
}
declare module '@apollo/client/react/hooks/useMutation.js' {
  declare module.exports: $Exports<'@apollo/client/react/hooks/useMutation'>;
}
declare module '@apollo/client/react/hooks/useQuery.js' {
  declare module.exports: $Exports<'@apollo/client/react/hooks/useQuery'>;
}
declare module '@apollo/client/react/hooks/useReactiveVar.js' {
  declare module.exports: $Exports<'@apollo/client/react/hooks/useReactiveVar'>;
}
declare module '@apollo/client/react/hooks/useSubscription.js' {
  declare module.exports: $Exports<'@apollo/client/react/hooks/useSubscription'>;
}
declare module '@apollo/client/react/hooks/useSyncExternalStore.js' {
  declare module.exports: $Exports<'@apollo/client/react/hooks/useSyncExternalStore'>;
}
declare module '@apollo/client/react/index' {
  declare module.exports: $Exports<'@apollo/client/react'>;
}
declare module '@apollo/client/react/index.js' {
  declare module.exports: $Exports<'@apollo/client/react'>;
}
declare module '@apollo/client/react/parser/index' {
  declare module.exports: $Exports<'@apollo/client/react/parser'>;
}
declare module '@apollo/client/react/parser/index.js' {
  declare module.exports: $Exports<'@apollo/client/react/parser'>;
}
declare module '@apollo/client/react/parser/parser.cjs.native.js' {
  declare module.exports: $Exports<'@apollo/client/react/parser/parser.cjs.native'>;
}
declare module '@apollo/client/react/react.cjs.native.js' {
  declare module.exports: $Exports<'@apollo/client/react/react.cjs.native'>;
}
declare module '@apollo/client/react/ssr/getDataFromTree.js' {
  declare module.exports: $Exports<'@apollo/client/react/ssr/getDataFromTree'>;
}
declare module '@apollo/client/react/ssr/index' {
  declare module.exports: $Exports<'@apollo/client/react/ssr'>;
}
declare module '@apollo/client/react/ssr/index.js' {
  declare module.exports: $Exports<'@apollo/client/react/ssr'>;
}
declare module '@apollo/client/react/ssr/RenderPromises.js' {
  declare module.exports: $Exports<'@apollo/client/react/ssr/RenderPromises'>;
}
declare module '@apollo/client/react/ssr/renderToStringWithData.js' {
  declare module.exports: $Exports<'@apollo/client/react/ssr/renderToStringWithData'>;
}
declare module '@apollo/client/react/ssr/ssr.cjs.native.js' {
  declare module.exports: $Exports<'@apollo/client/react/ssr/ssr.cjs.native'>;
}
declare module '@apollo/client/react/types/types.js' {
  declare module.exports: $Exports<'@apollo/client/react/types/types'>;
}
declare module '@apollo/client/testing/core/core.cjs.native.js' {
  declare module.exports: $Exports<'@apollo/client/testing/core/core.cjs.native'>;
}
declare module '@apollo/client/testing/core/index' {
  declare module.exports: $Exports<'@apollo/client/testing/core'>;
}
declare module '@apollo/client/testing/core/index.js' {
  declare module.exports: $Exports<'@apollo/client/testing/core'>;
}
declare module '@apollo/client/testing/core/itAsync.js' {
  declare module.exports: $Exports<'@apollo/client/testing/core/itAsync'>;
}
declare module '@apollo/client/testing/core/mocking/mockClient.js' {
  declare module.exports: $Exports<'@apollo/client/testing/core/mocking/mockClient'>;
}
declare module '@apollo/client/testing/core/mocking/mockFetch.js' {
  declare module.exports: $Exports<'@apollo/client/testing/core/mocking/mockFetch'>;
}
declare module '@apollo/client/testing/core/mocking/mockLink.js' {
  declare module.exports: $Exports<'@apollo/client/testing/core/mocking/mockLink'>;
}
declare module '@apollo/client/testing/core/mocking/mockQueryManager.js' {
  declare module.exports: $Exports<'@apollo/client/testing/core/mocking/mockQueryManager'>;
}
declare module '@apollo/client/testing/core/mocking/mockSubscriptionLink.js' {
  declare module.exports: $Exports<'@apollo/client/testing/core/mocking/mockSubscriptionLink'>;
}
declare module '@apollo/client/testing/core/mocking/mockWatchQuery.js' {
  declare module.exports: $Exports<'@apollo/client/testing/core/mocking/mockWatchQuery'>;
}
declare module '@apollo/client/testing/core/observableToPromise.js' {
  declare module.exports: $Exports<'@apollo/client/testing/core/observableToPromise'>;
}
declare module '@apollo/client/testing/core/subscribeAndCount.js' {
  declare module.exports: $Exports<'@apollo/client/testing/core/subscribeAndCount'>;
}
declare module '@apollo/client/testing/core/withConsoleSpy.js' {
  declare module.exports: $Exports<'@apollo/client/testing/core/withConsoleSpy'>;
}
declare module '@apollo/client/testing/core/wrap.js' {
  declare module.exports: $Exports<'@apollo/client/testing/core/wrap'>;
}
declare module '@apollo/client/testing/index' {
  declare module.exports: $Exports<'@apollo/client/testing'>;
}
declare module '@apollo/client/testing/index.js' {
  declare module.exports: $Exports<'@apollo/client/testing'>;
}
declare module '@apollo/client/testing/react/MockedProvider.js' {
  declare module.exports: $Exports<'@apollo/client/testing/react/MockedProvider'>;
}
declare module '@apollo/client/testing/testing.cjs.native.js' {
  declare module.exports: $Exports<'@apollo/client/testing/testing.cjs.native'>;
}
declare module '@apollo/client/utilities/common/arrays.js' {
  declare module.exports: $Exports<'@apollo/client/utilities/common/arrays'>;
}
declare module '@apollo/client/utilities/common/canUse.js' {
  declare module.exports: $Exports<'@apollo/client/utilities/common/canUse'>;
}
declare module '@apollo/client/utilities/common/cloneDeep.js' {
  declare module.exports: $Exports<'@apollo/client/utilities/common/cloneDeep'>;
}
declare module '@apollo/client/utilities/common/compact.js' {
  declare module.exports: $Exports<'@apollo/client/utilities/common/compact'>;
}
declare module '@apollo/client/utilities/common/errorHandling.js' {
  declare module.exports: $Exports<'@apollo/client/utilities/common/errorHandling'>;
}
declare module '@apollo/client/utilities/common/filterInPlace.js' {
  declare module.exports: $Exports<'@apollo/client/utilities/common/filterInPlace'>;
}
declare module '@apollo/client/utilities/common/makeUniqueId.js' {
  declare module.exports: $Exports<'@apollo/client/utilities/common/makeUniqueId'>;
}
declare module '@apollo/client/utilities/common/maybeDeepFreeze.js' {
  declare module.exports: $Exports<'@apollo/client/utilities/common/maybeDeepFreeze'>;
}
declare module '@apollo/client/utilities/common/mergeDeep.js' {
  declare module.exports: $Exports<'@apollo/client/utilities/common/mergeDeep'>;
}
declare module '@apollo/client/utilities/common/mergeOptions.js' {
  declare module.exports: $Exports<'@apollo/client/utilities/common/mergeOptions'>;
}
declare module '@apollo/client/utilities/common/objects.js' {
  declare module.exports: $Exports<'@apollo/client/utilities/common/objects'>;
}
declare module '@apollo/client/utilities/common/stringifyForDisplay.js' {
  declare module.exports: $Exports<'@apollo/client/utilities/common/stringifyForDisplay'>;
}
declare module '@apollo/client/utilities/globals/DEV.js' {
  declare module.exports: $Exports<'@apollo/client/utilities/globals/DEV'>;
}
declare module '@apollo/client/utilities/globals/fix-graphql.js' {
  declare module.exports: $Exports<'@apollo/client/utilities/globals/fix-graphql'>;
}
declare module '@apollo/client/utilities/globals/global.js' {
  declare module.exports: $Exports<'@apollo/client/utilities/globals/global'>;
}
declare module '@apollo/client/utilities/globals/globals.cjs.native.js' {
  declare module.exports: $Exports<'@apollo/client/utilities/globals/globals.cjs.native'>;
}
declare module '@apollo/client/utilities/globals/index' {
  declare module.exports: $Exports<'@apollo/client/utilities/globals'>;
}
declare module '@apollo/client/utilities/globals/index.js' {
  declare module.exports: $Exports<'@apollo/client/utilities/globals'>;
}
declare module '@apollo/client/utilities/globals/maybe.js' {
  declare module.exports: $Exports<'@apollo/client/utilities/globals/maybe'>;
}
declare module '@apollo/client/utilities/graphql/directives.js' {
  declare module.exports: $Exports<'@apollo/client/utilities/graphql/directives'>;
}
declare module '@apollo/client/utilities/graphql/fragments.js' {
  declare module.exports: $Exports<'@apollo/client/utilities/graphql/fragments'>;
}
declare module '@apollo/client/utilities/graphql/getFromAST.js' {
  declare module.exports: $Exports<'@apollo/client/utilities/graphql/getFromAST'>;
}
declare module '@apollo/client/utilities/graphql/storeUtils.js' {
  declare module.exports: $Exports<'@apollo/client/utilities/graphql/storeUtils'>;
}
declare module '@apollo/client/utilities/graphql/transform.js' {
  declare module.exports: $Exports<'@apollo/client/utilities/graphql/transform'>;
}
declare module '@apollo/client/utilities/index' {
  declare module.exports: $Exports<'@apollo/client/utilities'>;
}
declare module '@apollo/client/utilities/index.js' {
  declare module.exports: $Exports<'@apollo/client/utilities'>;
}
declare module '@apollo/client/utilities/observables/asyncMap.js' {
  declare module.exports: $Exports<'@apollo/client/utilities/observables/asyncMap'>;
}
declare module '@apollo/client/utilities/observables/Concast.js' {
  declare module.exports: $Exports<'@apollo/client/utilities/observables/Concast'>;
}
declare module '@apollo/client/utilities/observables/iteration.js' {
  declare module.exports: $Exports<'@apollo/client/utilities/observables/iteration'>;
}
declare module '@apollo/client/utilities/observables/Observable.js' {
  declare module.exports: $Exports<'@apollo/client/utilities/observables/Observable'>;
}
declare module '@apollo/client/utilities/observables/subclassing.js' {
  declare module.exports: $Exports<'@apollo/client/utilities/observables/subclassing'>;
}
declare module '@apollo/client/utilities/policies/pagination.js' {
  declare module.exports: $Exports<'@apollo/client/utilities/policies/pagination'>;
}
declare module '@apollo/client/utilities/types/IsStrictlyAny.js' {
  declare module.exports: $Exports<'@apollo/client/utilities/types/IsStrictlyAny'>;
}
declare module '@apollo/client/utilities/utilities.cjs.native.js' {
  declare module.exports: $Exports<'@apollo/client/utilities/utilities.cjs.native'>;
}
declare module '@apollo/client/version.js' {
  declare module.exports: $Exports<'@apollo/client/version'>;
}
