io:
  github:
    bbortt:
      event:
        planner:
          apps:
            projects:
              services:
                permission:
                  url: ${appl.permissions.service.url}
jwt:
  audience: ${appl.auth0.audience}
server:
  port: 8080
spring:
  datasource:
    url: ${appl.jdbc.url}
    username: ${appl.jdbc.username}
    password: ${appl.jdbc.password}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${appl.jwt.issuer.uri}
