io:
  github:
    bbortt:
      event:
        planner:
          apps:
            projects:
              services:
                permission:
                  url: http://localhost:8082
jwt:
  audience: http://localhost:8081
logging:
  level:
    web: debug
server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/event_planner?currentSchema=projects_service
    username: projects_service
    password: projects_service
