openapi: 3.0.1
info:
  title: Event-Planner
  description: The Event-Planner REST API definition
  contact:
    email: timon.borter@gmx.ch
  license:
    name: Apache 2.0
    url: https://github.com/bbortt/event-planner/blob/release/LICENSE
  version: 1.0.0
servers:
  - description: Localhost
    url: http://localhost:8080/api/rest
security:
  - user_auth: ['restapi:access']
tags:
  - name: member
    description: Member resource.
  - name: permission
    description: Permission resource.
  - name: project
    description: Project resource.
paths:
  /v1/members:
    post:
      tags:
        - member
      security:
        - user_auth: []
      summary: Create the project administrator member.
      description: |
        This will create the project administrator member. The administrator can
        do everything inside the project, regardles of his assigned permissions.
      operationId: createAdminMemberInProject
      parameters:
        - name: auth0UserId
          in: query
          required: true
          schema:
            type: string
            maxLength: 64
        - name: projectId
          in: query
          required: true
          schema:
            type: integer
            format: int64
      responses:
        201:
          description: Administrative member created
  /v1/permissions:
    get:
      tags:
        - permission
      security:
        - user_auth: []
      summary: Receive a list of permissions for the given project and user ID.
      description: |
        This will only return permissions for projects that the given user
        has access to.
      operationId: readPermissionsByUserAndProject
      parameters:
        - name: auth0UserId
          in: query
          required: true
          schema:
            type: string
            maxLength: 64
        - name: projectId
          in: query
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - type: array
                    items:
                      type: string
  /v1/permissions/{permission}:
    put:
      tags:
        - permission
      security:
        - user_auth: []
      summary: Assign the given permission to the project and user.
      description: |
        This will assign the permission to the given user (not the calling user)
        in a certain project. An HTTP 403 response may be returned if the calling
        user does not have the right permission (`permission:assign`).
      operationId: grantPermissionInProject
      parameters:
        - name: permission
          in: path
          required: true
          schema:
            type: string
            maxLength: 20
        - name: auth0UserId
          in: query
          required: true
          schema:
            type: string
            maxLength: 64
        - name: projectId
          in: query
          required: true
          schema:
            type: integer
            format: int64
        - name: callingAuth0UserId
          in: query
          required: true
          schema:
            type: string
            maxLength: 64
      responses:
        201:
          description: Permission assigned
        403:
          description: User does not have the necessary permissions
    delete:
      tags:
        - permission
      security:
        - user_auth: []
      summary: Revoke the given permission from a user in the project.
      description: |
        This will revoke the permission user (not the calling user) in a certain
        project. An HTTP 403 response may be returned if the calling
        user does not have the right permission (`permission:revoke`).
      operationId: revokePermissionInProject
      parameters:
        - name: permission
          in: path
          required: true
          schema:
            type: string
            maxLength: 20
        - name: auth0UserId
          in: query
          required: true
          schema:
            type: string
            maxLength: 64
        - name: projectId
          in: query
          required: true
          schema:
            type: integer
            format: int64
        - name: callingAuth0UserId
          in: query
          required: true
          schema:
            type: string
            maxLength: 64
      responses:
        204:
          description: Permission revoked
        403:
          description: User does not have the necessary permissions
  /v1/projects:
    get:
      tags:
        - project
      security:
        - user_auth: []
      summary: Receive a list of project IDs.
      description: |
        This will only return IDs of projects that the given user has access to.
      operationId: readProjectIdsByMembership
      parameters:
        - name: auth0UserId
          in: query
          schema:
            type: string
            maxLength: 64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  contents:
                    type: array
                    items:
                      type: integer
                      format: int64
  /v1/projects/{projectId}/permissions:
    get:
      tags:
        - project
      security:
        - user_auth: []
      summary: Check if the user has this permission in the project.
      description: |
        This will indicate if the given user has any of the permissions inside
        the given project by using HTTP response codes.
      operationId: hasAnyPermissionInProject
      parameters:
        - name: permissions
          in: query
          required: true
          schema:
            type: array
            items:
              type: string
              maxLength: 20
        - name: projectId
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: auth0UserId
          in: query
          required: true
          schema:
            type: string
            maxLength: 64
      responses:
        200:
          description: OK
        403:
          description: The user does not have the required role
components:
  securitySchemes:
    user_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://event-planner-dev.eu.auth0.com
          scopes:
            restapi:access: General access to the REST api.
