// flow-typed signature: 33fec18b95e1d0e8304476ed2c5eb1bf
// flow-typed version: <<STUB>>/@bbortt/owl_v^1.0.4/flow_v0.186.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@bbortt/owl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@bbortt/owl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@bbortt/owl/src/bin/owl' {
  declare module.exports: any;
}

declare module '@bbortt/owl/src/cmd/add' {
  declare module.exports: any;
}

declare module '@bbortt/owl/src/cmd/init' {
  declare module.exports: any;
}

declare module '@bbortt/owl/src/cmd/install' {
  declare module.exports: any;
}

declare module '@bbortt/owl/src/common/constants' {
  declare module.exports: any;
}

declare module '@bbortt/owl/src' {
  declare module.exports: any;
}

// Filename aliases
declare module '@bbortt/owl/src/bin/owl.js' {
  declare module.exports: $Exports<'@bbortt/owl/src/bin/owl'>;
}
declare module '@bbortt/owl/src/cmd/add.js' {
  declare module.exports: $Exports<'@bbortt/owl/src/cmd/add'>;
}
declare module '@bbortt/owl/src/cmd/init.js' {
  declare module.exports: $Exports<'@bbortt/owl/src/cmd/init'>;
}
declare module '@bbortt/owl/src/cmd/install.js' {
  declare module.exports: $Exports<'@bbortt/owl/src/cmd/install'>;
}
declare module '@bbortt/owl/src/common/constants.js' {
  declare module.exports: $Exports<'@bbortt/owl/src/common/constants'>;
}
declare module '@bbortt/owl/src/index' {
  declare module.exports: $Exports<'@bbortt/owl/src'>;
}
declare module '@bbortt/owl/src/index.js' {
  declare module.exports: $Exports<'@bbortt/owl/src'>;
}
