name: apps/frontend
on:
  push:
    branches-ignore:
      - release
    paths:
      - '.github/workflows/frontend.yml'
      - 'apps/frontend/**'
    tags-ignore:
      - '*'
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - run: ./gradlew :apps:frontend:check -PnodeInstall --no-daemon --scan
      - uses: actions/cache@v3.2.0
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ./node_modules
            ./apps/frontend/node_modules
          key: ${{ runner.os }}-gradle-${{ hashFiles('package-lock.json', 'apps/frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-
