name: Gradle CI
on:
  push:
    branches:
      - canary
      - release
  pull_request:
jobs:
  build:
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:13.1-alpine
        env:
          POSTGRES_DB: event_planner_integration
          POSTGRES_USER: event_planner
          POSTGRES_PASSWORD: event_planner_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build using Gradle
        run: |
          ./gradlew -Pprod --no-daemon -i \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.organization=bbortt-github \
          -Dsonar.login=$SONAR_TOKEN \
          dependencyUpdates check jacocoTestReport sonarqube
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Codecov coverage report
        run: bash <(curl -s https://codecov.io/bash)
      - name: Build cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.sonar/cache
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
