name: lint
on:
  pull_request:
jobs:
  commitlint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: 16
      - run: git fetch origin release
      - run: npm ci
      - run: |
          npx --no-install commitlint --from origin/release --to HEAD --verbose
  prettier:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - run: ./gradlew prettier -PnodeInstall --no-daemon --scan
      - uses: actions/cache@v3.0.10
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ./node_modules
          key: ${{ runner.os }}-gradle-${{ hashFiles('build.gradle', 'package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-
