name: apps/permissions-service
on:
  push:
    branches-ignore:
      - release
    paths:
      - '.github/workflows/permissions-service.yml'
      - 'apps/permissions-service/**'
    tags-ignore:
      - '*'
jobs:
  build:
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:14.6-alpine
        env:
          POSTGRES_DB: event_planner_test
          POSTGRES_USER: event_planner
          POSTGRES_PASSWORD: event_planner_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - run: PGPASSWORD=event_planner_password psql -h localhost -U event_planner -f apps/permissions-service/src/test/resources/db/scripts/init-permissions_service.sql event_planner_test
      - run: ./gradlew :apps:permissions-service:flywayMigrateTest --no-daemon --scan
      - run: ./gradlew :apps:permissions-service:build --no-daemon --scan
      - uses: actions/cache@v3.0.10
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ./node_modules
          key: ${{ runner.os }}-gradle-${{ hashFiles('build.gradle', 'package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-
