name: Version Previews
on:
  push:
    branches-ignore:
      - main
concurrency:
  group: preview-${{ github.ref }}
  cancel-in-progress: true
jobs:
  pipeline:
    name: 'Event Planner: Preview'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java-version: [18, 19]
    env:
      SPRING_OUTPUT_ANSI_ENABLED: DETECT
      SPRING_JPA_SHOW_SQL: false
      JHI_DISABLE_WEBPACK_LOGS: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
      - name: Backend Tests
        run: ./gradlew -DjavaVersion=${{ matrix.java-version }} test integrationTest -x webapp -x webapp_test
