name: Publish
on:
  push:
    branches:
      - release
    tags:
      - '*'
    paths:
      - '.github/version.json'
      - 'CHANGELOG.md'
jobs:
  publish:
    name: Build and Publish Docker Image
    runs-on: ubuntu-20.04
    environment: docker
    services:
      postgres:
        image: postgres:14.1-alpine
        env:
          POSTGRES_DB: event_planner_test
          POSTGRES_USER: event_planner
          POSTGRES_PASSWORD: event_planner_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - id: meta
        uses: docker/metadata-action@v4
        with:
          images: bbortt/event-planner
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: PGPASSWORD=event_planner_password psql -h localhost -U event_planner -f src/main/resources/db/scripts/init-event_planner.sql event_planner_test
      - run: |
          ./gradlew --no-daemon \
              flywayMigrateTest
          ./gradlew -Pprod --no-daemon \
              bootJar
      - uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/Dockerfile
          labels: ${{ steps.meta.outputs.labels }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
      - uses: actions/cache@v3.0.2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ./node_modules
          key: ${{ runner.os }}-gradle-${{ hashFiles('build.gradle', 'package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-
