name: NPM Build
on:
  push:
    branches:
      - 'canary'
jobs:
  build:
    name: Build Application
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm ci
      - run: npm run release -- --prerelease
      - run: npm run fullbuild
      - uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true
      - uses: actions/cache@v2
        with:
          path: |
            ./node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-
