name: NPM Pre-Release
on:
  push:
    branches:
      - 'canary'
jobs:
  build:
    name: Pre-Release Application
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npx standard-version --prerelease
      - uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.ACTION_TOKEN }}
          branch: ${{ github.ref }}
          tags: true
