name: Release Version
on:
  push:
    branches:
      - 'release'
    tags-ignore:
      - '*'
    paths-ignore:
      - '.github/version.json'
      - 'CHANGELOG.md'
jobs:
  release:
    name: Bump Standard-Version
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npx standard-version
      - run: git push --follow-tags origin ${{ github.ref }}
