name: NPM Release
on:
  push:
    branches:
      - 'release'
jobs:
  build:
    name: Release Application
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACTION_TOKEN }}
      - run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npx standard-version
      - run: |
          git push
          git push --tags
