name: release
on:
  push:
    branches:
      - release
jobs:
  docker:apps:permissions-service:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - run: ./gradlew :apps:permissions-service:quarkusBuild -Dquarkus.package.type=native -Dquarkus.native.container-build=true --no-daemon --scan
      - run: docker build -t event-planner/permissions-service apps/permissions-service
  docker:apps:projects-service:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - run: ./gradlew :apps:projects-service:bootBuildImage --imageName=event-planner/projects-service --no-daemon --scan
  release:
    runs-on: ubuntu-20.04
    environment: release
    needs: ['docker:apps:permissions-service', 'docker:apps:projects-service']
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: 16
      - run: npm ci
      - env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
        run: |
          npx --no-install semantic-release
