name: Sonar
on:
  push:
    branches:
      - release
    tags-ignore:
      - '*'
    paths-ignore:
      - '.github/version.json'
      - 'CHANGELOG.md'
  pull_request:
jobs:
  fullbuild:
    name: Analyze Application
    runs-on: ubuntu-20.04
    environment: build
    services:
      postgres:
        image: postgres:14.1-alpine
        env:
          POSTGRES_DB: event_planner_test
          POSTGRES_USER: event_planner
          POSTGRES_PASSWORD: event_planner_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: PGPASSWORD=event_planner_password psql -h localhost -U event_planner -f src/main/resources/db/scripts/init-event_planner.sql event_planner_test
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          if [ -n "$SONAR_TOKEN" ]; then export SONARQUBE_CMD="jacocoTestReport sonarqube"; fi
          ./gradlew --no-daemon \
              flywayMigrateTest
          ./gradlew -Pprod --no-daemon \
             -Dsonar.host.url=https://sonarcloud.io \
             -Dsonar.organization=bbortt-github \
             -Dsonar.login=$SONAR_TOKEN \
              check $SONARQUBE_CMD
      - uses: actions/cache@v3.0.2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ./node_modules
          key: ${{ runner.os }}-gradle-${{ hashFiles('build.gradle', 'package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-
